// Generated by tools/extract-hook.js from Frontend/src/modules/Food/pages/user/orders/OrderTracking.jsx (OrderTracking), then edited by hand
// where the web code touched the DOM. The logic is the web page's own.
/* eslint-disable react-hooks/exhaustive-deps, no-unused-vars, no-empty */
import { useParams, useSearchParams, useNavigate, useLocation } from '../../../lib/webRouter'
import { useState, useEffect, useMemo, useRef, useCallback } from 'react'
import { toast } from '../../../lib/notify'
import { Linking } from 'react-native'
import { useOrders } from '../../context/OrdersContext'
import { useProfile } from '../../context/ProfileContext'
import { useLocation as useUserLocation } from '../useLocation'
import { orderAPI, restaurantAPI } from '../../../api/food'
import { useCompanyName } from '../useCompanyName'
import { API_ORIGIN } from '../../../api/client'
import { localStore } from '../../../lib/storage'
import { window, document, navigator } from '../../../lib/webShim'

const debugLog = (...args) => {}

const debugWarn = (...args) => {}

const debugError = (...args) => {}

const getRestaurantCoordsFromOrder = (apiOrder, fallback = null) => {
  if (
    apiOrder?.restaurantId?.location?.coordinates &&
    Array.isArray(apiOrder.restaurantId.location.coordinates) &&
    apiOrder.restaurantId.location.coordinates.length >= 2
  ) {
    return apiOrder.restaurantId.location.coordinates
  }
  if (apiOrder?.restaurantId?.location?.latitude && apiOrder?.restaurantId?.location?.longitude) {
    return [apiOrder.restaurantId.location.longitude, apiOrder.restaurantId.location.latitude]
  }
  if (
    apiOrder?.restaurant?.location?.coordinates &&
    Array.isArray(apiOrder.restaurant.location.coordinates) &&
    apiOrder.restaurant.location.coordinates.length >= 2
  ) {
    return apiOrder.restaurant.location.coordinates
  }
  return fallback || null
}

const getRestaurantAddressFromOrder = (apiOrder, previousOrder = null, explicitRestaurantAddress = null) => {
  if (explicitRestaurantAddress && String(explicitRestaurantAddress).trim()) {
    return String(explicitRestaurantAddress).trim()
  }

  const location = apiOrder?.restaurantId?.location || apiOrder?.restaurant?.location || {}

  if (location?.formattedAddress && String(location.formattedAddress).trim()) {
    return String(location.formattedAddress).trim()
  }
  if (location?.address && String(location.address).trim()) {
    return String(location.address).trim()
  }
  if (location?.addressLine1 && String(location.addressLine1).trim()) {
    return String(location.addressLine1).trim()
  }

  const parts = [location?.street, location?.area, location?.city, location?.state, location?.zipCode]
    .map((value) => (value == null ? '' : String(value).trim()))
    .filter(Boolean)

  if (parts.length > 0) return parts.join(', ')

  return previousOrder?.restaurantAddress || apiOrder?.restaurantAddress || apiOrder?.restaurant?.address || 'Restaurant location'
}

const getCustomerCoordsFromApiOrder = (apiOrder, previousOrder = null) => {
  const addr = apiOrder?.address || apiOrder?.deliveryAddress || {}
  const fromLoc = addr?.location?.coordinates
  if (Array.isArray(fromLoc) && fromLoc.length >= 2) return fromLoc
  const flat = addr?.coordinates
  if (Array.isArray(flat) && flat.length >= 2) return flat

  // Some payloads provide plain object coordinates instead of GeoJSON arrays.
  const objectCoord = addr?.location || addr
  const objLat = Number(objectCoord?.lat ?? objectCoord?.latitude)
  const objLng = Number(objectCoord?.lng ?? objectCoord?.longitude)
  if (Number.isFinite(objLat) && Number.isFinite(objLng)) return [objLng, objLat]

  const prev = previousOrder?.address?.coordinates || previousOrder?.address?.location?.coordinates
  if (Array.isArray(prev) && prev.length >= 2) return prev
  return null
}

const transformOrderForTracking = (apiOrder, previousOrder = null, explicitRestaurantCoords = null, explicitRestaurantAddress = null) => {
  const restaurantCoords = explicitRestaurantCoords || getRestaurantCoordsFromOrder(apiOrder, previousOrder?.restaurantLocation?.coordinates)
  const restaurantAddress = getRestaurantAddressFromOrder(apiOrder, previousOrder, explicitRestaurantAddress)
  // API returns `deliveryAddress`; some paths use `address`
  const addr = apiOrder?.address || apiOrder?.deliveryAddress || {}
  const customerCoordsResolved = getCustomerCoordsFromApiOrder(apiOrder, previousOrder)

  return {
    id: apiOrder?.orderId || apiOrder?._id,
    mongoId: apiOrder?._id || null,
    orderId: apiOrder?.orderId || apiOrder?._id,
    restaurant: 
      apiOrder?.restaurantId?.restaurantName || 
      apiOrder?.restaurantId?.name || 
      apiOrder?.restaurantName || 
      (typeof apiOrder?.restaurant === 'string' ? apiOrder.restaurant : null) ||
      apiOrder?.restaurant?.restaurantName || 
      apiOrder?.restaurant?.name || 
      previousOrder?.restaurant || 
      'Restaurant',
    restaurantPhone:
      apiOrder?.restaurantPhone ||
      apiOrder?.restaurantId?.phone ||
      apiOrder?.restaurantId?.ownerPhone ||
      apiOrder?.restaurant?.phone ||
      apiOrder?.restaurant?.ownerPhone ||
      previousOrder?.restaurantPhone ||
      '',
    restaurantAddress,
    restaurantId: apiOrder?.restaurantId || previousOrder?.restaurantId || null,
    userId: apiOrder?.userId || previousOrder?.userId || null,
    userName: apiOrder?.userName || apiOrder?.userId?.name || apiOrder?.userId?.fullName || previousOrder?.userName || '',
    userPhone: apiOrder?.userPhone || apiOrder?.userId?.phone || previousOrder?.userPhone || '',
    address: {
      street: addr?.street || previousOrder?.address?.street || '',
      city: addr?.city || previousOrder?.address?.city || '',
      state: addr?.state || previousOrder?.address?.state || '',
      zipCode: addr?.zipCode || previousOrder?.address?.zipCode || '',
      additionalDetails: addr?.additionalDetails || previousOrder?.address?.additionalDetails || '',
      formattedAddress: addr?.formattedAddress ||
        (addr?.street && addr?.city
          ? `${addr.street}${addr.additionalDetails ? `, ${addr.additionalDetails}` : ''}, ${addr.city}${addr.state ? `, ${addr.state}` : ''}${addr.zipCode ? ` ${addr.zipCode}` : ''}`
          : previousOrder?.address?.formattedAddress || addr?.city || ''),
      coordinates: customerCoordsResolved || addr?.location?.coordinates || previousOrder?.address?.coordinates || null
    },
    restaurantLocation: {
      coordinates: restaurantCoords
    },
    items: apiOrder?.items?.map(item => ({
      name: item.name,
      variantName: item.variantName || '',
      quantity: item.quantity,
      price: item.price
    })) || previousOrder?.items || [],
    total: apiOrder?.pricing?.total || previousOrder?.total || 0,
    // Backend canonical field is orderStatus; keep legacy `status` for UI compatibility.
    status: apiOrder?.orderStatus || apiOrder?.status || previousOrder?.status || 'pending',
    deliveryPartner: apiOrder?.deliveryPartnerId ? {
      name: apiOrder.deliveryPartnerId.name || apiOrder.deliveryPartnerId.fullName || 'Delivery Partner',
      phone: apiOrder.deliveryPartnerId.phone || apiOrder.deliveryPartnerId.phoneNumber || '',
      avatar: apiOrder.deliveryPartnerId.avatar || apiOrder.deliveryPartnerId.profilePicture || null
    } : (previousOrder?.deliveryPartner || null),
    deliveryPartnerId: apiOrder?.deliveryPartnerId?._id || apiOrder?.deliveryPartnerId || apiOrder?.dispatch?.deliveryPartnerId?._id || apiOrder?.dispatch?.deliveryPartnerId || apiOrder?.assignmentInfo?.deliveryPartnerId || null,
    dispatch: apiOrder?.dispatch || previousOrder?.dispatch || null,
    assignmentInfo: apiOrder?.assignmentInfo || previousOrder?.assignmentInfo || null,
    tracking: apiOrder?.tracking || previousOrder?.tracking || {},
    deliveryState: apiOrder?.deliveryState || previousOrder?.deliveryState || null,
    scheduledAt: apiOrder?.scheduledAt || previousOrder?.scheduledAt || null,
    createdAt: apiOrder?.createdAt || previousOrder?.createdAt || null,
    preparationTime: apiOrder?.preparationTime || previousOrder?.preparationTime || 0,
    acceptedAt: apiOrder?.acceptedAt || previousOrder?.acceptedAt || null,
    totalAmount: apiOrder?.pricing?.total || apiOrder?.totalAmount || previousOrder?.totalAmount || 0,
    deliveryFee: apiOrder?.pricing?.deliveryFee || apiOrder?.deliveryFee || previousOrder?.deliveryFee || 0,
    gst: apiOrder?.pricing?.tax || apiOrder?.pricing?.gst || apiOrder?.gst || apiOrder?.tax || previousOrder?.gst || 0,
    packagingFee: apiOrder?.pricing?.packagingFee || apiOrder?.packagingFee || 0,
    platformFee: apiOrder?.pricing?.platformFee || apiOrder?.platformFee || 0,
    discount: apiOrder?.pricing?.discount || apiOrder?.discount || 0,
    subtotal: apiOrder?.pricing?.subtotal || apiOrder?.subtotal || 0,
    paymentMethod: apiOrder?.paymentMethod || apiOrder?.payment?.method || previousOrder?.paymentMethod || null,
    payment: apiOrder?.payment || previousOrder?.payment || null,
    orderType: apiOrder?.orderType || previousOrder?.orderType || 'delivery',
    // Preserve delivery OTP code received via socket event.
    // API responses intentionally strip the secret code for security,
    // so without preserving it the UI would lose the OTP on each poll refresh.
    deliveryVerification: (() => {
      const prevDV = previousOrder?.deliveryVerification || null
      const apiDV = apiOrder?.deliveryVerification || null
      const handoverOtp = apiOrder?.handoverOtp || null
      
      if (!prevDV && !apiDV && !handoverOtp) return null

      const prevDropOtp = prevDV?.dropOtp || null
      const apiDropOtp = apiDV?.dropOtp || null
      
      const merged = {
        ...(prevDV || {}),
        ...(apiDV || {})
      }

      // Prioritize: 1. Real-time handoverOtp from current API response
      // 2. Previously preserved code in local state (from socket or earlier poll)
      // 3. Nested code field in API response (if ever present)
      const finalCode = handoverOtp || prevDropOtp?.code || apiDropOtp?.code

      if (finalCode || prevDropOtp?.required || apiDropOtp?.required) {
        merged.dropOtp = {
          ...(prevDropOtp || {}),
          ...(apiDropOtp || {}),
          code: finalCode
        }
      }
      return merged
    })(),
    cancellationReason: apiOrder?.cancellationReason || previousOrder?.cancellationReason || null,
    ratings: apiOrder?.ratings || previousOrder?.ratings || {},
    restaurantRating: apiOrder?.ratings?.restaurant?.rating || apiOrder?.restaurantRating || previousOrder?.restaurantRating || null,
    deliveryPartnerRating: apiOrder?.ratings?.deliveryPartner?.rating || apiOrder?.deliveryPartnerRating || previousOrder?.deliveryPartnerRating || null,
  }
}

/**
 * Backend uses `orderStatus` (created, confirmed, preparing, ready_for_pickup, picked_up, delivered, cancelled_*).
 * In this flow `confirmed` means the user placed the order and it is waiting for restaurant acceptance.
 * `preparing` is the first true restaurant-accepted state.
 */

function mapBackendOrderStatusToUi(raw) {
  const s = String(raw || "").toLowerCase()
  if (!s || s === "pending" || s === "created" || s === "confirmed") return "placed"
  if (s === "accepted" || s === "preparing" || s === "processed") return "preparing"
  if (s === "ready" || s === "ready_for_pickup" || s === "reached_pickup" || s === "order_confirmed") return "ready"
  if (s === "picked_up" || s === "out_for_delivery" || s === "en_route_to_delivery") return "on_way"
  if (s === "reached_drop" || s === "at_drop" || s === "at_delivery") return "at_drop"
  if (s === "delivered" || s === "completed") return "delivered"
  if (s.includes("cancelled") || s === "cancelled") return "cancelled"
  return "placed"
}

function mapOrderToTrackingUiStatus(orderLike) {
  if (!orderLike) return "placed"
  const statusRaw = orderLike.status || orderLike.orderStatus
  const phase = orderLike.deliveryState?.currentPhase

  // Terminal states handled first
  if (isFoodOrderCancelledStatus(statusRaw)) return "cancelled"
  if (statusRaw === "delivered" || statusRaw === "completed") return "delivered"

  // Live Ride / Phase-based mapping (Highest priority for precision)
  const isRiderAccepted = orderLike.dispatch?.status === "accepted" || orderLike.assignmentInfo?.status === "accepted" || orderLike.deliveryPartner?.status === "accepted";
  
  if (phase === "reached_drop" || phase === "at_drop" || statusRaw === "at_drop") return "at_drop"
  if (phase === "en_route_to_delivery" || statusRaw === "picked_up" || statusRaw === "out_for_delivery") return "on_way"
  if (phase === "at_pickup" && orderLike.deliveryPartnerId && isRiderAccepted) return "at_pickup"
  if (phase === "en_route_to_pickup" && orderLike.deliveryPartnerId && isRiderAccepted) return "assigned"

  // Fallback to basic status mapping
  return mapBackendOrderStatusToUi(statusRaw)
}

/** Prefer live delivery phase when present (socket / polling include deliveryState). */

function isFoodOrderCancelledStatus(statusRaw) {
  const s = String(statusRaw || "").toLowerCase()
  return s === "cancelled" || s.includes("cancelled")
}

function normalizeLookupId(value) {
  if (value == null) return ""
  const raw = String(value).trim()
  if (!raw || raw === "undefined" || raw === "null") return ""
  return raw
}

const getGlobalLastFetchTime = (id) => {
  window.__lastOrderDetailsFetchTime = window.__lastOrderDetailsFetchTime || {};
  return window.__lastOrderDetailsFetchTime[id] || 0;
};

const setGlobalLastFetchTime = (id, time) => {
  window.__lastOrderDetailsFetchTime = window.__lastOrderDetailsFetchTime || {};
  window.__lastOrderDetailsFetchTime[id] = time;
};

export function useOrderTracking() {
  const companyName = useCompanyName()
  const navigate = useNavigate()
  const location = useLocation()
  const { orderId } = useParams()
  const [searchParams] = useSearchParams()
  const confirmed = searchParams.get("confirmed") === "true"
  const { profile, getDefaultAddress } = useProfile()
  const { location: userLiveLocation } = useUserLocation()
  const { getOrderById } = useOrders()

  const [isSocketConnected, setIsSocketConnected] = useState(() => {
    return true ? !!globalThis.orderSocketConnected : false
  })

  useEffect(() => {
    const handleConnectionChange = (e) => {
      setIsSocketConnected(!!e?.detail?.isConnected)
    }
    window.addEventListener('userSocketConnectionChange', handleConnectionChange)
    return () => {
      window.removeEventListener('userSocketConnectionChange', handleConnectionChange)
    }
  }, [])
  
  // Extract initial order from location state or context for instant 0ms rendering
  const locationOrder = location.state?.order || location.state?.placedOrder
  const contextOrder = getOrderById(orderId)
  const initialOrder = locationOrder || contextOrder || null

  // State for order data
  const [order, setOrder] = useState(() => initialOrder ? transformOrderForTracking(initialOrder) : null)
  const [loading, setLoading] = useState(() => !initialOrder)
  const [error, setError] = useState(null)

  const [showConfirmation, setShowConfirmation] = useState(confirmed)
  const [orderStatus, setOrderStatus] = useState('placed')
  const [estimatedTime, setEstimatedTime] = useState(29)
  const [isRefreshing, setIsRefreshing] = useState(false)

  const orderRef = useRef(order)
  const estimatedTimeRef = useRef(estimatedTime)

  useEffect(() => {
    orderRef.current = order
  }, [order])

  useEffect(() => {
    estimatedTimeRef.current = estimatedTime
  }, [estimatedTime])

  const isRefreshingRef = useRef(isRefreshing)
  useEffect(() => {
    isRefreshingRef.current = isRefreshing
  }, [isRefreshing])

  const [showCancelDialog, setShowCancelDialog] = useState(false)
  const [showOrderDetails, setShowOrderDetails] = useState(false)
  const [cancellationReason, setCancellationReason] = useState("")
  const [refundDestination, setRefundDestination] = useState("source")
  const [isCancelling, setIsCancelling] = useState(false)
  const [isInstructionsModalOpen, setIsInstructionsModalOpen] = useState(false)
  const [deliveryInstructions, setDeliveryInstructions] = useState("")
  const [isUpdatingInstructions, setIsUpdatingInstructions] = useState(false)
  const [resolvedLookupId, setResolvedLookupId] = useState("")
  const [timerNow, setTimerNow] = useState(() => Date.now())
  
  const navigateToHomeAfterRating = useRef(false)

  // Rating states
  const [showRatingModal, setShowRatingModal] = useState(false)
  const [selectedRestaurantRating, setSelectedRestaurantRating] = useState(null)
  const [selectedDeliveryRating, setSelectedDeliveryRating] = useState(null)
  const [restaurantFeedbackText, setRestaurantFeedbackText] = useState("")
  const [deliveryFeedbackText, setDeliveryFeedbackText] = useState("")
  const [submittingRating, setSubmittingRating] = useState(false)
  const [isLocalRated, setIsLocalRated] = useState(false)

  // Sync with localStore on load/change
  useEffect(() => {
    const key = `rated_order_${orderId}`;
    if (localStore.getItem(key) === 'true') {
      setIsLocalRated(true);
    }
  }, [orderId]);

  // Check if order is already rated
  const resRatingVal = Number(order?.ratings?.restaurant?.rating || order?.restaurantRating || 0)
  const delRatingVal = Number(order?.ratings?.deliveryPartner?.rating || order?.deliveryPartnerRating || 0)

  const hasRestaurantRating = resRatingVal > 0
  const hasDeliveryPartner = !!(order?.deliveryPartnerId || order?.deliveryPartnerName)
  const hasDeliveryRating = delRatingVal > 0
  const isOrderRated = hasRestaurantRating && (!hasDeliveryPartner || hasDeliveryRating)


  const handleOpenRating = () => {
    setSelectedRestaurantRating(order?.ratings?.restaurant?.rating || order?.restaurantRating || null)
    setSelectedDeliveryRating(order?.ratings?.deliveryPartner?.rating || order?.deliveryPartnerRating || null)
    setRestaurantFeedbackText(order?.ratings?.restaurant?.comment || "")
    setDeliveryFeedbackText(order?.ratings?.deliveryPartner?.comment || "")
    setShowRatingModal(true)
  }

  useEffect(() => {
    if (!showRatingModal && navigateToHomeAfterRating.current) {
      navigateToHomeAfterRating.current = false
      navigate("/food/user")
    }
  }, [showRatingModal])

  const handleBackClick = () => {
    const isDelivered = orderStatus === "delivered" || order?.status === "delivered" || Boolean(order?.deliveredAt)
    if (isDelivered && !isOrderRated) {
      navigateToHomeAfterRating.current = true
      handleOpenRating()
    } else {
      navigate(isDelivered ? "/food/user" : "/user/orders")
    }
  }

  const handleSubmitRating = async () => {
    const deliveryPartnerCheck = !!(order?.deliveryPartnerId || order?.deliveryPartnerName)
    const isMissingDeliveryRating = deliveryPartnerCheck && selectedDeliveryRating === null
    if (!order || selectedRestaurantRating === null || isMissingDeliveryRating) {
      toast.error("Please select all required ratings first")
      return
    }

    try {
      setSubmittingRating(true)
      const response = await orderAPI.submitOrderRatings(order.mongoId || order._id || order.id, {
        restaurantRating: selectedRestaurantRating,
        deliveryPartnerRating: deliveryPartnerCheck ? selectedDeliveryRating : undefined,
        restaurantComment: restaurantFeedbackText || undefined,
        deliveryPartnerComment: deliveryPartnerCheck ? (deliveryFeedbackText || undefined) : undefined,
      })
      
      const updatedOrderData = response?.data?.data?.order || response?.data?.order
      
      // Save rating state locally to prevent duplicate rating clicks/popups
      const oId = order.mongoId || order._id || order.id || orderId;
      localStore.setItem(`rated_order_${oId}`, "true");
      setIsLocalRated(true);

      setOrder(prev => {
        const prevRatings = prev?.ratings || {};
        const newRestRating = selectedRestaurantRating;
        const newDelivRating = selectedDeliveryRating;
        const apiRatings = updatedOrderData?.ratings || {};
        
        return {
          ...prev,
          ...(updatedOrderData || {}),
          ratings: {
            ...prevRatings,
            ...apiRatings,
            restaurant: {
              ...(prevRatings.restaurant || {}),
              ...(apiRatings.restaurant || {}),
              rating: newRestRating,
              comment: restaurantFeedbackText || prevRatings.restaurant?.comment || ""
            },
            deliveryPartner: {
              ...(prevRatings.deliveryPartner || {}),
              ...(apiRatings.deliveryPartner || {}),
              rating: newDelivRating,
              comment: deliveryFeedbackText || prevRatings.deliveryPartner?.comment || ""
            }
          },
          restaurantRating: newRestRating,
          deliveryPartnerRating: newDelivRating
        };
      });

      toast.success("Thanks for your feedback!")
      setShowRatingModal(false)
    } catch (error) {
      debugError("Error submitting order ratings:", error)
      toast.error(error?.response?.data?.message || "Failed to submit ratings")
    } finally {
      setSubmittingRating(false)
    }
  }

  const handleEtaUpdate = useCallback((newEta) => {
    if (typeof newEta === 'string') {
      const match = newEta.match(/(\d+)/);
      if (match) {
        setEstimatedTime(parseInt(match[1], 10));
        return;
      }
    }
    if (typeof newEta === 'number' && !isNaN(newEta)) {
      setEstimatedTime(newEta);
    }
  }, [])
  const lastRealtimeRefreshRef = useRef(0)
  const trackingOrderIdsRef = useRef(new Set())
  const terminalPollStopRef = useRef(false)
  const lookupIdsRef = useRef([])
  const isInitialPollRequestedRef = useRef(null)
  const lastPollExecutionRef = useRef(0) // New: Hard throttle for extreme cases
  const lastStatusToastRef = useRef({ key: '', at: 0 })

  const ORDER_STATUS_TOAST_ID = 'order-tracking-status-update'
  const ORDER_STATUS_TOAST_DEDUPE_MS = 4000

  // Delivery handover OTP received via socket event.
  // Kept separately so UI still renders even if the event arrives
  // before the order API poll populates `order` state.
  const [socketDropOtpCode, setSocketDropOtpCode] = useState(null)


  // OTP received via socket event (deliveryDropOtp)
  useEffect(() => {
    const handleDeliveryDropOtp = (event) => {
      const detail = event?.detail || {}
      const otp = detail?.otp != null ? String(detail.otp) : null
      const evtOrderId = detail?.orderId != null ? String(detail.orderId) : null
      const evtOrderMongoId =
        detail?.orderMongoId != null ? String(detail.orderMongoId) : null

      if (!otp) return

      // If the order is already loaded, match by either orderId or mongoId.
      // Otherwise, match against the current URL param.
      const currentIds = [String(orderId)]
      if (order?.orderId) currentIds.push(String(order.orderId))
      if (order?.mongoId) currentIds.push(String(order.mongoId))
      if (order?._id) currentIds.push(String(order._id))

      const matches =
        (evtOrderId && currentIds.includes(evtOrderId)) ||
        (evtOrderMongoId && currentIds.includes(evtOrderMongoId))

      if (!matches) return

      // Always store so UI can render even if `order` hasn't loaded yet.
      setSocketDropOtpCode(otp)

      setOrder((prev) => {
        if (!prev) return prev
        const prevDV = prev.deliveryVerification || {}
        const prevDropOtp = prevDV.dropOtp || {}
        
        // Only update if code actually changed to avoid render loops
        if (prevDropOtp.code === otp) return prev;
        
        return {
          ...prev,
          deliveryVerification: {
            ...prevDV,
            dropOtp: {
              ...prevDropOtp,
              required: true,
              verified: false,
              code: otp
            }
          }
        }
      })
    }

    window.addEventListener('deliveryDropOtp', handleDeliveryDropOtp)
    return () => window.removeEventListener('deliveryDropOtp', handleDeliveryDropOtp)
  }, [orderId, order])

  // --- Start: Sync arrival time and status ---
  const getDeliveryTargetTime = useCallback((orderData) => {
    if (!orderData) return null;

    // If preparationTime is set by the restaurant, use acceptedAt + preparationTime
    if (orderData.preparationTime && orderData.acceptedAt) {
      const acceptTime = new Date(orderData.acceptedAt);
      return new Date(acceptTime.getTime() + orderData.preparationTime * 60000);
    }

    // Use scheduled time if available, fallback to creation time
    const orderTime = new Date(
      orderData.scheduledAt || orderData.createdAt || orderData.orderDate || orderData.created_at || orderData.date || Date.now()
    );

    // For non-scheduled orders, we add the estimated delivery time to the creation time.
    // For scheduled orders, scheduledAt is already the target time.
    const isScheduled = !!orderData.scheduledAt;
    const estimatedMinutes = isScheduled 
      ? 0 
      : (orderData.estimatedDeliveryTime || orderData.estimatedTime || orderData.estimated_delivery_time || 35);

    return new Date(orderTime.getTime() + estimatedMinutes * 60000);
  }, []);

  // Single clock source for estimatedTime and orderStatus sync
  useEffect(() => {
    if (!order) return;

    const targetTime = getDeliveryTargetTime(order);

    const updateTimerAndStatus = () => {
      const actualStatus = mapOrderToTrackingUiStatus(order);
      let diffMs = 0;
      if (targetTime) {
        diffMs = targetTime.getTime() - Date.now();
      }

      if (diffMs <= 0) {
        setEstimatedTime(0);
        // Do NOT auto-set to 'ready' — that status must come from the restaurant
        setOrderStatus(actualStatus);
      } else {
        const mins = Math.ceil(diffMs / 60000);
        setEstimatedTime(mins);
        setOrderStatus(actualStatus);
      }
    };

    updateTimerAndStatus();
    const interval = setInterval(updateTimerAndStatus, 1000); // Check every second for instant response

    return () => clearInterval(interval);
  }, [order, getDeliveryTargetTime]);
  // --- End: Sync arrival time and status ---

  // --------------------------------------------------------------------------
  // DATA FETCHING & POLLING STABILITY (FIXED FOR HAMMERING)
  // --------------------------------------------------------------------------

  // Socket notifications include order ids — keep a set so events match this page.
  useEffect(() => {
    const s = trackingOrderIdsRef.current
    s.add(String(orderId))
    if (order?.orderId) s.add(String(order.orderId))
    if (order?.mongoId) s.add(String(order.mongoId))
    if (order?.id) s.add(String(order.id))
  }, [orderId, order?.orderId, order?.mongoId, order?.id])

  useEffect(() => {
    const ids = [
      resolvedLookupId,
      orderId,
      order?.orderId,
      order?.mongoId,
      order?._id,
      order?.id,
    ]
      .map(normalizeLookupId)
      .filter(Boolean)
    lookupIdsRef.current = Array.from(new Set(ids))
  }, [orderId, resolvedLookupId, order?.orderId, order?.mongoId, order?._id, order?.id])

  // Stability Nuke: Move function bodies into a ref-protected execute flow
  const stableOpsRef = useRef({
    resolveOrderFromList: async (rawLookupId) => {
      const needle = normalizeLookupId(rawLookupId)
      if (!needle) return null
      try {
        const listResponse = await orderAPI.getOrders({ page: 1, limit: 50 })
        let orders = []
        if (listResponse?.data?.success && listResponse?.data?.data?.orders) {
          orders = listResponse.data.data.orders || []
        } else if (listResponse?.data?.orders) {
          orders = listResponse.data.orders || []
        } else if (Array.isArray(listResponse?.data?.data?.data)) {
          orders = listResponse.data.data.data || []
        } else if (Array.isArray(listResponse?.data?.data)) {
          orders = listResponse.data.data || []
        }

        const matched = (orders || []).find((o) => {
          const candidates = [o?._id, o?.id, o?.orderId, o?.mongoId].map(normalizeLookupId)
          return candidates.includes(needle)
        })
        if (matched) return matched
      } catch (err) {
        debugWarn('resolveOrderFromList error:', err)
      }
      return null
    },
    fetchOrderDetailsWithFallback: async (options = {}) => {
      const lookupIds = lookupIdsRef.current
      if (lookupIds.length === 0) throw new Error("Order id required")
      let lastError = null
      for (const id of lookupIds) {
        try {
          // Double guard against hammer
          return await orderAPI.getOrderDetails(id, options)
        } catch (err) {
          lastError = err
          if (err?.response?.status === 400 || err?.response?.status === 404) continue
          throw err
        }
      }
      throw lastError || new Error("Failed to fetch order details")
    }
  });

  const resolveOrderFromList = useCallback((id) => stableOpsRef.current.resolveOrderFromList(id), [])
  const fetchOrderDetailsWithFallback = useCallback((opts) => stableOpsRef.current.fetchOrderDetailsWithFallback(opts), [])

  // Clear OTP when order is finalized.
  useEffect(() => {
    if (!order) return
    const status = mapOrderToTrackingUiStatus(order)
    if (status === 'delivered' || status === 'cancelled') {
      setSocketDropOtpCode(null)


      setOrder((prev) => {
        if (!prev?.deliveryVerification?.dropOtp?.code) return prev
        return {
          ...prev,
          deliveryVerification: {
            ...(prev.deliveryVerification || {}),
            dropOtp: {
              ...(prev.deliveryVerification?.dropOtp || {}),
              code: null
            }
          }
        }
      })
    }
  }, [orderStatus, order])

  const defaultAddress = getDefaultAddress()
  const fallbackCustomerCoords = useMemo(() => {
    const orderCoords = order?.address?.coordinates || order?.address?.location?.coordinates
    if (Array.isArray(orderCoords) && orderCoords.length >= 2) {
      const lng = Number(orderCoords[0])
      const lat = Number(orderCoords[1])
      if (Number.isFinite(lat) && Number.isFinite(lng)) {
        return { lat, lng }
      }
    }

    const orderLocObj = order?.address?.location || order?.address
    const orderObjLat = Number(orderLocObj?.lat ?? orderLocObj?.latitude)
    const orderObjLng = Number(orderLocObj?.lng ?? orderLocObj?.longitude)
    if (Number.isFinite(orderObjLat) && Number.isFinite(orderObjLng)) {
      return { lat: orderObjLat, lng: orderObjLng }
    }

    const defaultCoords = defaultAddress?.location?.coordinates
    if (Array.isArray(defaultCoords) && defaultCoords.length >= 2) {
      const lng = Number(defaultCoords[0])
      const lat = Number(defaultCoords[1])
      if (Number.isFinite(lat) && Number.isFinite(lng)) {
        return { lat, lng }
      }
    }

    const defaultLocObj = defaultAddress?.location || defaultAddress
    const defaultObjLat = Number(defaultLocObj?.lat ?? defaultLocObj?.latitude)
    const defaultObjLng = Number(defaultLocObj?.lng ?? defaultLocObj?.longitude)
    if (Number.isFinite(defaultObjLat) && Number.isFinite(defaultObjLng)) {
      return { lat: defaultObjLat, lng: defaultObjLng }
    }

    const liveLat = Number(userLiveLocation?.latitude)
    const liveLng = Number(userLiveLocation?.longitude)
    if (Number.isFinite(liveLat) && Number.isFinite(liveLng)) {
      return { lat: liveLat, lng: liveLng }
    }

    return null
  }, [
    order?.address?.coordinates,
    order?.address?.location?.coordinates,
    defaultAddress?.location?.coordinates,
    userLiveLocation?.latitude,
    userLiveLocation?.longitude
  ])

  const userLiveCoords = useMemo(() => {
    const lat = Number(userLiveLocation?.latitude)
    const lng = Number(userLiveLocation?.longitude)
    if (!Number.isFinite(lat) || !Number.isFinite(lng)) return null
    return { lat, lng }
  }, [userLiveLocation?.latitude, userLiveLocation?.longitude])

  const isAdminAccepted = useMemo(() => {
    const status = order?.status
    return [
      "preparing",
      "ready",
      "ready_for_pickup",
      "picked_up",
    ].includes(status)
  }, [order?.status])

  // Single source of truth is now handled by the unified sync clock useEffect above.

  const acceptedAtMs = useMemo(() => {
    const timestamp =
      order?.tracking?.preparing?.timestamp ||
      order?.updatedAt ||
      order?.createdAt

    const parsed = timestamp ? new Date(timestamp).getTime() : NaN
    return Number.isFinite(parsed) ? parsed : null
  }, [order?.tracking?.preparing?.timestamp, order?.updatedAt, order?.createdAt])

  const editWindowRemainingMs = useMemo(() => {
    if (!isAdminAccepted || !acceptedAtMs) return 0
    const remaining = 60000 - (timerNow - acceptedAtMs)
    return Math.max(0, remaining)
  }, [isAdminAccepted, acceptedAtMs, timerNow])

  const isEditWindowOpen = editWindowRemainingMs > 0

  const editWindowText = useMemo(() => {
    const totalSeconds = Math.ceil(editWindowRemainingMs / 1000)
    const minutes = Math.floor(totalSeconds / 60)
    const seconds = totalSeconds % 60
    return `${minutes}:${String(seconds).padStart(2, '0')}`
  }, [editWindowRemainingMs])

  const handleCallRestaurant = (e) => {
    // Prevent event bubbling if necessary
    if (e && e.stopPropagation) e.stopPropagation();

    const rawPhone =
      order?.restaurantPhone ||
      order?.restaurantId?.phone ||
      order?.restaurantId?.ownerPhone ||
      order?.restaurantId?.contact?.phone ||
      order?.restaurant?.phone ||
      order?.restaurant?.ownerPhone ||
      order?.restaurantId?.location?.phone ||
      '';

    const cleanPhone = String(rawPhone).replace(/[^\d+]/g, '');
    
    if (!cleanPhone || cleanPhone.length < 5) {
      toast.error('Restaurant phone number not available');
      return;
    }

    debugLog('?? Attempting to call restaurant:', cleanPhone);
    
    try {
      Linking.openURL(`tel:${cleanPhone}`);
    } catch (err) {
      debugError('Call failed:', err);
    }
  };

  const handleOpenDirections = async (e) => {
    if (e && e.stopPropagation) e.stopPropagation();

    let lat = null;
    let lng = null;

    // Helper to extract coords
    const extractCoords = (obj) => {
      if (!obj) return null;
      // If array [lng, lat]
      if (Array.isArray(obj) && obj.length >= 2) {
        return { lat: Number(obj[1]), lng: Number(obj[0]) };
      }
      // If array nested in coordinates
      if (obj.coordinates && Array.isArray(obj.coordinates) && obj.coordinates.length >= 2) {
        return { lat: Number(obj.coordinates[1]), lng: Number(obj.coordinates[0]) };
      }
      // If object with lat/lng or latitude/longitude
      const latVal = obj.lat || obj.latitude;
      const lngVal = obj.lng || obj.longitude;
      if (latVal != null && lngVal != null) {
        return { lat: Number(latVal), lng: Number(lngVal) };
      }
      return null;
    };

    // Try multiple sources on order
    let resolved = extractCoords(order?.restaurantLocation) || 
                   extractCoords(order?.restaurantId?.location) ||
                   extractCoords(order?.restaurant?.location);

    if (resolved) {
      lat = resolved.lat;
      lng = resolved.lng;
    }

    // Fallbacks on order object properties
    if (lat === null || lng === null) {
      const loc = order?.restaurantId?.location || order?.restaurant?.location;
      if (loc && Number.isFinite(Number(loc.latitude)) && Number.isFinite(Number(loc.longitude))) {
        lat = Number(loc.latitude);
        lng = Number(loc.longitude);
      } else if (loc && Number.isFinite(Number(loc.lat)) && Number.isFinite(Number(loc.lng))) {
        lat = Number(loc.lat);
        lng = Number(loc.lng);
      }
    }

    // Dynamic fetch from restaurant API if coords are still missing
    if (lat === null || lng === null) {
      const restId = order?.restaurantId?._id || order?.restaurantId?.id || (typeof order?.restaurantId === 'string' ? order.restaurantId : null);
      if (restId) {
        try {
          const restaurantResponse = await restaurantAPI.getRestaurantById(restId);
          if (restaurantResponse?.data?.success && restaurantResponse.data.data?.restaurant) {
            const restaurant = restaurantResponse.data.data.restaurant;
            const fetched = extractCoords(restaurant.location);
            if (fetched) {
              lat = fetched.lat;
              lng = fetched.lng;
            }
          }
        } catch (err) {
          debugError('Failed to fetch restaurant details in handleOpenDirections:', err);
        }
      }
    }

    let mapsUrl = '';
    const name = order?.restaurant || 'Restaurant';

    if (lat !== null && lng !== null && Number.isFinite(Number(lat)) && Number.isFinite(Number(lng))) {
      mapsUrl = `https://maps.google.com/?q=${lat},${lng}+(${encodeURIComponent(name)})`;
    } else {
      const address = order?.restaurantAddress || '';
      const query = address ? `${name} ${address}` : name;
      mapsUrl = `https://maps.google.com/?q=${encodeURIComponent(query)}`;
    }

    window.open(mapsUrl, '_blank');
  };

  const handleCallRider = (e) => {
    if (e && e.stopPropagation) e.stopPropagation();
    
    const rawPhone = order?.deliveryPartner?.phone || '';
    const cleanPhone = String(rawPhone).replace(/[^\d+]/g, '');

    if (!cleanPhone || cleanPhone.length < 5) {
      toast.error('Rider phone number not available');
      return;
    }

    debugLog('?? Attempting to call rider:', cleanPhone);
    
    try {
      Linking.openURL(`tel:${cleanPhone}`);
    } catch (err) {
      debugError('Call failed:', err);
    }
  };

  const customerDeliveryOtp = useMemo(() => {
    const codeFromOrder = order?.deliveryVerification?.dropOtp?.code
    const code = codeFromOrder ?? socketDropOtpCode
    return code ? String(code) : null
  }, [order?.deliveryVerification?.dropOtp?.code, socketDropOtpCode])

  useEffect(() => {
    if (!isEditWindowOpen) return
    const interval = setInterval(() => {
      setTimerNow(Date.now())
    }, 1000)
    return () => clearInterval(interval)
  }, [isEditWindowOpen])

  // Poll for order updates (especially when delivery partner accepts)

  const pollRef = useRef(null);

  // Main fetch & polling core logic. (Isolated from socket connection stat-changes)
  useEffect(() => {
    if (!orderId) return;

    let isSubscribed = true;
    let requestInProgress = false;

    // Clearing `loading` must survive every bail-out below. Under StrictMode the
    // effect mounts twice: the first instance unsubscribes (so its `finally`
    // skips setLoading) and the second trips the shared throttle refs and
    // returns early — leaving the screen on "Loading order details..." forever.
    const stopInitialLoading = () => {
      if (isSubscribed) setLoading(false);
    };

    const poll = async (isInitial = false) => {
      // Do NOT clear loading here: a request is already in flight and will
      // render the order when it lands. Clearing would flash "Order Not Found".
      if (!isSubscribed || requestInProgress) return;
      if (terminalPollStopRef.current && !isInitial) return;

      const now = Date.now();
      
      let hasOrderData = !!orderRef.current;

      // Check context immediately to avoid loaders if data exists locally
      if (isInitial) {
        const rawContext = getOrderById(orderId);
        if (rawContext) {
          setOrder(transformOrderForTracking(rawContext));
          setLoading(false);
          hasOrderData = true;
        }
      }

      // Global throttle across component remounts to prevent rapid API hammering
      const globalLastFetch = getGlobalLastFetchTime(orderId);
      if (isInitial && hasOrderData && now - globalLastFetch < 2000) {
        debugLog("?? Throttling initial poll - too soon since last fetch");
        stopInitialLoading();
        return;
      }
      if (isInitial) {
        setGlobalLastFetchTime(orderId, now);
      }

      // Throttle repeat initial polls, but never while we still have nothing to
      // show. `lastPollExecutionRef` is shared across mounts, so under
      // StrictMode this would throttle out the second (live) mount's only
      // fetch — leaving the screen with no data to render.
      if (isInitial && orderRef.current && now - lastPollExecutionRef.current < 1000) {
        stopInitialLoading();
        return;
      }
      if (isInitial) lastPollExecutionRef.current = now;

      requestInProgress = true;
      try {
        const response = await fetchOrderDetailsWithFallback({ force: isInitial });
        if (!isSubscribed) return;

        let finalOrderData = null;

        if (response.data?.success && response.data.data?.order) {
          finalOrderData = response.data.data.order;
        } else if (isInitial) {
          const matchedOrder = await resolveOrderFromList(orderId);
          if (matchedOrder) finalOrderData = matchedOrder;
        }

        if (finalOrderData) {
          setOrder(prev => {
            const transformedOrder = transformOrderForTracking(finalOrderData, prev);
            const ui = mapOrderToTrackingUiStatus(transformedOrder);
            terminalPollStopRef.current = ui === 'delivered' || ui === 'cancelled';
            return transformedOrder;
          });
          setError(null);
          setLoading(false);
          return;
        }

        if (isInitial && !order) {
          setError(response.data?.message || 'Order not found');
          terminalPollStopRef.current = true;
        }
      } catch (err) {
        if (isInitial && !order) {
          try {
            const matchedOrder = await resolveOrderFromList(orderId);
            if (matchedOrder) {
              if (!isSubscribed) return;
              setOrder(prev => transformOrderForTracking(matchedOrder, prev));
              setError(null);
              setLoading(false);
              return;
            }
          } catch {}
          if (!isSubscribed) return;
          setError(err.response?.data?.message || 'Failed to fetch order details');
          terminalPollStopRef.current = true;
        }
      } finally {
        requestInProgress = false;
        if (isInitial && isSubscribed) setLoading(false);
      }
    };

    pollRef.current = poll;
    terminalPollStopRef.current = false;

    if (isInitialPollRequestedRef.current !== orderId) {
      isInitialPollRequestedRef.current = orderId;
      poll(true);
    } else if (!orderRef.current) {
      // A previous mount already claimed the initial poll, then unmounted before
      // it could clear `loading` (its `finally` is gated on `isSubscribed`).
      // Under StrictMode that is every dev page load, which left this screen
      // stuck on "Loading order details..." forever. Only the interval poll runs
      // after that, and it passes isInitial=false, so it never clears loading
      // either. Re-run for this instance whenever we still have no order.
      poll(true);
    }

    return () => {
      isSubscribed = false;
    };
  }, [orderId, fetchOrderDetailsWithFallback, resolveOrderFromList]);

  // Interval Manager (dynamically adapts based on socket connection state independently)
  useEffect(() => {
    if (!orderId) return;

    const tick = () => {
      if (terminalPollStopRef.current) return;
      if (document.hidden) return;
      // Delegate to the latest instance of our polling function capturing current state
      if (pollRef.current) pollRef.current(false);
    };
    
    const pollInterval = (isSocketConnected || globalThis.orderSocketConnected) ? 60000 : 20000;
    const interval = setInterval(tick, pollInterval);

    return () => clearInterval(interval);
  }, [orderId, isSocketConnected]);

  useEffect(() => {
    if (!order) return
    const ui = mapOrderToTrackingUiStatus(order)
    terminalPollStopRef.current = ui === 'delivered' || ui === 'cancelled'
  }, [order])

  // Post-checkout splash only — real status comes from API / poll / socket.
  useEffect(() => {
    if (!confirmed) return
    const timer1 = setTimeout(() => setShowConfirmation(false), 3000)
    return () => clearTimeout(timer1)
  }, [confirmed])

  // Countdown timer is now handled by the unified sync clock useEffect above.

  // Listen for order status updates from socket (e.g., "Delivery partner on the way")
  useEffect(() => {
    const handleOrderStatusNotification = (event) => {
      const payload = event?.detail || {};
      const { message, status, estimatedDeliveryTime, orderId: evtOrderId, orderMongoId } = payload;

      const evtKeys = [evtOrderId, orderMongoId, payload?._id].filter(Boolean).map(String)
      const idMatches =
        evtKeys.length === 0 ||
        evtKeys.some((k) => String(k) === String(orderId)) ||
        evtKeys.some((k) => trackingOrderIdsRef.current.has(k))

      debugLog('?? Order status notification received:', { message, status, idMatches });

      if (idMatches) {
        const next = mapOrderToTrackingUiStatus({
          status,
          orderStatus: payload.orderStatus || status,
          deliveryState: payload.deliveryState,
        });
        const currentOrder = orderRef.current;
        const currentEstTime = estimatedTimeRef.current;
        if ((currentOrder?.orderType === 'takeaway' || currentOrder?.orderType === 'dining') && 
            currentEstTime <= 0 && 
            ['placed', 'preparing'].includes(next)) {
          setOrderStatus('ready');
        } else {
          setOrderStatus(next);
        }

        // Pull latest order state without refresh spam on bursty socket events.
        const now = Date.now();
        if (now - lastRealtimeRefreshRef.current > 1500 && !isRefreshingRef.current) {
          lastRealtimeRefreshRef.current = now;
          handleRefresh();
        }
      }

      // Show a single deduped notification toast
      if (message && idMatches) {
        const toastKey = `${String(evtOrderId || orderMongoId || orderId)}:${String(status || payload.orderStatus || '')}`
        const now = Date.now()
        const isDuplicateToast =
          toastKey &&
          toastKey === lastStatusToastRef.current.key &&
          now - lastStatusToastRef.current.at < ORDER_STATUS_TOAST_DEDUPE_MS

        if (isDuplicateToast) return

        lastStatusToastRef.current = { key: toastKey, at: now }
        toast.dismiss(ORDER_STATUS_TOAST_ID)
        toast.success(message, {
          id: ORDER_STATUS_TOAST_ID,
          duration: 5000,
          position: 'top-center',
          description: estimatedDeliveryTime
            ? `Estimated delivery in ${Math.round(estimatedDeliveryTime / 60)} minutes`
            : undefined
        });

        // Optional: Vibrate device if supported and user has interacted
        if (window.__userHasInteracted && navigator.vibrate) {
          try {
            navigator.vibrate([200, 100, 200]);
          } catch (_) {}
        }
      }
    };

    // Listen for custom event from DeliveryTrackingMap
    window.addEventListener('orderStatusNotification', handleOrderStatusNotification);

    return () => {
      window.removeEventListener('orderStatusNotification', handleOrderStatusNotification);
    };
  }, [orderId])

  const handleCancelOrder = () => {
    // Check if order can be cancelled (only Razorpay orders that aren't delivered/cancelled)
    if (!order) return;

    if (isAdminAccepted && !isEditWindowOpen) {
      toast.error('Cancellation window ended. You can no longer cancel this order.');
      return;
    }

    if (order.status === 'cancelled') {
      toast.error('Order is already cancelled');
      return;
    }

    if (order.status === 'delivered') {
      toast.error('Cannot cancel a delivered order');
      return;
    }

    // Allow cancellation for all payment methods (Razorpay, COD, Wallet)
    // Only restrict if order is already cancelled or delivered (checked above)

    const method = String(order?.payment?.method || order?.paymentMethod || "").toLowerCase()
    const status = String(order?.payment?.status || "").toLowerCase()
    const isRazorpayPaid =
      method === "razorpay" && ["paid", "authorized", "captured", "settled", "refunded"].includes(status)

    setRefundDestination(isRazorpayPaid ? "source" : "wallet")

    setShowCancelDialog(true);
  };

  const handleConfirmCancel = async () => {
    if (!cancellationReason.trim()) {
      toast.error('Please provide a reason for cancellation');
      return;
    }

    setIsCancelling(true);
    try {
      const cancelLookupId =
        lookupIdsRef.current[0] || normalizeLookupId(orderId)
      const method = String(order?.payment?.method || order?.paymentMethod || "").toLowerCase()
      const status = String(order?.payment?.status || "").toLowerCase()
      const isRazorpayPaid =
        method === "razorpay" && ["paid", "authorized", "captured", "settled", "refunded"].includes(status)

      const payload = {
        reason: cancellationReason.trim(),
        ...(isRazorpayPaid ? { refundDestination } : {}),
      }

      const response = await orderAPI.cancelOrder(cancelLookupId, payload);
      if (response.data?.success) {
        const paymentMethod = order?.payment?.method || order?.paymentMethod;
        const successMessage = response.data?.message ||
          (paymentMethod === 'cash' || paymentMethod === 'cod'
            ? 'Order cancelled successfully. No refund required as payment was not made.'
            : refundDestination === 'wallet'
              ? 'Order cancelled successfully. Refund has been added to your wallet.'
              : 'Order cancelled successfully. Refund will be processed to your original payment method.');
        toast.success(successMessage);
        setShowCancelDialog(false);
        setCancellationReason("");
        setRefundDestination("source");
        // Refresh order data
        const orderResponse = await fetchOrderDetailsWithFallback({ force: true });
        if (orderResponse.data?.success && orderResponse.data.data?.order) {
          const apiOrder = orderResponse.data.data.order;
          setOrder(transformOrderForTracking(apiOrder, order));
        }
      } else {
        toast.error(response.data?.message || 'Failed to cancel order');
      }
    } catch (error) {
      debugError('Error cancelling order:', error);
      toast.error(error.response?.data?.message || 'Failed to cancel order');
    } finally {
      setIsCancelling(false);
    }
  };

  const handleUpdateInstructions = async () => {
    try {
      setIsUpdatingInstructions(true);
      const response = await orderAPI.updateOrderInstructions(resolvedLookupId || orderId, deliveryInstructions);
      if (response.data?.success) {
        toast.success("Delivery instructions updated");
        setIsInstructionsModalOpen(false);
        const updatedOrder = response.data.data?.order;
        if (updatedOrder) {
          setOrder(prev => transformOrderForTracking(updatedOrder, prev));
        } else {
          setOrder(prev => ({ ...prev, note: deliveryInstructions }));
        }
      } else {
        toast.error(response.data?.message || "Failed to update instructions");
      }
    } catch (err) {
      toast.error(err.response?.data?.message || "Failed to update instructions");
    } finally {
      setIsUpdatingInstructions(false);
    }
  };

  const handleShare = async () => {
    try {
      if (navigator.share) {
        await navigator.share({
          title: `Track my order from ${order?.restaurant || companyName}`,
          text: `Hey! Track my order from ${order?.restaurant || companyName} with ID #${order?.orderId || order?.id}.`,
          url: `${API_ORIGIN}/food/user/orders/${orderId}`,
        });
      } else {
        await navigator.clipboard.writeText(`${API_ORIGIN}/food/user/orders/${orderId}`);
        toast.success("Tracking link copied to clipboard!");
      }
    } catch (error) {
      if (error.name !== 'AbortError') {
        debugError('Error sharing:', error);
        toast.error("Failed to share link");
      }
    }
  };

  const handleRefresh = async () => {
    if (isRefreshingRef.current) return
    isRefreshingRef.current = true
    setIsRefreshing(true)
    try {
      const response = await fetchOrderDetailsWithFallback({ force: true })
      if (response.data?.success && response.data.data?.order) {
        const apiOrder = response.data.data.order

        // Extract restaurant location coordinates with multiple fallbacks
        let restaurantCoords = null;
        let restaurantAddress = null;

        // Priority 1: restaurantId.location.coordinates (GeoJSON format: [lng, lat])
        if (apiOrder.restaurantId?.location?.coordinates &&
          Array.isArray(apiOrder.restaurantId.location.coordinates) &&
          apiOrder.restaurantId.location.coordinates.length >= 2) {
          restaurantCoords = apiOrder.restaurantId.location.coordinates;
        }
        // Priority 2: restaurantId.location with latitude/longitude properties
        else if (apiOrder.restaurantId?.location?.latitude && apiOrder.restaurantId?.location?.longitude) {
          restaurantCoords = [apiOrder.restaurantId.location.longitude, apiOrder.restaurantId.location.latitude];
        }
        // Priority 3: Check nested restaurant data
        else if (apiOrder.restaurant?.location?.coordinates) {
          restaurantCoords = apiOrder.restaurant.location.coordinates;
        }
        // Priority 4: Check if restaurantId is a string ID and fetch restaurant details
        else if (typeof apiOrder.restaurantId === 'string') {
          debugLog('?? restaurantId is a string ID, fetching restaurant details...', apiOrder.restaurantId);
          try {
            const restaurantResponse = await restaurantAPI.getRestaurantById(apiOrder.restaurantId);
            if (restaurantResponse?.data?.success && restaurantResponse.data.data?.restaurant) {
              const restaurant = restaurantResponse.data.data.restaurant;
              if (restaurant.location?.coordinates && Array.isArray(restaurant.location.coordinates) && restaurant.location.coordinates.length >= 2) {
                restaurantCoords = restaurant.location.coordinates;
                debugLog('? Fetched restaurant coordinates from API:', restaurantCoords);
              }
              restaurantAddress =
                restaurant?.location?.formattedAddress ||
                restaurant?.location?.address ||
                restaurant?.address ||
                null;
            }
          } catch (err) {
            debugError('? Error fetching restaurant details:', err);
          }
        }

        setOrder(prev => transformOrderForTracking(apiOrder, prev, restaurantCoords, restaurantAddress))
      }
    } catch (err) {
      debugError('Error refreshing order:', err)
    } finally {
      isRefreshingRef.current = false
      setIsRefreshing(false)
    }
  }

  // --------------------------------------------------------------------------
  // RENDER (Final JSX)
  // --------------------------------------------------------------------------

  // Loading state (moved after hooks)

  return {
    companyName,
    navigate,
    location,
    orderId,
    searchParams,
    confirmed,
    profile,
    getDefaultAddress,
    userLiveLocation,
    getOrderById,
    isSocketConnected,
    setIsSocketConnected,
    locationOrder,
    contextOrder,
    initialOrder,
    order,
    setOrder,
    loading,
    setLoading,
    error,
    setError,
    showConfirmation,
    setShowConfirmation,
    orderStatus,
    setOrderStatus,
    estimatedTime,
    setEstimatedTime,
    isRefreshing,
    setIsRefreshing,
    orderRef,
    estimatedTimeRef,
    isRefreshingRef,
    showCancelDialog,
    setShowCancelDialog,
    showOrderDetails,
    setShowOrderDetails,
    cancellationReason,
    setCancellationReason,
    refundDestination,
    setRefundDestination,
    isCancelling,
    setIsCancelling,
    isInstructionsModalOpen,
    setIsInstructionsModalOpen,
    deliveryInstructions,
    setDeliveryInstructions,
    isUpdatingInstructions,
    setIsUpdatingInstructions,
    resolvedLookupId,
    setResolvedLookupId,
    timerNow,
    setTimerNow,
    navigateToHomeAfterRating,
    showRatingModal,
    setShowRatingModal,
    selectedRestaurantRating,
    setSelectedRestaurantRating,
    selectedDeliveryRating,
    setSelectedDeliveryRating,
    restaurantFeedbackText,
    setRestaurantFeedbackText,
    deliveryFeedbackText,
    setDeliveryFeedbackText,
    submittingRating,
    setSubmittingRating,
    isLocalRated,
    setIsLocalRated,
    resRatingVal,
    delRatingVal,
    hasRestaurantRating,
    hasDeliveryPartner,
    hasDeliveryRating,
    isOrderRated,
    handleOpenRating,
    handleBackClick,
    handleSubmitRating,
    handleEtaUpdate,
    lastRealtimeRefreshRef,
    trackingOrderIdsRef,
    terminalPollStopRef,
    lookupIdsRef,
    isInitialPollRequestedRef,
    lastPollExecutionRef,
    lastStatusToastRef,
    ORDER_STATUS_TOAST_ID,
    ORDER_STATUS_TOAST_DEDUPE_MS,
    socketDropOtpCode,
    setSocketDropOtpCode,
    getDeliveryTargetTime,
    stableOpsRef,
    resolveOrderFromList,
    fetchOrderDetailsWithFallback,
    defaultAddress,
    fallbackCustomerCoords,
    userLiveCoords,
    isAdminAccepted,
    acceptedAtMs,
    editWindowRemainingMs,
    isEditWindowOpen,
    editWindowText,
    handleCallRestaurant,
    handleOpenDirections,
    handleCallRider,
    customerDeliveryOtp,
    pollRef,
    handleCancelOrder,
    handleConfirmCancel,
    handleUpdateInstructions,
    handleShare,
    handleRefresh,
    getRestaurantCoordsFromOrder,
    getRestaurantAddressFromOrder,
    getCustomerCoordsFromApiOrder,
    transformOrderForTracking,
    mapBackendOrderStatusToUi,
    mapOrderToTrackingUiStatus,
    isFoodOrderCancelledStatus,
    normalizeLookupId,
    getGlobalLastFetchTime,
    setGlobalLastFetchTime,
  }
}
