// Generated by tools/extract-hook.js from Frontend/src/modules/Food/pages/user/search/ProfessionalSearch.jsx (ProfessionalSearch), then edited by hand
// where the web code touched the DOM. The logic is the web page's own.
/* eslint-disable react-hooks/exhaustive-deps, no-unused-vars, no-empty */
import { useState, useMemo, useRef, useEffect, useCallback } from 'react'
import { useSearchParams, useNavigate } from '../../../lib/webRouter'
import { useLocation as useGeoLocation } from '../useLocation'
import { useZone } from '../useZone'
import { searchAPI } from '../../../api/food'
import { API_ORIGIN } from '../../../api/client'
import { normalizeImageUrl } from '../../utils/common'
import { useProfile } from '../../context/ProfileContext'
import { filterCategoriesForVegMode, filterRestaurantsForVegMode, isVegMenuItem, matchesVegRestaurantFilter } from '../../utils/vegMode'
import { localStore } from '../../../lib/storage'

const getMediaUrl = (url) => {
  if (!url || typeof url !== 'string') return null;
  if (url.startsWith('http')) return url;
  return normalizeImageUrl(url, API_ORIGIN);
};

function useDebounce(value, delay) {
  const [debouncedValue, setDebouncedValue] = useState(value)
  useEffect(() => {
    const handler = setTimeout(() => setDebouncedValue(value), delay)
    return () => clearTimeout(handler)
  }, [value, delay])
  return debouncedValue
}

const SEARCH_HISTORY_KEY = "professional_search_history_v1"

export function useProfessionalSearch() {
  const [searchParams, setSearchParams] = useSearchParams()
  const initialQuery = searchParams.get("q") || ""
  const navigate = useNavigate()
  const { location: userCoords } = useGeoLocation()
  const { zoneId } = useZone(userCoords)
  const { vegMode, vegModeOption } = useProfile()
  const searchMode = searchParams.get("mode") || "delivery"
  const isTakeawaySearch = searchMode === "takeaway"
  
  const [query, setQuery] = useState(initialQuery)
  const debouncedQuery = useDebounce(query, 500)
  
  const [results, setResults] = useState({ restaurants: [], dishes: [] })
  const [loading, setLoading] = useState(false)
  // Voice search (Web Speech API) has no native counterpart: the mic focuses the field so the keyboard's own voice typing is used.
  const isListening = false
  const startListening = () => {}
  const stopListening = () => {}
  const [categories, setCategories] = useState([])
  const [selectedCategoryId, setSelectedCategoryId] = useState(searchParams.get("cat") || null)
  const [history, setHistory] = useState([])
  const resultsRef = useRef(null)

  // Load search history
  useEffect(() => {
    const savedHistory = localStore.getItem(SEARCH_HISTORY_KEY)
    try { if (savedHistory) setHistory(JSON.parse(savedHistory)) } catch {}
    fetchCategories()
  }, [])

  const navType = 'PUSH'
  // The screen sets this to scroll its ScrollView to the results block.
  const scrollToResultsRef = useRef(null)
  const prevQueryRef = useRef(query);
  const prevCategoryRef = useRef(selectedCategoryId);
  const hasInitialScrolledRef = useRef(false);

  // Auto-scroll to results only when query ACTUALLY changes OR on fresh navigation (not BACK/FORWARD)
  useEffect(() => {
    const queryChanged = prevQueryRef.current !== query;
    const isFreshMount = !hasInitialScrolledRef.current;
    
    if (!loading && query && resultsRef.current) {
      if (queryChanged || (isFreshMount && navType !== "POP")) {
        prevQueryRef.current = query;
        hasInitialScrolledRef.current = true;
        
        const timer = setTimeout(() => {
          scrollToResultsRef.current?.();
        }, 50);
        return () => clearTimeout(timer);
      }
    }
  }, [loading, query, navType])

  // Auto-scroll to results when category changes
  useEffect(() => {
    if (selectedCategoryId) {
      const timer = setTimeout(() => {
        scrollToResultsRef.current?.();
      }, 80);
      return () => clearTimeout(timer);
    }
  }, [selectedCategoryId])

  const fetchCategories = async () => {
    try {
      const res = await searchAPI.getAdminCategories({ zoneId })
      if (res.data?.success) setCategories(res.data.data.categories || [])
    } catch (err) {
      console.error("Failed to fetch categories", err)
    }
  }

  const visibleCategories = useMemo(
    () => filterCategoriesForVegMode(categories, vegMode),
    [categories, vegMode],
  )

  // If a non-veg category was selected before veg mode turned on, clear it
  useEffect(() => {
    if (!vegMode || !selectedCategoryId) return
    const stillVisible = visibleCategories.some(
      (c) => String(c._id || c.id) === String(selectedCategoryId),
    )
    if (!stillVisible) setSelectedCategoryId(null)
  }, [vegMode, selectedCategoryId, visibleCategories])

  const addToHistory = (term) => {
    const newHistory = [term, ...history.filter(h => h !== term)].slice(0, 5)
    setHistory(newHistory)
    localStore.setItem(SEARCH_HISTORY_KEY, JSON.stringify(newHistory))
  }

  const performSearch = useCallback(async (searchTerm, catId) => {
    if (!searchTerm && !catId) {
      setResults({ restaurants: [], dishes: [] })
      return
    }

    if (!zoneId) {
      setResults({ restaurants: [], dishes: [] })
      return
    }
    
    setLoading(true)
    try {
      const res = await searchAPI.unifiedSearch({
        q: searchTerm,
        categoryId: catId,
        lat: userCoords?.latitude,
        lng: userCoords?.longitude,
        limit: 50,
        zoneId,
        orderType: searchMode,
        ...(vegMode ? { isVeg: "true" } : {}),
      })

      const all = res.data?.success ? (res.data.data?.restaurants || []) : []
      const restaurantsRaw = all.filter(r => r.matchType === 'restaurant' || !r.matchType)
      const dishesRaw = all.filter(r => r.matchType === 'food')

      const restaurants = filterRestaurantsForVegMode(restaurantsRaw, {
        vegMode,
        vegModeOption,
      })
      const dishes = dishesRaw
        .filter((r) => !vegMode || isVegMenuItem({
          foodType: r.matchedDishFoodType || r.foodType,
          isVeg: r.isVeg,
        }))
        .filter((r) => matchesVegRestaurantFilter(r, { vegMode, vegModeOption }))

      setResults({ restaurants, dishes })
    } catch (err) {
      console.error("Search failed", err)
      setResults({ restaurants: [], dishes: [] })
    } finally {
      setLoading(false)
    }
  }, [userCoords, zoneId, searchMode, vegMode, vegModeOption])

  useEffect(() => {
    performSearch(debouncedQuery, selectedCategoryId)
    if (debouncedQuery) {
        setSearchParams({ q: debouncedQuery, ...(selectedCategoryId ? { cat: selectedCategoryId } : {}) }, { replace: true })
    }
  }, [debouncedQuery, selectedCategoryId, performSearch])

  // Speech Recognition Implementation
  const handleVoiceSearch = () => {
    if (isListening) {
      stopListening()
    } else {
      startListening()
    }
  }

  const handleClear = () => {
    setQuery("")
    setSelectedCategoryId(null)
    setSearchParams({}, { replace: true })
    setResults({ restaurants: [], dishes: [] })
  }

  const handleCategoryClick = (id) => {
    if (selectedCategoryId === id) {
      scrollToResultsRef.current?.();
    } else {
      setSelectedCategoryId(id)
      setSearchParams({ ...Object.fromEntries(searchParams), cat: id }, { replace: true })
    }
  }

  const selectedCategoryObj = categories.find(c => c._id === selectedCategoryId)
  const selectedCategorySlug = selectedCategoryObj?.slug || selectedCategoryObj?._id || selectedCategoryObj?.name?.toLowerCase().replace(/\s+/g, '-')

  return {
    searchParams,
    setSearchParams,
    initialQuery,
    navigate,
    userCoords,
    zoneId,
    vegMode,
    vegModeOption,
    searchMode,
    isTakeawaySearch,
    query,
    setQuery,
    debouncedQuery,
    results,
    setResults,
    loading,
    setLoading,
    isListening,
    startListening,
    stopListening,
    categories,
    setCategories,
    selectedCategoryId,
    setSelectedCategoryId,
    history,
    setHistory,
    resultsRef,
    navType,
    prevQueryRef,
    prevCategoryRef,
    hasInitialScrolledRef,
    fetchCategories,
    visibleCategories,
    addToHistory,
    performSearch,
    handleVoiceSearch,
    handleClear,
    handleCategoryClick,
    selectedCategoryObj,
    selectedCategorySlug,
    scrollToResultsRef,
    getMediaUrl,
    useDebounce,
    SEARCH_HISTORY_KEY,
  }
}
