// Generated by tools/extract-hook.js from Frontend/src/modules/Food/pages/user/Under250.jsx (Under250), then edited by hand
// where the web code touched the DOM. The logic is the web page's own.
/* eslint-disable react-hooks/exhaustive-deps, no-unused-vars, no-empty */
import { Linking } from 'react-native'
import { Link, useNavigate } from '../../../lib/webRouter'
import { useState, useMemo, useCallback, useEffect, useRef } from 'react'
import { Check } from 'lucide-react-native'
import { toast } from '../../../lib/notify'
import { useLocation } from '../useLocation'
import { useZone } from '../useZone'
import { useCart } from '../../context/CartContext'
import { useProfile } from '../../context/ProfileContext'
import { getRestaurantAvailabilityStatus } from '../../utils/restaurantAvailability'
import api from '../../../api/food'
import { restaurantAPI, adminAPI } from '../../../api/food'
import { isModuleAuthenticated } from '../../utils/auth'
import { calculateDistance, formatDistance } from '../../utils/common'
import { getDefaultFoodVariant, buildCartLineId } from '../../utils/foodVariants'
import { isVegMenuItem, isNonVegCategoryScope } from '../../utils/vegMode'
import { buildFoodCacheKey, getCachedUnder250PriceLimit, getFoodPageCache, getLandingSettingsPublic, setFoodPageCache } from '../../utils/foodPageCache'
import { localStore } from '../../../lib/storage'
import { events } from '../../../lib/events'
import { window, document, navigator, Image } from '../../../lib/webShim'

const getLineItemIdForDish = (item, variant = null) =>
  buildCartLineId(item?.id || item?._id || "", variant?.id || variant?._id || "")

const debugLog = (...args) => {}

const debugWarn = (...args) => {}

const debugError = (...args) => {}

const RUPEE_SYMBOL = "\u20B9"

const UNDER_250_FILTERS_STORAGE_KEY = "food-under-250-filters"

const UNDER250_LIST_MAX_VISIBLE = 12

const UNDER250_ITEMS_PER_RESTAURANT = 10

const UNDER250_PAGE_SIZE = 6

const UNDER250_CACHE_TTL_MS = 15 * 60 * 1000

const isUnder250CacheFresh = (cached) =>
  Boolean(
    cached?.restaurants?.length > 0 &&
      cached?.ts &&
      Date.now() - Number(cached.ts) < UNDER250_CACHE_TTL_MS,
  )

const mapUnder250Restaurants = (restaurantsRaw, location) => {
  const userLat = Number(location?.latitude)
  const userLng = Number(location?.longitude)

  return (Array.isArray(restaurantsRaw) ? restaurantsRaw : []).map((restaurant) => {
    const restaurantId = restaurant?.restaurantId || restaurant?.id || restaurant?._id

    const restaurantLocation = restaurant?.location
    const restaurantLat = Number(
      restaurantLocation?.latitude ??
        (Array.isArray(restaurantLocation?.coordinates)
          ? restaurantLocation.coordinates[1]
          : null),
    )
    const restaurantLng = Number(
      restaurantLocation?.longitude ??
        (Array.isArray(restaurantLocation?.coordinates)
          ? restaurantLocation.coordinates[0]
          : null),
    )
    const distanceInKm =
      Number.isFinite(userLat) &&
      Number.isFinite(userLng) &&
      Number.isFinite(restaurantLat) &&
      Number.isFinite(restaurantLng)
        ? calculateDistance(userLat, userLng, restaurantLat, restaurantLng)
        : null

    const fallbackDistance =
      typeof restaurant?.distance === "number"
        ? formatDistance(restaurant.distance)
        : restaurant?.distance || ""

    const mappedItems = (restaurant.menuItems || [])
      .slice(0, UNDER250_ITEMS_PER_RESTAURANT)
      .map((item) => ({
        ...item,
        id: String(item.id || item._id),
        price: Number(item.price || 0),
        foodType: item.foodType || (item.isVeg ? "Veg" : "Non-Veg"),
        isVeg: isVegMenuItem(item),
        image: item?.image || "",
      }))
    const hasNonVegInPayload = mappedItems.some((item) => !item.isVeg)
    const hasNonVegMenu =
      restaurant?.hasNonVegMenu === true || hasNonVegInPayload
        ? true
        : restaurant?.hasNonVegMenu === false
          ? false
          : undefined

    return {
      ...restaurant,
      id: String(restaurantId),
      restaurantId: String(restaurantId),
      name: restaurant?.restaurantName || restaurant?.name || "Restaurant",
      rating: Number(restaurant?.rating || 0),
      totalRatings: Number(restaurant?.totalRatings || restaurant?.ratingCount || 0),
      deliveryTime:
        restaurant?.estimatedDeliveryTime ||
        (restaurant?.estimatedDeliveryTimeMinutes
          ? `${restaurant.estimatedDeliveryTimeMinutes} mins`
          : "30 mins"),
      distance: distanceInKm !== null ? formatDistance(distanceInKm) : fallbackDistance,
      distanceInKm,
      hasNonVegMenu,
      isPureVeg:
        hasNonVegMenu === true
          ? false
          : restaurant?.isPureVeg === true ||
            (hasNonVegMenu === false &&
              (restaurant?.pureVegRestaurant === true ||
                mappedItems.some((item) => item.isVeg))),
      menuItems: mappedItems,
    }
  })
}

const readUnder250Filters = () => {
  if (false) {
    return {
      selectedSort: null,
      activeCategory: null,
      under30MinsFilter: false,
    }
  }

  try {
    const raw = localStore.getItem(UNDER_250_FILTERS_STORAGE_KEY)
    if (!raw) {
      return {
        selectedSort: null,
        activeCategory: null,
        under30MinsFilter: false,
      }
    }

    const parsed = JSON.parse(raw)
    return {
      selectedSort: typeof parsed?.selectedSort === "string" ? parsed.selectedSort : null,
      activeCategory: typeof parsed?.activeCategory === "string" ? parsed.activeCategory : null,
      under30MinsFilter: parsed?.under30MinsFilter === true,
    }
  } catch {
    return {
      selectedSort: null,
      activeCategory: null,
      under30MinsFilter: false,
    }
  }
}

export function useUnder250Page({ isTabActive = true } = {}) {
  const initialFiltersRef = useRef(readUnder250Filters())
  const { location } = useLocation()
  const { zoneId, zoneStatus, isInService, isOutOfService } = useZone(location)
  const { userProfile, vegMode, vegModeOption } = useProfile()

  const navigate = useNavigate()
  const { addToCart, updateQuantity, removeFromCart, getCartItem, cart } = useCart()
  const [activeCategory, setActiveCategory] = useState(initialFiltersRef.current.activeCategory)
  const [showSortPopup, setShowSortPopup] = useState(false)
  const [selectedSort, setSelectedSort] = useState(initialFiltersRef.current.selectedSort)
  const [draftSelectedSort, setDraftSelectedSort] = useState(initialFiltersRef.current.selectedSort)
  const [under30MinsFilter, setUnder30MinsFilter] = useState(initialFiltersRef.current.under30MinsFilter)
  const [showItemDetail, setShowItemDetail] = useState(false)
  const [selectedItem, setSelectedItem] = useState(null)
  const [itemDetailQuantity, setItemDetailQuantity] = useState(1)
  const [showShareOptions, setShowShareOptions] = useState(false)
  const [quantities, setQuantities] = useState({})
  const [bookmarkedItems, setBookmarkedItems] = useState(new Set())
  const [viewCartButtonBottom, setViewCartButtonBottom] = useState("bottom-[92px]")
  const lastScrollY = useRef(0)
  const scrollLockYRef = useRef(0)
  const itemDetailContentRef = useRef(null)
  const itemDetailGestureRef = useRef({
    startY: 0,
    dragging: false,
  })
  const [categories, setCategories] = useState([])
  const [loadingCategories, setLoadingCategories] = useState(true)
  const [bannerImages, setBannerImages] = useState([])
  const [loadingBanner, setLoadingBanner] = useState(true)
  const [currentBannerIndex, setCurrentBannerIndex] = useState(0)
  const [isTransitionEnabled, setIsTransitionEnabled] = useState(true)
  const [under250PriceLimit, setUnder250PriceLimit] = useState(() =>
    getCachedUnder250PriceLimit(250),
  )
  const cacheKey = buildFoodCacheKey("under250", {
    zoneId: zoneId || "none",
    limit: under250PriceLimit,
  })
  const cachedListRef = useRef(getFoodPageCache(cacheKey))
  const [under250Restaurants, setUnder250Restaurants] = useState(
    () => cachedListRef.current?.restaurants || [],
  )
  const [loadingRestaurants, setLoadingRestaurants] = useState(
    () => !(cachedListRef.current?.restaurants?.length > 0),
  )
  const [visibleRestaurantCount, setVisibleRestaurantCount] = useState(UNDER250_LIST_MAX_VISIBLE)
  const [hasScrolledPastBanner, setHasScrolledPastBanner] = useState(false)
  const bannerShellRef = useRef(null)
  const stickyHeaderRef = useRef(null)
  const autoSlideIntervalRef = useRef(null)
  const touchStartXRef = useRef(0)
  const touchStartYRef = useRef(0)
  const touchEndXRef = useRef(0)
  const touchEndYRef = useRef(0)
  const isBannerSwipingRef = useRef(false)
  const fetchInflightRef = useRef(null)

  const sortOptions = [
    { id: null, label: 'Relevance' },
    { id: 'rating-high', label: 'Rating: High to Low' },
    { id: 'delivery-time-low', label: 'Estimated Time: Low to High' },
    { id: 'distance-low', label: 'Distance: Low to High' },
  ]

  const handleClearAll = () => {
    setSelectedSort(null)
    setDraftSelectedSort(null)
    setUnder30MinsFilter(false)
    setActiveCategory(null)
    if (true) {
      localStore.removeItem(UNDER_250_FILTERS_STORAGE_KEY)
    }
  }

  const handleApply = () => {
    setSelectedSort(draftSelectedSort)
    setShowSortPopup(false)
  }

  // Helper function to parse delivery time (e.g., "12-15 mins" -> 12 or average)
  const parseDeliveryTime = (deliveryTime) => {
    if (typeof deliveryTime === "number" && Number.isFinite(deliveryTime)) return deliveryTime
    if (!deliveryTime) return 999 // Default high value for sorting
    const value = String(deliveryTime)
    const rangeMatch = value.match(/(\d+)\s*-\s*(\d+)/)
    if (rangeMatch) {
      return (parseInt(rangeMatch[1]) + parseInt(rangeMatch[2])) / 2 // Average
    }
    const match = value.match(/(\d+)/)
    if (match) {
      return parseInt(match[1])
    }
    return 999
  }

  // Helper function to parse distance (e.g., "0.4 km" -> 0.4)
  const parseDistance = (distance) => {
    if (typeof distance === "number" && Number.isFinite(distance)) return distance
    if (!distance) return 999 // Default high value for sorting
    const value = String(distance)
    const match = value.match(/(\d+\.?\d*)/)
    if (match) {
      const numericValue = parseFloat(match[1])
      return value.toLowerCase().includes("m") && !value.toLowerCase().includes("km")
        ? numericValue / 1000
        : numericValue
    }
    return 999
  }

  // Sort and filter restaurants based on selected sort, filters, and veg mode
  const sortedAndFilteredRestaurants = useMemo(() => {
    let filtered = under250Restaurants.map((r) => ({
      ...r,
      menuItems: [...(r.menuItems || [])],
    }))

    // Veg mode: pure-veg restaurants only, or all restaurants with veg dishes only
    if (vegMode) {
      if (vegModeOption === "pure-veg") {
        filtered = filtered.filter((restaurant) => {
          // Full-menu signal from API (any price) — don't trust under-250 items alone
          if (restaurant?.hasNonVegMenu === true) return false
          if (restaurant?.isPureVeg === true) return true
          if (restaurant?.hasNonVegMenu === false) {
            // Menu scanned: no non-veg anywhere; allow even if admin flag is wrong/missing
            return true
          }
          const items = restaurant.menuItems || []
          const hasNonVegDish = items.some((item) => !isVegMenuItem(item))
          return restaurant?.pureVegRestaurant === !hasNonVegDish
        })
      }
      filtered = filtered
        .map((restaurant) => {
          const vegItems = (restaurant.menuItems || []).filter(isVegMenuItem)
          if (vegItems.length === 0) return null
          return { ...restaurant, menuItems: vegItems }
        })
        .filter(Boolean)
    }

    // Apply category filter
    if (activeCategory) {
      const selectedCat = categories.find((cat) => cat.id === activeCategory)
      if (selectedCat) {
        const catNameLower = String(selectedCat.name || "").toLowerCase()
        filtered = filtered
          .map((restaurant) => {
            const matches = restaurant.menuItems.filter((item) => {
              const itemCat = String(item.categoryName || item.category || item.sectionName || item.subsectionName || "").toLowerCase()
              const itemName = String(item.name || "").toLowerCase()
              const itemDesc = String(item.description || "").toLowerCase()
              return (
                (itemCat && (itemCat.includes(catNameLower) || catNameLower.includes(itemCat))) ||
                (itemName && (itemName.includes(catNameLower) || catNameLower.includes(itemName))) ||
                (itemDesc && itemDesc.includes(catNameLower))
              )
            })
            if (matches.length > 0) {
              return { ...restaurant, menuItems: matches }
            }
            return null
          })
          .filter(Boolean)
      }
    }

    // Apply "Under 30 mins" filter
    if (under30MinsFilter) {
      filtered = filtered.filter((restaurant) => {
        const deliveryTime = parseDeliveryTime(restaurant.deliveryTime)
        return deliveryTime <= 30
      })
    }

    // Apply sorting
    if (selectedSort === "rating-high") {
      filtered.sort((a, b) => {
        const ratingA = a.rating || 0
        const ratingB = b.rating || 0
        if (ratingB !== ratingA) {
          return ratingB - ratingA
        }
        return (b.menuItems?.length || 0) - (a.menuItems?.length || 0)
      })
    } else if (selectedSort === "delivery-time-low") {
      filtered.sort((a, b) => {
        const timeA = parseDeliveryTime(a.deliveryTime)
        const timeB = parseDeliveryTime(b.deliveryTime)
        if (timeA !== timeB) {
          return timeA - timeB
        }
        if ((b.rating || 0) !== (a.rating || 0)) {
          return (b.rating || 0) - (a.rating || 0)
        }
        return (a.originalIndex || 0) - (b.originalIndex || 0)
      })
    } else if (selectedSort === "distance-low") {
      filtered.sort((a, b) => {
        const distA = Number.isFinite(a.distanceInKm)
          ? a.distanceInKm
          : parseDistance(a.distance)
        const distB = Number.isFinite(b.distanceInKm)
          ? b.distanceInKm
          : parseDistance(b.distance)
        if (distA !== distB) {
          return distA - distB
        }
        if ((b.rating || 0) !== (a.rating || 0)) {
          return (b.rating || 0) - (a.rating || 0)
        }
        return (a.originalIndex || 0) - (b.originalIndex || 0)
      })
    }

    const sortedResult = filtered
      .map((restaurant, index) => ({ restaurant, index }))
      .sort((a, b) => {
        const aAvail = getRestaurantAvailabilityStatus(a.restaurant)
        const bAvail = getRestaurantAvailabilityStatus(b.restaurant)
        
        const aOpen = aAvail?.isOpen ? 1 : 0
        const bOpen = bAvail?.isOpen ? 1 : 0
        
        if (aOpen !== bOpen) {
          return bOpen - aOpen
        }
        
        return a.index - b.index
      })
      .map(item => item.restaurant)

    return sortedResult
  }, [
    under250Restaurants,
    selectedSort,
    under30MinsFilter,
    activeCategory,
    categories,
    vegMode,
    vegModeOption,
  ])

  const displayCategories = useMemo(() => {
    let baseCats = categories
    if (vegMode) {
      baseCats = baseCats.filter((cat) => !isNonVegCategoryScope(cat))
    }
    if (!under250Restaurants || under250Restaurants.length === 0) {
      return baseCats
    }

    const availableItems = under250Restaurants.flatMap((r) => r.menuItems || [])
    if (availableItems.length === 0) return baseCats

    return baseCats.filter((cat) => {
      const catNameLower = String(cat.name || "").toLowerCase().trim()
      const catWords = catNameLower.split(/\s+/).filter(w => w.length > 2)

      return availableItems.some((item) => {
        const itemCat = String(item.categoryName || item.category || item.sectionName || item.subsectionName || item.categoryId || "").toLowerCase().trim()
        const itemName = String(item.name || "").toLowerCase().trim()
        const itemDesc = String(item.description || "").toLowerCase().trim()

        if (itemCat && (itemCat.includes(catNameLower) || catNameLower.includes(itemCat))) return true
        if (itemName && (itemName.includes(catNameLower) || catNameLower.includes(itemName))) return true
        if (itemDesc && itemDesc.includes(catNameLower)) return true

        if (catWords.length > 0) {
          return catWords.some(word => itemCat.includes(word) || itemName.includes(word) || itemDesc.includes(word))
        }
        return false
      })
    })
  }, [categories, vegMode, under250Restaurants])

  // If active category was non-veg and veg mode turns on, clear it
  useEffect(() => {
    if (!vegMode || !activeCategory) return
    const selected = categories.find((cat) => cat.id === activeCategory)
    if (selected && isNonVegCategoryScope(selected)) {
      setActiveCategory(null)
    }
  }, [vegMode, activeCategory, categories])

  // Fetch under-50 banner from public API
  useEffect(() => {
    let cancelled = false
    setLoadingBanner(true)
    const reqConfig = zoneId ? { params: { zoneId } } : {}
    api.get('/food/hero-banners/under-250/public', reqConfig)
      .then((res) => {
        if (cancelled) return
        const data = res?.data?.data
        const list = Array.isArray(data?.banners) ? data.banners : (Array.isArray(data) ? data : [])
        const images = list
          .map((banner) => (typeof banner?.imageUrl === "string" ? banner.imageUrl.trim() : ""))
          .filter(Boolean)
        setBannerImages(images)
      })
      .catch(() => {
        if (!cancelled) setBannerImages([])
      })
      .finally(() => {
        if (!cancelled) setLoadingBanner(false)
      })
    return () => { cancelled = true }
  }, [zoneId])

  // Fetch landing settings to get dynamic price limit (shared cache)
  useEffect(() => {
    let cancelled = false
    getLandingSettingsPublic(() =>
      api.get("/food/landing/settings/public", zoneId ? { params: { zoneId } } : {}),
    )
      .then((settings) => {
        if (cancelled) return
        if (settings && typeof settings.under250PriceLimit === "number") {
          setUnder250PriceLimit(settings.under250PriceLimit)
        }
      })
      .catch(() => {
        if (!cancelled) setUnder250PriceLimit(250)
      })
    return () => {
      cancelled = true
    }
  }, [zoneId])

  useEffect(() => {
    setCurrentBannerIndex((prev) => {
      if (bannerImages.length === 0) return 0
      return Math.min(prev, bannerImages.length - 1)
    })
  }, [bannerImages.length])

  useEffect(() => {

    bannerImages.forEach((src) => {
      if (!src) return
      const img = new Image()
      img.src = src
    })
  }, [bannerImages])

  const startBannerAutoSlide = useCallback(() => {
    if (autoSlideIntervalRef.current) {
      clearInterval(autoSlideIntervalRef.current)
    }

    if (bannerImages.length <= 1) return

    autoSlideIntervalRef.current = setInterval(() => {
      if (!isBannerSwipingRef.current) {
        setIsTransitionEnabled(true)
        setCurrentBannerIndex((prev) => {
          if (prev >= bannerImages.length) return prev
          return prev + 1
        })
      }
    }, 3500)
  }, [bannerImages.length])

  // Handle snap-back when reaching the cloned slide at the end
  useEffect(() => {
    if (currentBannerIndex === bannerImages.length && bannerImages.length > 1) {
      const timer = setTimeout(() => {
        setIsTransitionEnabled(false)
        setCurrentBannerIndex(0)
      }, 500) // match transition duration
      return () => clearTimeout(timer)
    }
  }, [currentBannerIndex, bannerImages.length])

  // Re-enable transition after snap-back
  useEffect(() => {
    if (!isTransitionEnabled && currentBannerIndex === 0) {
      const timer = setTimeout(() => {
        setIsTransitionEnabled(true)
      }, 50)
      return () => clearTimeout(timer)
    }
  }, [isTransitionEnabled, currentBannerIndex])

  const resetBannerAutoSlide = useCallback(() => {
    startBannerAutoSlide()
  }, [startBannerAutoSlide])

  useEffect(() => {
    startBannerAutoSlide()

    return () => {
      if (autoSlideIntervalRef.current) {
        clearInterval(autoSlideIntervalRef.current)
      }
    }
  }, [startBannerAutoSlide])

  const handleBannerTouchStart = useCallback((event) => {
    if (bannerImages.length <= 1) return
    touchStartXRef.current = event.nativeEvent.touches[0].pageX
    touchStartYRef.current = event.nativeEvent.touches[0].pageY
    touchEndXRef.current = event.nativeEvent.touches[0].pageX
    touchEndYRef.current = event.nativeEvent.touches[0].pageY
    isBannerSwipingRef.current = true
  }, [bannerImages.length])

  const handleBannerTouchMove = useCallback((event) => {
    if (!isBannerSwipingRef.current) return
    touchEndXRef.current = event.nativeEvent.touches[0].pageX
    touchEndYRef.current = event.nativeEvent.touches[0].pageY
  }, [])

  const handleBannerTouchEnd = useCallback(() => {
    if (!isBannerSwipingRef.current || bannerImages.length <= 1) {
      isBannerSwipingRef.current = false
      return
    }

    const deltaX = touchEndXRef.current - touchStartXRef.current
    const deltaY = Math.abs(touchEndYRef.current - touchStartYRef.current)
    const minSwipeDistance = 40

    if (Math.abs(deltaX) > minSwipeDistance && Math.abs(deltaX) > deltaY) {
      if (deltaX > 0) {
        if (currentBannerIndex === 0) {
          setIsTransitionEnabled(false)
          setCurrentBannerIndex(bannerImages.length)
          setTimeout(() => {
            setIsTransitionEnabled(true)
            setCurrentBannerIndex(bannerImages.length - 1)
          }, 50)
        } else {
          setIsTransitionEnabled(true)
          setCurrentBannerIndex((prev) => prev - 1)
        }
      } else {
        setIsTransitionEnabled(true)
        setCurrentBannerIndex((prev) => {
          if (prev >= bannerImages.length) return prev
          return prev + 1
        })
      }
      resetBannerAutoSlide()
    }

    isBannerSwipingRef.current = false
  }, [bannerImages.length, currentBannerIndex, resetBannerAutoSlide])

  // Recompute distances when GPS moves — do NOT refetch the heavy list
  useEffect(() => {
    const lat = Number(location?.latitude)
    const lng = Number(location?.longitude)
    if (!Number.isFinite(lat) || !Number.isFinite(lng)) return

    setUnder250Restaurants((prev) => {
      if (!prev.length) return prev
      let changed = false
      const next = prev.map((restaurant) => {
        const restaurantLocation = restaurant?.location
        const restaurantLat = Number(
          restaurantLocation?.latitude ??
            (Array.isArray(restaurantLocation?.coordinates)
              ? restaurantLocation.coordinates[1]
              : null),
        )
        const restaurantLng = Number(
          restaurantLocation?.longitude ??
            (Array.isArray(restaurantLocation?.coordinates)
              ? restaurantLocation.coordinates[0]
              : null),
        )
        if (!Number.isFinite(restaurantLat) || !Number.isFinite(restaurantLng)) {
          return restaurant
        }
        const distanceInKm = calculateDistance(lat, lng, restaurantLat, restaurantLng)
        const distance = formatDistance(distanceInKm)
        if (restaurant.distanceInKm === distanceInKm && restaurant.distance === distance) {
          return restaurant
        }
        changed = true
        return { ...restaurant, distanceInKm, distance }
      })
      return changed ? next : prev
    })
  }, [location?.latitude, location?.longitude])

  // Progressive fetch: first 6 restaurants paint fast, rest append in background.
  // Fresh cache → show instantly, no full refresh on tab return.
  useEffect(() => {
    if (!isTabActive) return undefined
    if (!zoneId) {
      setLoadingRestaurants(false)
      return undefined
    }

    let cancelled = false
    const key = buildFoodCacheKey("under250", {
      zoneId,
      limit: under250PriceLimit,
    })
    const cached = getFoodPageCache(key)

    if (isUnder250CacheFresh(cached)) {
      setUnder250Restaurants(mapUnder250Restaurants(cached.restaurants, location))
      setVisibleRestaurantCount(
        Math.max(UNDER250_LIST_MAX_VISIBLE, cached.restaurants.length),
      )
      setLoadingRestaurants(false)
      return undefined
    }

    if (cached?.restaurants?.length) {
      setUnder250Restaurants(mapUnder250Restaurants(cached.restaurants, location))
      setLoadingRestaurants(false)
    } else if (under250Restaurants.length === 0) {
      setLoadingRestaurants(true)
    }

    const mergeUnique = (prev, incoming) => {
      const seen = new Set(prev.map((r) => String(r.id)))
      const next = [...prev]
      incoming.forEach((r) => {
        const id = String(r.id)
        if (seen.has(id)) return
        seen.add(id)
        next.push(r)
      })
      return next
    }

    const loadProgressive = async () => {
      try {
        if (fetchInflightRef.current === key) return
        fetchInflightRef.current = key

        let offset = 0
        let scanSkip = 0
        let hasMore = true
        let accumulatedRaw = cached?.restaurants?.length ? [...cached.restaurants] : []
        let page = 0

        while (hasMore && !cancelled && page < 25) {
          const response = await restaurantAPI.getRestaurantsUnder250({
            zoneId,
            priceLimit: under250PriceLimit,
            limit: UNDER250_PAGE_SIZE,
            offset,
            scanSkip: page === 0 ? 0 : scanSkip,
          })
          if (cancelled) return

          const data = response?.data?.data
          const batchRaw = Array.isArray(data?.restaurants) ? data.restaurants : []
          hasMore = data?.hasMore === batchRaw.length > 0
          scanSkip = Number(data?.scanSkip) || scanSkip
          offset = Number(data?.nextOffset) || offset + batchRaw.length

          if (batchRaw.length === 0) break

          accumulatedRaw = (() => {
            const seen = new Set(accumulatedRaw.map((r) => String(r._id || r.id || r.restaurantId)))
            const next = [...accumulatedRaw]
            batchRaw.forEach((r) => {
              const id = String(r._id || r.id || r.restaurantId)
              if (seen.has(id)) return
              seen.add(id)
              next.push(r)
            })
            return next
          })()

          const mappedBatch = mapUnder250Restaurants(batchRaw, location)
          setUnder250Restaurants((prev) =>
            page === 0 && !(cached?.restaurants?.length)
              ? mappedBatch
              : mergeUnique(prev, mappedBatch),
          )
          setVisibleRestaurantCount((n) =>
            Math.max(n, UNDER250_LIST_MAX_VISIBLE, (page + 1) * UNDER250_PAGE_SIZE),
          )
          setLoadingRestaurants(false)
          setFoodPageCache(key, { restaurants: accumulatedRaw, ts: Date.now() })

          page += 1
          if (!hasMore) break
          // Yield so UI stays responsive between pages
          await new Promise((r) => setTimeout(r, 50))
        }

        if (!cancelled) {
          setFoodPageCache(key, { restaurants: accumulatedRaw, ts: Date.now() })
          setLoadingRestaurants(false)
        }
      } catch (error) {
        if (!cancelled) {
          debugError("Error fetching restaurants under 250:", error)
          if (!(cached?.restaurants?.length > 0) && under250Restaurants.length === 0) {
            setUnder250Restaurants([])
          }
          setLoadingRestaurants(false)
        }
      } finally {
        if (fetchInflightRef.current === key) fetchInflightRef.current = null
      }
    }

    loadProgressive()
    return () => {
      cancelled = true
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- location only used for mapping; GPS remapped separately
  }, [zoneId, under250PriceLimit, isTabActive])

  // Fetch categories from backend (no static fallback list)
  useEffect(() => {
    let cancelled = false

    const fetchCategories = async () => {
      try {
        setLoadingCategories((prev) => categories.length === 0 ? true : false)
        const response = await adminAPI.getPublicCategories(zoneId ? { zoneId } : {})
        const categoriesRaw = Array.isArray(response?.data?.data?.categories)
          ? response.data.data.categories
          : []

        const mappedCategories = categoriesRaw
          .map((cat, index) => {
            const name = String(cat?.name || "").trim()
            if (!name) return null

            return {
              id: String(cat?.id || cat?._id || cat?.slug || `cat-${index}`),
              name,
              slug: String(cat?.slug || name.toLowerCase().replace(/\s+/g, "-")),
              foodTypeScope: String(cat?.foodTypeScope || cat?.type || "Both"),
              image:
                cat?.imageUrl ||
                cat?.image ||
                cat?.icon ||
                "",
            }
          })
          .filter(Boolean)

        if (!cancelled) {
          setCategories(mappedCategories)
          setLoadingCategories(false)
        }
      } catch (error) {
        debugError("Error fetching under-250 categories:", error)
        if (!cancelled) {
          setCategories([])
          setLoadingCategories(false)
        }
      }
    }

    fetchCategories()

    return () => {
      cancelled = true
    }
  }, [zoneId])

  // Sync quantities from cart on mount
  useEffect(() => {
    const cartQuantities = {}
    cart.forEach((item) => {
      cartQuantities[item.id] = item.quantity || 0
    })
    setQuantities(cartQuantities)
  }, [cart])

  useEffect(() => {
    if (!selectedItem || !showItemDetail) return

    const defaultVariant = getDefaultFoodVariant(selectedItem)
    const lineItemId = getLineItemIdForDish(selectedItem, defaultVariant)
    const existingQuantity = quantities[lineItemId] || 0
    if (existingQuantity > 0) {
      setItemDetailQuantity(existingQuantity)
    }
  }, [quantities, selectedItem, showItemDetail])

  useEffect(() => {
    if (!showSortPopup) return
    setDraftSelectedSort(selectedSort)
  }, [showSortPopup, selectedSort])

  // (the web locks body scroll behind its popups; native modals already do)

  // Keep-alive: leaving Under250 must unlock body + close sheets or Delivery taps feel dead
  useEffect(() => {
    if (isTabActive) return undefined
    setShowSortPopup(false)
    setShowItemDetail(false)
    setShowShareOptions(false)
    setSelectedItem(null)
    return undefined
  }, [isTabActive])

  useEffect(() => {

    if (!selectedSort && !activeCategory && !under30MinsFilter) {
      localStore.removeItem(UNDER_250_FILTERS_STORAGE_KEY)
      return
    }

    localStore.setItem(
      UNDER_250_FILTERS_STORAGE_KEY,
      JSON.stringify({
        selectedSort,
        activeCategory,
        under30MinsFilter,
      })
    )
  }, [selectedSort, activeCategory, under30MinsFilter])

  // Helper function to update item quantity in both local state and cart
  const updateItemQuantity = (item, newQuantity, event = null, restaurantName = null, preferredVariant = null) => {
    // Check authentication
    if (!isModuleAuthenticated('user')) {
      events.emit('show-login-required')
      return
    }

    // CRITICAL: Check if user is in service zone
    if (isOutOfService) {
      toast.error('You are outside the service zone. Please select a location within the service area.')
      return
    }

    const resolvedVariant = preferredVariant || getDefaultFoodVariant(item)
    const lineItemId = getLineItemIdForDish(item, resolvedVariant)

    // Update local state
    setQuantities((prev) => ({
      ...prev,
      [lineItemId]: newQuantity,
    }))

    // Find restaurant name from the item or use provided parameter
    const restaurant = restaurantName || item.restaurant || "Under 250"

    // Prepare cart item with all required properties
    const cartItem = {
      id: lineItemId,
      lineItemId,
      itemId: item.id,
      name: item.name,
      price: resolvedVariant?.price ?? item.price,
      variantId: resolvedVariant?.id || "",
      variantName: resolvedVariant?.name || "",
      variantPrice: resolvedVariant?.price ?? item.price,
      image: item.image,
      restaurant: restaurant,
      description: item.description || "",
      originalPrice: item.originalPrice || item.price,
      isVeg: item.isVeg === true,
      priceOnOtherPlatforms: null,
      otherPlatformGst: null,
    }

    // The fly-to-cart animation needs a DOM rect; the native cart pill needs none.
    const sourcePosition = null

    // Update cart context
    if (newQuantity <= 0) {
      const productInfo = {
        id: lineItemId,
        name: item.name,
        imageUrl: item.image,
      }
      removeFromCart(lineItemId, sourcePosition, productInfo)
    } else {
      const existingCartItem = getCartItem(lineItemId)
      if (existingCartItem) {
        const productInfo = {
          id: lineItemId,
          name: item.name,
          imageUrl: item.image,
        }

        if (newQuantity > existingCartItem.quantity && sourcePosition) {
          const result = addToCart(cartItem, sourcePosition)
          if (result?.ok === false) {
            toast.error(result.error || 'Cannot add item from different restaurant. Please clear cart first.')
            return
          }
          if (newQuantity > existingCartItem.quantity + 1) {
            updateQuantity(lineItemId, newQuantity)
          }
        } else if (newQuantity < existingCartItem.quantity && sourcePosition) {
          updateQuantity(lineItemId, newQuantity, sourcePosition, productInfo)
        } else {
          updateQuantity(lineItemId, newQuantity)
        }
      } else {
        const result = addToCart(cartItem, sourcePosition)
        if (result?.ok === false) {
          toast.error(result.error || 'Cannot add item from different restaurant. Please clear cart first.')
          return
        }
        if (newQuantity > 1) {
          updateQuantity(lineItemId, newQuantity)
        }
      }
    }
  }

  const closeItemDetail = useCallback(() => {
    setShowItemDetail(false)
    setShowShareOptions(false)
  }, [])

  const goToRestaurantForVariants = (item, restaurant) => {
    const restaurantSlug = restaurant.slug || restaurant.restaurantId || ""
    const itemId = item.id || item._id
    navigate(`/user/restaurants/${restaurantSlug}${itemId ? `?dish=${encodeURIComponent(itemId)}` : ""}`)
  }

  const handleItemClick = (item, restaurant) => {
    const availabilityStatus = getRestaurantAvailabilityStatus(restaurant)
    const isRestaurantOffline = !availabilityStatus.isOpen
    // Add restaurant info to item for display
    const itemWithRestaurant = {
      ...item,
      restaurant: restaurant.name,
      restaurantSlug: restaurant.slug || restaurant.restaurantId || "",
      description: item.description || `${item.name} from ${restaurant.name}`,
      customisable: item.customisable || false,
      notEligibleForCoupons: item.notEligibleForCoupons || false,
      isRestaurantOffline,
    }
    const defaultVariant = getDefaultFoodVariant(item)
    const lineItemId = getLineItemIdForDish(item, defaultVariant)
    const existingQuantity = quantities[lineItemId] || 0
    setItemDetailQuantity(existingQuantity > 0 ? existingQuantity : 1)
    setSelectedItem(itemWithRestaurant)
    setShowShareOptions(false)
    setShowItemDetail(true)
  }

  const handleBookmarkClick = (itemId) => {
    setBookmarkedItems((prev) => {
      const newSet = new Set(prev)
      if (newSet.has(itemId)) {
        newSet.delete(itemId)
      } else {
        newSet.add(itemId)
      }
      return newSet
    })
  }

  const handleShareItem = async (item) => {
    if (!item) return

    const itemId = item.id || item._id
    const restaurantSlug = item.restaurantSlug || item.slug || ""
    const shareUrl = restaurantSlug
      ? `${window.location.origin}/user/restaurants/${restaurantSlug}${itemId ? `?dish=${encodeURIComponent(itemId)}` : ""}`
      : window.location.href

    try {
      if (navigator.share) {
        await navigator.share({
          title: item.name || "Dish",
          text: `Check out ${item.name || "this dish"} from ${item.restaurant || "Under 250"}`,
          url: shareUrl,
        })
        return
      }
    } catch (error) {
      if (error?.name === "AbortError") return
    }

    setShowShareOptions(true)
  }

  const handleShareOption = async (type) => {
    if (!selectedItem) return

    const itemId = selectedItem.id || selectedItem._id
    const restaurantSlug = selectedItem.restaurantSlug || selectedItem.slug || ""
    const shareUrl = restaurantSlug
      ? `${window.location.origin}/user/restaurants/${restaurantSlug}${itemId ? `?dish=${encodeURIComponent(itemId)}` : ""}`
      : window.location.href
    const shareText = `Check out ${selectedItem.name || "this dish"} from ${selectedItem.restaurant || "Under 250"}`
    const encodedUrl = encodeURIComponent(shareUrl)
    const encodedText = encodeURIComponent(`${shareText} ${shareUrl}`)

    try {
      if (type === "copy") {
        await navigator.clipboard.writeText(shareUrl)
        toast.success("Link copied to clipboard!")
      } else if (type === "whatsapp") {
        window.open(`https://wa.me/?text=${encodedText}`, "_blank", "noopener,noreferrer")
      } else if (type === "telegram") {
        window.open(`https://t.me/share/url?url=${encodedUrl}&text=${encodeURIComponent(shareText)}`, "_blank", "noopener,noreferrer")
      } else if (type === "sms") {
        await Linking.openURL(`sms:?&body=${encodedText}`)
      } else if (type === "email") {
        await Linking.openURL(`mailto:?subject=${encodeURIComponent(selectedItem.name || "Dish")}&body=${encodedText}`)
      }
      setShowShareOptions(false)
    } catch {
      toast.error("Failed to share link")
    }
  }

  const handleItemDetailTouchStart = (e) => {
    if (!showItemDetail) return
    itemDetailGestureRef.current = {
      startY: e.touches?.[0]?.clientY || 0,
      dragging: true,
    }
  }

  const handleItemDetailTouchEnd = (e) => {
    if (!showItemDetail || !itemDetailGestureRef.current.dragging) return

    const endY = e.changedTouches?.[0]?.clientY || 0
    const deltaY = endY - itemDetailGestureRef.current.startY
    const contentScrollTop = itemDetailContentRef.current?.scrollTop || 0

    itemDetailGestureRef.current.dragging = false

    if (contentScrollTop <= 0 && deltaY > 80) {
      closeItemDetail()
    }
  }

  const handleItemDetailWheel = (e) => {
    if (!showItemDetail) return
    const contentScrollTop = itemDetailContentRef.current?.scrollTop || 0
    if (contentScrollTop <= 0 && e.deltaY < -20) {
      closeItemDetail()
    }
  }

  // Check if should show grayscale (only when user is out of service)
  const shouldShowGrayscale = isOutOfService

  return {
    initialFiltersRef,
    location,
    zoneId,
    zoneStatus,
    isInService,
    isOutOfService,
    userProfile,
    vegMode,
    vegModeOption,
    navigate,
    addToCart,
    updateQuantity,
    removeFromCart,
    getCartItem,
    cart,
    activeCategory,
    setActiveCategory,
    showSortPopup,
    setShowSortPopup,
    selectedSort,
    setSelectedSort,
    draftSelectedSort,
    setDraftSelectedSort,
    under30MinsFilter,
    setUnder30MinsFilter,
    showItemDetail,
    setShowItemDetail,
    selectedItem,
    setSelectedItem,
    itemDetailQuantity,
    setItemDetailQuantity,
    showShareOptions,
    setShowShareOptions,
    quantities,
    setQuantities,
    bookmarkedItems,
    setBookmarkedItems,
    viewCartButtonBottom,
    setViewCartButtonBottom,
    lastScrollY,
    scrollLockYRef,
    itemDetailContentRef,
    itemDetailGestureRef,
    categories,
    setCategories,
    loadingCategories,
    setLoadingCategories,
    bannerImages,
    setBannerImages,
    loadingBanner,
    setLoadingBanner,
    currentBannerIndex,
    setCurrentBannerIndex,
    isTransitionEnabled,
    setIsTransitionEnabled,
    under250PriceLimit,
    setUnder250PriceLimit,
    cacheKey,
    cachedListRef,
    under250Restaurants,
    setUnder250Restaurants,
    loadingRestaurants,
    setLoadingRestaurants,
    visibleRestaurantCount,
    setVisibleRestaurantCount,
    hasScrolledPastBanner,
    setHasScrolledPastBanner,
    bannerShellRef,
    stickyHeaderRef,
    autoSlideIntervalRef,
    touchStartXRef,
    touchStartYRef,
    touchEndXRef,
    touchEndYRef,
    isBannerSwipingRef,
    fetchInflightRef,
    sortOptions,
    handleClearAll,
    handleApply,
    parseDeliveryTime,
    parseDistance,
    sortedAndFilteredRestaurants,
    displayCategories,
    startBannerAutoSlide,
    resetBannerAutoSlide,
    handleBannerTouchStart,
    handleBannerTouchMove,
    handleBannerTouchEnd,
    updateItemQuantity,
    closeItemDetail,
    goToRestaurantForVariants,
    handleItemClick,
    handleBookmarkClick,
    handleShareItem,
    handleShareOption,
    handleItemDetailTouchStart,
    handleItemDetailTouchEnd,
    handleItemDetailWheel,
    shouldShowGrayscale,
    getLineItemIdForDish,
    RUPEE_SYMBOL,
    UNDER_250_FILTERS_STORAGE_KEY,
    UNDER250_LIST_MAX_VISIBLE,
    UNDER250_ITEMS_PER_RESTAURANT,
    UNDER250_PAGE_SIZE,
    UNDER250_CACHE_TTL_MS,
    isUnder250CacheFresh,
    mapUnder250Restaurants,
    readUnder250Filters,
  }
}
