// Generated by tools/extract-hook.js from Frontend/src/modules/Food/pages/restaurant/OrdersMain.jsx (OutForDeliveryOrders), then edited by hand
// where the web code touched the DOM. The logic is the web page's own.
/* eslint-disable react-hooks/exhaustive-deps, no-unused-vars, no-empty */
import { useState, useEffect } from 'react'
import { restaurantAPI } from '../../../../api/restaurant'

const notificationSound = "/assets/media/restaurant_alert.mp3";

const debugLog = (...args) => { };

const debugWarn = (...args) => { };

const debugError = (...args) => { };

const STORAGE_KEY = "restaurant_online_status";

const filterTabs = [
  { id: "all", label: "All" },
  { id: "preparing", label: "Preparing" },
  { id: "ready", label: "Ready" },
  { id: "out-for-delivery", label: "Out for delivery" },
  { id: "completed", label: "Completed" },
  { id: "cancelled", label: "Cancelled" },
];

const allOrdersStatusGroup = {
  pending: 0,
  confirmed: 0,
  preparing: 0,
  ready: 0,
  out_for_delivery: 0,
  delivered: 1,
  completed: 1,
  picked_up: 1,
  cancelled: 1,
};

const allOrdersStatusPriority = {
  pending: 0,
  confirmed: 1,
  preparing: 2,
  ready: 3,
  out_for_delivery: 4,
  delivered: 6,
  completed: 6,
  picked_up: 6,
  cancelled: 7,
};

const getAllOrdersTimestamp = (order) =>
  order?.cancelledAt ||
  order?.deliveredAt ||
  order?.updatedAt ||
  order?.createdAt ||
  new Date().toISOString();

const TERMINAL_STATUSES = new Set(["delivered", "completed", "picked_up", "cancelled"]);

const HIDDEN_FROM_ORDERS_TAB = new Set([
  "cancelled",
  "canceled",
  "delivered",
  "completed",
  "picked_up",
  "refunded"
]);

const transformOrderForList = (order) => {
  // The restaurant-facing order carries `orderStatus`; `status` is not set on
  // it, so this read was always undefined and every order fell through to the
  // "pending" default below — which is why a freshly-created order displayed as
  // pending and never matched the accept flow.
  const rawStatus = order?.orderStatus ?? order?.status;
  const normalizedStatus = String(rawStatus || "").toLowerCase();
  // Filter out cancelled, delivered, refunded, completed orders from front of Orders tab
  if (HIDDEN_FROM_ORDERS_TAB.has(normalizedStatus)) return null;
  const isTerminal = TERMINAL_STATUSES.has(normalizedStatus);
  // Dining orders are handled via Dining Booking tab, not the food order list
  if (String(order.orderType || "").toLowerCase() === "dining") return null;
  return {
    orderId: order.orderId || order._id,
    mongoId: order._id,
    status: rawStatus || "pending",
    customerName: order.userId?.name || order.customerName || "Customer",
    type: order.orderType === "takeaway"
      ? "Takeaway"
      : order.orderType === "dining"
        ? "Dining"
        : "Home Delivery",
    tableOrToken: null,
    timePlaced: new Date(getAllOrdersTimestamp(order)).toLocaleDateString(
      "en-US",
      {
        month: "short",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      },
    ),
    eta: null,
    itemsSummary:
      order.items?.map((item) => `${item.quantity}x ${item.name}${item.variantName ? ` (${item.variantName})` : ''}`).join(", ") ||
      "No items",
    photoUrl: order.items?.[0]?.image || null,
    photoAlt: order.items?.[0]?.name || "Order",
    paymentMethod: order.paymentMethod || order.payment?.method || null,
    deliveryPartnerId: order.deliveryPartnerId || null,
    dispatchStatus: order.dispatch?.status || null,
    preparingTimestamp: order.tracking?.preparing?.timestamp
      ? new Date(order.tracking.preparing.timestamp)
      : (order.acceptedAt
        ? new Date(order.acceptedAt)
        : new Date(order.createdAt || Date.now())),
    initialETA: order.preparationTime || order.estimatedDeliveryTime || 30,
    // For active orders: sort by creation time (newest first within same status)
    // For terminal orders: sort by the most recent event (cancelledAt/deliveredAt/updatedAt)
    sortTimestamp: isTerminal
      ? new Date(getAllOrdersTimestamp(order)).getTime()
      : new Date(order.createdAt || Date.now()).getTime(),
    restaurantNote: order.restaurantNote || null,
    acceptedAt: order.acceptedAt || null,
  };
};

const isTakeawayOrder = (order) =>
  String(order?.orderType || order?.type || "").toLowerCase() === "takeaway";

/** Accept window used when the admin has not configured one. */

const DEFAULT_ACCEPT_ORDER_TIMEOUT_SECONDS = 5 * 60;

const resolveAcceptOrderTimeoutSeconds = (
  order,
  deliveryTimeoutSeconds,
  takeawayTimeoutSeconds,
) => {
  if (isTakeawayOrder(order)) return takeawayTimeoutSeconds;
  return deliveryTimeoutSeconds;
};

const getInitialCountdown = (order, timeoutSeconds) => {
  if (!timeoutSeconds || timeoutSeconds <= 0) return 0;
  if (!order?.createdAt) return timeoutSeconds;
  const now = Date.now();
  const created = new Date(order.createdAt).getTime();
  const diffInSeconds = Math.floor((now - created) / 1000);
  const remaining = timeoutSeconds - diffInSeconds;
  return Math.max(0, Math.min(timeoutSeconds, remaining));
}

export function useOutForDeliveryOrders({ onSelectOrder, refreshToken = 0 }) {
  const [orders, setOrders] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let isMounted = true;

    const fetchOrders = async () => {
      try {
        // Fetch all orders and filter for 'out_for_delivery' status on frontend
        const response = await restaurantAPI.getOrders();

        if (!isMounted) return;

        if (response.data?.success && response.data.data?.orders) {
          // Filter orders with 'out_for_delivery' status
          const outForDeliveryOrders = response.data.data.orders.filter(
            (order) => order.status === "out_for_delivery",
          );

          const transformedOrders = outForDeliveryOrders.map((order) => ({
            orderId: order.orderId || order._id,
            mongoId: order._id,
            status: order.status || "out_for_delivery",
            customerName: order.userId?.name || "Customer",
            type:
              order.orderType === "takeaway"
                ? "Takeaway"
                : order.orderType === "dining"
                  ? "Dining"
                  : order.deliveryFleet === "standard"
                    ? "Home Delivery"
                    : "Express Delivery",
            tableOrToken: null,
            timePlaced: new Date(order.createdAt).toLocaleTimeString("en-US", {
              hour: "2-digit",
              minute: "2-digit",
            }),
            eta: null,
            itemsSummary:
              order.items
                ?.map((item) => `${item.quantity}x ${item.name}${item.variantName ? ` (${item.variantName})` : ''}`)
                .join(", ") || "No items",
            photoUrl: order.items?.[0]?.image || null,
            photoAlt: order.items?.[0]?.name || "Order",
            paymentMethod: order.paymentMethod || order.payment?.method || null,
            deliveryPartnerId: order.deliveryPartnerId || null,
            dispatchStatus: order.dispatch?.status || null,
            restaurantNote: order.restaurantNote || null,
          }));

          if (isMounted) {
            setOrders(transformedOrders);
            setLoading(false);
          }
        } else {
          if (isMounted) {
            setOrders([]);
            setLoading(false);
          }
        }
      } catch (error) {
        if (!isMounted) return;

        // Don't log network errors repeatedly - they're expected if backend is down
        if (error.code !== "ERR_NETWORK" && error.response?.status !== 404) {
          debugError("Error fetching out for delivery orders:", error);
        }

        if (isMounted) {
          setOrders([]);
          setLoading(false);
        }
      }
    };

    fetchOrders();

    return () => {
      isMounted = false;
    };
  }, [refreshToken]); // Re-fetch only when parent requests it

  return {
    orders,
    setOrders,
    loading,
    setLoading,
    notificationSound,
    STORAGE_KEY,
    filterTabs,
    allOrdersStatusGroup,
    allOrdersStatusPriority,
    getAllOrdersTimestamp,
    TERMINAL_STATUSES,
    HIDDEN_FROM_ORDERS_TAB,
    transformOrderForList,
    isTakeawayOrder,
    DEFAULT_ACCEPT_ORDER_TIMEOUT_SECONDS,
    resolveAcceptOrderTimeoutSeconds,
    getInitialCountdown,
  }
}
