// Generated by tools/extract-hook.js from Frontend/src/modules/Food/pages/restaurant/OrdersMain.jsx (PreparingOrders), then edited by hand
// where the web code touched the DOM. The logic is the web page's own.
/* eslint-disable react-hooks/exhaustive-deps, no-unused-vars, no-empty */
import { useState, useEffect, useRef } from 'react'
import { toast } from '../../../../lib/notify'
import { restaurantAPI } from '../../../../api/restaurant'

const notificationSound = "/assets/media/restaurant_alert.mp3";

const debugLog = (...args) => { };

const debugWarn = (...args) => { };

const debugError = (...args) => { };

const STORAGE_KEY = "restaurant_online_status";

const filterTabs = [
  { id: "all", label: "All" },
  { id: "preparing", label: "Preparing" },
  { id: "ready", label: "Ready" },
  { id: "out-for-delivery", label: "Out for delivery" },
  { id: "completed", label: "Completed" },
  { id: "cancelled", label: "Cancelled" },
];

const allOrdersStatusGroup = {
  pending: 0,
  confirmed: 0,
  preparing: 0,
  ready: 0,
  out_for_delivery: 0,
  delivered: 1,
  completed: 1,
  picked_up: 1,
  cancelled: 1,
};

const allOrdersStatusPriority = {
  pending: 0,
  confirmed: 1,
  preparing: 2,
  ready: 3,
  out_for_delivery: 4,
  delivered: 6,
  completed: 6,
  picked_up: 6,
  cancelled: 7,
};

const getAllOrdersTimestamp = (order) =>
  order?.cancelledAt ||
  order?.deliveredAt ||
  order?.updatedAt ||
  order?.createdAt ||
  new Date().toISOString();

const TERMINAL_STATUSES = new Set(["delivered", "completed", "picked_up", "cancelled"]);

const HIDDEN_FROM_ORDERS_TAB = new Set([
  "cancelled",
  "canceled",
  "delivered",
  "completed",
  "picked_up",
  "refunded"
]);

const transformOrderForList = (order) => {
  // The restaurant-facing order carries `orderStatus`; `status` is not set on
  // it, so this read was always undefined and every order fell through to the
  // "pending" default below — which is why a freshly-created order displayed as
  // pending and never matched the accept flow.
  const rawStatus = order?.orderStatus ?? order?.status;
  const normalizedStatus = String(rawStatus || "").toLowerCase();
  // Filter out cancelled, delivered, refunded, completed orders from front of Orders tab
  if (HIDDEN_FROM_ORDERS_TAB.has(normalizedStatus)) return null;
  const isTerminal = TERMINAL_STATUSES.has(normalizedStatus);
  // Dining orders are handled via Dining Booking tab, not the food order list
  if (String(order.orderType || "").toLowerCase() === "dining") return null;
  return {
    orderId: order.orderId || order._id,
    mongoId: order._id,
    status: rawStatus || "pending",
    customerName: order.userId?.name || order.customerName || "Customer",
    type: order.orderType === "takeaway"
      ? "Takeaway"
      : order.orderType === "dining"
        ? "Dining"
        : "Home Delivery",
    tableOrToken: null,
    timePlaced: new Date(getAllOrdersTimestamp(order)).toLocaleDateString(
      "en-US",
      {
        month: "short",
        day: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      },
    ),
    eta: null,
    itemsSummary:
      order.items?.map((item) => `${item.quantity}x ${item.name}${item.variantName ? ` (${item.variantName})` : ''}`).join(", ") ||
      "No items",
    photoUrl: order.items?.[0]?.image || null,
    photoAlt: order.items?.[0]?.name || "Order",
    paymentMethod: order.paymentMethod || order.payment?.method || null,
    deliveryPartnerId: order.deliveryPartnerId || null,
    dispatchStatus: order.dispatch?.status || null,
    preparingTimestamp: order.tracking?.preparing?.timestamp
      ? new Date(order.tracking.preparing.timestamp)
      : (order.acceptedAt
        ? new Date(order.acceptedAt)
        : new Date(order.createdAt || Date.now())),
    initialETA: order.preparationTime || order.estimatedDeliveryTime || 30,
    // For active orders: sort by creation time (newest first within same status)
    // For terminal orders: sort by the most recent event (cancelledAt/deliveredAt/updatedAt)
    sortTimestamp: isTerminal
      ? new Date(getAllOrdersTimestamp(order)).getTime()
      : new Date(order.createdAt || Date.now()).getTime(),
    restaurantNote: order.restaurantNote || null,
    acceptedAt: order.acceptedAt || null,
  };
};

const isTakeawayOrder = (order) =>
  String(order?.orderType || order?.type || "").toLowerCase() === "takeaway";

/** Accept window used when the admin has not configured one. */

const DEFAULT_ACCEPT_ORDER_TIMEOUT_SECONDS = 5 * 60;

const resolveAcceptOrderTimeoutSeconds = (
  order,
  deliveryTimeoutSeconds,
  takeawayTimeoutSeconds,
) => {
  if (isTakeawayOrder(order)) return takeawayTimeoutSeconds;
  return deliveryTimeoutSeconds;
};

const getInitialCountdown = (order, timeoutSeconds) => {
  if (!timeoutSeconds || timeoutSeconds <= 0) return 0;
  if (!order?.createdAt) return timeoutSeconds;
  const now = Date.now();
  const created = new Date(order.createdAt).getTime();
  const diffInSeconds = Math.floor((now - created) / 1000);
  const remaining = timeoutSeconds - diffInSeconds;
  return Math.max(0, Math.min(timeoutSeconds, remaining));
}

export function usePreparingOrders({
  onSelectOrder,
  onCancel,
  refreshToken = 0,
  onStatusChanged,
}) {
  const [orders, setOrders] = useState([]);
  const [loading, setLoading] = useState(true);
  const [currentTime, setCurrentTime] = useState(() => new Date());
  const [markingReadyOrderIds, setMarkingReadyOrderIds] = useState({});
  const isFetchingRef = useRef(false);

  useEffect(() => {
    let isMounted = true;

    const fetchOrders = async () => {
      if (isFetchingRef.current) return;
      isFetchingRef.current = true;
      try {
        // Fetch all orders and filter for 'preparing' status on frontend
        const response = await restaurantAPI.getOrders();

        if (!isMounted) return;

        if (response.data?.success && response.data.data?.orders) {
          // Filter orders with 'preparing' status only
          // 'confirmed' orders should only appear in popup notification, not in preparing list
          // After accepting, order status changes to 'preparing' and then appears here
          const preparingOrders = response.data.data.orders.filter(
            (order) => order.status === "preparing" && String(order.orderType || "").toLowerCase() !== "dining",
          );

          const transformedOrders = preparingOrders.map((order) => {
            const initialETA = order.preparationTime || order.estimatedDeliveryTime || 30; // in minutes
            const preparingTimestamp = order.tracking?.preparing?.timestamp
              ? new Date(order.tracking.preparing.timestamp)
              : (order.acceptedAt
                ? new Date(order.acceptedAt)
                : new Date(order.createdAt)); // Fallback to createdAt if preparing timestamp not available

            return {
              orderId: order.orderId || order._id,
              mongoId: order._id,
              status: order.status || "preparing",
              customerName: order.userId?.name || "Customer",
              type:
                order.orderType === "takeaway"
                  ? "Takeaway"
                  : order.orderType === "dining"
                    ? "Dining"
                    : order.deliveryFleet === "standard"
                      ? "Home Delivery"
                      : "Express Delivery",
              tableOrToken: null,
              timePlaced: new Date(order.createdAt).toLocaleTimeString(
                "en-US",
                { hour: "2-digit", minute: "2-digit" },
              ),
              initialETA, // Store initial ETA in minutes
              preparingTimestamp, // Store when order started preparing
              itemsSummary:
                order.items
                  ?.map((item) => `${item.quantity}x ${item.name}${item.variantName ? ` (${item.variantName})` : ''}`)
                  .join(", ") || "No items",
              photoUrl: order.items?.[0]?.image || null,
              photoAlt: order.items?.[0]?.name || "Order",
              deliveryPartnerId: order.deliveryPartnerId || null,
              dispatchStatus: order.dispatch?.status || null,
              paymentMethod:
                order.paymentMethod || order.payment?.method || null,
              restaurantNote: order.restaurantNote || null,
            };
          });

          if (isMounted) {
            setOrders(transformedOrders);
            setLoading(false);
          }
        } else {
          if (isMounted) {
            setOrders([]);
            setLoading(false);
          }
        }
      } catch (error) {
        if (!isMounted) return;

        // Don't log network errors, 404, or 401 errors
        // 401 is handled by axios interceptor (token refresh/redirect)
        // 404 means no orders found (normal)
        // ERR_NETWORK means backend is down (expected in dev)
        if (
          error.code !== "ERR_NETWORK" &&
          error.response?.status !== 404 &&
          error.response?.status !== 401
        ) {
          debugError("Error fetching preparing orders:", error);
        }

        if (isMounted) {
          setOrders([]);
          setLoading(false);
        }
      } finally {
        if (isMounted) {
          isFetchingRef.current = false;
        }
      }
    };

    fetchOrders();

    // Update countdown every second
    const countdownIntervalId = setInterval(() => {
      if (isMounted) {
        setCurrentTime(new Date());
      }
    }, 1000);

    return () => {
      isMounted = false;
      if (countdownIntervalId) {
        clearInterval(countdownIntervalId);
      }
    };
  }, [refreshToken]); // Re-fetch only when parent requests it

  // Track which orders have been marked as ready to avoid duplicate API calls
  const markedReadyOrdersRef = useRef(new Set());

  // Auto-mark orders as ready when ETA reaches 0
  useEffect(() => {
    if (orders.length === 0) return;

    const checkAndMarkReady = async () => {
      const now = new Date();
      for (const order of orders) {
        const orderKey = order.mongoId || order.orderId;

        // Skip if already marked as ready
        if (markedReadyOrdersRef.current.has(orderKey)) {
          continue;
        }

        // Calculate remaining ETA
        const elapsedMs = now - order.preparingTimestamp;
        const elapsedMinutes = Math.floor(elapsedMs / 60000);
        const remainingMinutes = Math.max(0, order.initialETA - elapsedMinutes);

        // If ETA has reached 0 (or slightly past), mark as ready
        if (remainingMinutes <= 0 && order.status === "preparing") {
          const elapsedSeconds = Math.floor(elapsedMs / 1000);
          const totalETASeconds = order.initialETA * 60;

          // Mark as ready when ETA time has elapsed (with 2 second buffer)
          if (elapsedSeconds >= totalETASeconds - 2) {
            try {
              debugLog(
                `?? Auto-marking order ${order.orderId} as ready (ETA reached 0)`,
              );
              markedReadyOrdersRef.current.add(orderKey); // Mark as processing
              await restaurantAPI.markOrderReady(
                order.mongoId || order.orderId,
              );
              debugLog(`? Order ${order.orderId} marked as ready`);
              onStatusChanged?.();
              // Order will be removed from preparing list on next fetch
            } catch (error) {
              const status = error.response?.status;
              const msg = (
                error.response?.data?.message ||
                error.message ||
                ""
              ).toLowerCase();
              // If 400 and message says order cannot be marked ready (e.g. already ready),
              // treat as idempotent - backend cron or another client already marked it.
              if (
                status === 400 &&
                (msg.includes("cannot be marked as ready") ||
                  msg.includes("current status"))
              ) {
                // Keep in markedReadyOrdersRef so we don't retry; order will disappear on next fetch
              } else {
                debugError(
                  `? Failed to auto-mark order ${order.orderId} as ready:`,
                  error,
                );
                markedReadyOrdersRef.current.delete(orderKey);
              }
              // Don't show error toast - it will retry on next check (for non-idempotent errors)
            }
          }
        }
      }
    };

    // Check every 2 seconds for orders that need to be marked ready
    const readyCheckInterval = setInterval(checkAndMarkReady, 2000);

    return () => {
      clearInterval(readyCheckInterval);
    };
  }, [orders, onStatusChanged]);

  // Clear marked orders when orders list changes (orders moved to ready)
  useEffect(() => {
    const currentOrderKeys = new Set(orders.map((o) => o.mongoId || o.orderId));
    // Remove keys that are no longer in the preparing orders list
    for (const key of markedReadyOrdersRef.current) {
      if (!currentOrderKeys.has(key)) {
        markedReadyOrdersRef.current.delete(key);
      }
    }
  }, [orders]);

  const handleMarkReady = async ({ orderId, mongoId, customerName }) => {
    const orderKey = mongoId || orderId;
    if (!orderKey || markingReadyOrderIds[orderKey]) return;

    try {
      setMarkingReadyOrderIds((prev) => ({ ...prev, [orderKey]: true }));
      await restaurantAPI.markOrderReady(orderKey);
      setOrders((prev) =>
        prev.filter((order) => (order.mongoId || order.orderId) !== orderKey),
      );
      toast.success(
        `Order ${orderId} marked ready${customerName ? ` for ${customerName}` : ""}`,
      );
      onStatusChanged?.();
    } catch (error) {
      const status = error.response?.status;
      const message =
        error.response?.data?.message || "Failed to mark order as ready";
      if (
        status === 400 &&
        String(message).toLowerCase().includes("current status")
      ) {
        setOrders((prev) =>
          prev.filter((order) => (order.mongoId || order.orderId) !== orderKey),
        );
        toast.success(`Order ${orderId} is already ready`);
        onStatusChanged?.();
      } else {
        toast.error(message);
      }
    } finally {
      setMarkingReadyOrderIds((prev) => {
        const next = { ...prev };
        delete next[orderKey];
        return next;
      });
    }
  };

  return {
    orders,
    setOrders,
    loading,
    setLoading,
    currentTime,
    setCurrentTime,
    markingReadyOrderIds,
    setMarkingReadyOrderIds,
    isFetchingRef,
    markedReadyOrdersRef,
    handleMarkReady,
    notificationSound,
    STORAGE_KEY,
    filterTabs,
    allOrdersStatusGroup,
    allOrdersStatusPriority,
    getAllOrdersTimestamp,
    TERMINAL_STATUSES,
    HIDDEN_FROM_ORDERS_TAB,
    transformOrderForList,
    isTakeawayOrder,
    DEFAULT_ACCEPT_ORDER_TIMEOUT_SECONDS,
    resolveAcceptOrderTimeoutSeconds,
    getInitialCountdown,
  }
}
