// Generated by tools/extract-hook.js from Frontend/src/modules/Food/pages/restaurant/DownloadReport.jsx (DownloadReport), then edited by hand
// where the web code touched the DOM. The logic is the web page's own.
/* eslint-disable react-hooks/exhaustive-deps, no-unused-vars, no-empty */
import { useState, useMemo, useEffect } from 'react'
import { useNavigate } from '../../../lib/webRouter'
import useRestaurantBackNavigation from '../useRestaurantBackNavigation'

const REPORT_VIEWS = [
  { id: "detailed", label: "Detailed report" },
  { id: "item", label: "Item sales report" },
]

const VIEW_TYPES = ["DAILY", "WEEKLY", "MONTHLY"]

export function useDownloadReport() {
  const navigate = useNavigate()
  const goBack = useRestaurantBackNavigation()
  const [reportView, setReportView] = useState("detailed")
  const [viewType, setViewType] = useState("DAILY")
  const durations = useMemo(() => {
    if (viewType === "WEEKLY") {
      return [
        { id: "4w", label: "Last 4 weeks" },
        { id: "8w", label: "Last 8 weeks" },
        { id: "12w", label: "Last 12 weeks" },
        { id: "custom", label: "Custom" },
      ]
    }
    if (viewType === "MONTHLY") {
      return [
        { id: "3m", label: "Last 3 months" },
        { id: "6m", label: "Last 6 months" },
        { id: "12m", label: "Last 12 months" },
        { id: "custom", label: "Custom" },
      ]
    }
    return [
      { id: "7", label: "Last 7 days" },
      { id: "14", label: "Last 14 days" },
      { id: "30", label: "Last 30 days" },
      { id: "custom", label: "Custom" },
    ]
  }, [viewType])

  const [duration, setDuration] = useState("7")
  const [showSuccess, setShowSuccess] = useState(false)

  useEffect(() => {
    if (durations.length > 0 && !durations.find((d) => d.id === duration)) {
      setDuration(durations[0].id)
    }
  }, [viewType, durations, duration])

  const handleSend = () => {
    setShowSuccess(true)
    setTimeout(() => setShowSuccess(false), 2000)
  }

  return {
    navigate,
    goBack,
    reportView,
    setReportView,
    viewType,
    setViewType,
    durations,
    duration,
    setDuration,
    showSuccess,
    setShowSuccess,
    handleSend,
    REPORT_VIEWS,
    VIEW_TYPES,
  }
}
