// Generated by tools/extract-hook.js from Frontend/src/modules/Food/pages/restaurant/DiningReservations.jsx (DiningReservations), then edited by hand
// where the web code touched the DOM. The logic is the web page's own.
/* eslint-disable react-hooks/exhaustive-deps, no-unused-vars, no-empty */
import { useState, useEffect, useMemo } from 'react'
import { useNavigate } from '../../../lib/webRouter'
import useRestaurantBackNavigation from '../useRestaurantBackNavigation'
import { diningAPI, restaurantAPI } from '../../../api/restaurant'
import { toast } from '../../../lib/notify'

const debugError = (...args) => {}

const getRestaurantFromResponse = (response) =>
    response?.data?.data?.restaurant ||
    response?.data?.restaurant ||
    response?.data?.data ||
    null

const normalizeImageEntry = (entry) => {
    if (!entry) return null
    if (typeof entry === "string") {
        const url = entry.trim()
        return url ? { url, publicId: null } : null
    }
    const url = String(entry?.url || "").trim()
    if (!url) return null
    return {
        url,
        publicId: entry?.publicId || null,
    }
}

const getProfilePhotoUrl = (restaurant) => {
    const candidate = restaurant?.profileImage
    if (!candidate) return ""
    if (typeof candidate === "string") return candidate.trim()
    return String(candidate?.url || "").trim()
}

const getCoverImages = (restaurant) => {
    const base = Array.isArray(restaurant?.coverImages) ? restaurant.coverImages : []
    return base
        .map(normalizeImageEntry)
        .filter(Boolean)
}

const getMenuImages = (restaurant) => {
    const base = Array.isArray(restaurant?.menuImages) ? restaurant.menuImages : []

    return base
        .map(normalizeImageEntry)
        .filter(Boolean)
}

const getBookerName = (booking) =>
    String(
        booking?.user?.name ||
        booking?.customerName ||
        booking?.bookedBy?.name ||
        booking?.name ||
        "Guest"
    ).trim()

const getBookerPhone = (booking) =>
    String(
        booking?.user?.phone ||
        booking?.phone ||
        booking?.phoneNumber ||
        booking?.mobile ||
        booking?.bookedBy?.phone ||
        ""
    ).trim()

export function useDiningReservations() {
    const navigate = useNavigate()
    const goBack = useRestaurantBackNavigation()
    const [bookings, setBookings] = useState([])
    const [loading, setLoading] = useState(true)
    const [restaurant, setRestaurant] = useState(null)
    const [searchTerm, setSearchTerm] = useState("")
    const [restaurantPhoto, setRestaurantPhoto] = useState("")
    const [restaurantPhotos, setRestaurantPhotos] = useState([])
    const [menuPhotos, setMenuPhotos] = useState([])
    const [uploadingRestaurantPhoto, setUploadingRestaurantPhoto] = useState(false)
    const [uploadingMenuPhotos, setUploadingMenuPhotos] = useState(false)
    const [removingRestaurantPhoto, setRemovingRestaurantPhoto] = useState(false)
    const [removingMenuPhoto, setRemovingMenuPhoto] = useState(false)
    const [uploadMessage, setUploadMessage] = useState("")
    const [uploadError, setUploadError] = useState("")
    const [activeSection, setActiveSection] = useState("reservations")
    const [activeView, setActiveView] = useState("priority")
    const [showMediaPanel, setShowMediaPanel] = useState(false)
    const [diningEnabled, setDiningEnabled] = useState(false)
    const [maxGuestsLimit, setMaxGuestsLimit] = useState(6)
    const [savingDiningSettings, setSavingDiningSettings] = useState(false)
    const [diningSettingsMessage, setDiningSettingsMessage] = useState("")
    const [diningSettingsError, setDiningSettingsError] = useState("")
    const [diningType, setDiningType] = useState([])
    const [availableCategories, setAvailableCategories] = useState([])
    const [pendingRequest, setPendingRequest] = useState(null)
    const [fetchingRequest, setFetchingRequest] = useState(true)

    const syncRestaurantMediaState = (restaurantData) => {
        setRestaurant(restaurantData || null)
        const coverImages = getCoverImages(restaurantData)
        const profileImage = getProfilePhotoUrl(restaurantData)
        setRestaurantPhotos(coverImages)
        setRestaurantPhoto(coverImages[0]?.url || profileImage)
        setMenuPhotos(getMenuImages(restaurantData))
        setDiningEnabled(Boolean(restaurantData?.diningSettings?.isEnabled))
        setMaxGuestsLimit(Math.max(1, parseInt(restaurantData?.diningSettings?.maxGuests, 10) || 6))
        
        const rawDiningType = restaurantData?.diningSettings?.diningType
        setDiningType(Array.isArray(rawDiningType) ? rawDiningType : (rawDiningType ? [rawDiningType].filter(Boolean) : []))
    }

    useEffect(() => {
        const fetchAll = async (isPoll = false) => {
            try {
                if (!isPoll) setLoading(true)

                const resResponse = await restaurantAPI.getCurrentRestaurant()
                if (resResponse.data.success) {
                    const resData = getRestaurantFromResponse(resResponse)
                    const restaurantId = resData?._id || resData?.id

                    if (restaurantId) {
                        syncRestaurantMediaState(resData)

                        if (!isPoll) {
                            const bookingsResponse = await diningAPI.getRestaurantBookings(resData)
                            if (bookingsResponse.data.success) {
                                setBookings(Array.isArray(bookingsResponse.data.data) ? bookingsResponse.data.data : [])
                            }

                            const catRes = await diningAPI.getCategories()
                            if (catRes.data.success) {
                                setAvailableCategories(catRes.data.data || [])
                            }
                        }

                        const requestRes = await restaurantAPI.getPendingDiningRequest()
                        const newPendingRequest = requestRes.data.success && requestRes.data.data ? requestRes.data.data : null

                        if (pendingRequest && !newPendingRequest) {
                            const updatedRes = await restaurantAPI.getCurrentRestaurant()
                            const updatedData = getRestaurantFromResponse(updatedRes)
                            
                            // Simple check: if isEnabled matches what we requested, it was likely approved
                            const requestedEnabled = pendingRequest.requestedSettings?.isEnabled
                            const currentEnabled = updatedData?.diningSettings?.isEnabled
                            
                            if (requestedEnabled === currentEnabled) {
                                toast.success("Dining settings updated and approved!")
                            } else {
                                toast.error("Your dining settings request was rejected by admin.")
                            }
                            
                            syncRestaurantMediaState(updatedData)
                        }

                        setPendingRequest(newPendingRequest)

                        if (newPendingRequest?.requestedSettings) {
                            setDiningEnabled(newPendingRequest.requestedSettings.isEnabled)
                            setMaxGuestsLimit(newPendingRequest.requestedSettings.maxGuests)
                            const reqType = newPendingRequest.requestedSettings.diningType
                            setDiningType(Array.isArray(reqType) ? reqType : (reqType ? [reqType] : []))
                        }
                    }
                }
            } catch (error) {
                if (!isPoll) debugError("Error fetching dining data:", error)
            } finally {
                if (!isPoll) {
                    setLoading(false)
                    setFetchingRequest(false)
                }
            }
        }

        fetchAll()
        let interval
        if (pendingRequest) {
            interval = setInterval(() => fetchAll(true), 15000)
        }
        return () => interval && clearInterval(interval)
    }, [pendingRequest?._id])

    const handleRestaurantPhotoUpload = async (event) => {
        const files = Array.from(event.target.files || [])
        if (files.length === 0) return

        setUploadError("")
        setUploadMessage("")
        setUploadingRestaurantPhoto(true)

        try {
            await restaurantAPI.uploadCoverImages(files)
            const refreshedResponse = await restaurantAPI.getCurrentRestaurant()
            const refreshedRestaurant = getRestaurantFromResponse(refreshedResponse)
            syncRestaurantMediaState(refreshedRestaurant)
            setUploadMessage(`Uploaded ${files.length} restaurant photo(s) successfully.`)
        } catch (error) {
            debugError("Error uploading restaurant photo:", error)
            setUploadError(error?.response?.data?.message || "Failed to upload restaurant photos.")
        } finally {
            setUploadingRestaurantPhoto(false)
            event.target.value = ""
        }
    }

    const handleMenuPhotosUpload = async (event) => {
        const files = Array.from(event.target.files || [])
        if (files.length === 0) return

        setUploadError("")
        setUploadMessage("")
        setUploadingMenuPhotos(true)

        try {
            await restaurantAPI.uploadMenuImages(files)
            const refreshedResponse = await restaurantAPI.getCurrentRestaurant()
            syncRestaurantMediaState(getRestaurantFromResponse(refreshedResponse))
            setUploadMessage(`Uploaded ${files.length} menu photo(s) successfully.`)
        } catch (error) {
            debugError("Error saving menu photos:", error)
            setUploadError(error?.response?.data?.message || "Failed to upload menu photos.")
        } finally {
            setUploadingMenuPhotos(false)
            event.target.value = ""
        }
    }

    const handleRemoveRestaurantPhoto = async (photoUrl) => {
        if (!photoUrl || removingRestaurantPhoto) return

        setUploadError("")
        setUploadMessage("")
        setRemovingRestaurantPhoto(true)

        try {
            const nextCoverImages = restaurantPhotos.filter((photo) => photo.url !== photoUrl)
            const currentProfileImage = getProfilePhotoUrl(restaurant)
            const nextPrimaryPhoto = nextCoverImages[0]?.url || ""
            const shouldClearProfileImage = !nextPrimaryPhoto && currentProfileImage === photoUrl

            const response = await restaurantAPI.updateProfile({
                coverImages: nextCoverImages.map((photo) => ({
                    url: photo.url,
                    ...(photo.publicId ? { publicId: photo.publicId } : {}),
                })),
                ...(shouldClearProfileImage ? { profileImage: "" } : {}),
            })

            const updatedRestaurant = getRestaurantFromResponse(response)
            if (updatedRestaurant) {
                syncRestaurantMediaState(updatedRestaurant)
            } else {
                const refreshedResponse = await restaurantAPI.getCurrentRestaurant()
                syncRestaurantMediaState(getRestaurantFromResponse(refreshedResponse))
            }

            setUploadMessage("Restaurant photo removed successfully.")
        } catch (error) {
            debugError("Error removing restaurant photo:", error)
            setUploadError(error?.response?.data?.message || "Failed to remove restaurant photo.")
        } finally {
            setRemovingRestaurantPhoto(false)
        }
    }

    const handleRemoveMenuPhoto = async (photoUrl) => {
        if (!photoUrl || removingMenuPhoto) return

        setUploadError("")
        setUploadMessage("")
        setRemovingMenuPhoto(true)

        try {
            const nextMenuPhotos = menuPhotos.filter((photo) => photo.url !== photoUrl)
            const response = await restaurantAPI.updateProfile({
                menuImages: nextMenuPhotos.map((photo) => ({
                    url: photo.url,
                    ...(photo.publicId ? { publicId: photo.publicId } : {}),
                })),
            })

            const updatedRestaurant = getRestaurantFromResponse(response)
            if (updatedRestaurant) {
                syncRestaurantMediaState(updatedRestaurant)
            } else {
                const refreshedResponse = await restaurantAPI.getCurrentRestaurant()
                syncRestaurantMediaState(getRestaurantFromResponse(refreshedResponse))
            }

            setUploadMessage("Menu photo removed successfully.")
        } catch (error) {
            debugError("Error removing menu photo:", error)
            setUploadError(error?.response?.data?.message || "Failed to remove menu photo.")
        } finally {
            setRemovingMenuPhoto(false)
        }
    }

    const handleSaveDiningSettings = async () => {
        if (!restaurant || savingDiningSettings || pendingRequest) return

        if (!diningType || diningType.length === 0) {
            setDiningSettingsError("Please select at least one dining category")
            toast.error("Dining category is required")
            return
        }

        const nextMaxGuests = parseInt(maxGuestsLimit, 10) || 0

        if (diningEnabled && nextMaxGuests <= 0) {
            setDiningSettingsError("Guest limit must be at least 1 when dining is enabled")
            toast.error("Set at least 1 guest limit to enable dining")
            return
        }

        const nextDiningSettings = {
            isEnabled: Boolean(diningEnabled),
            maxGuests: nextMaxGuests,
            diningType: Array.isArray(diningType) ? [...new Set(diningType)] : [diningType],
        }

        setDiningSettingsError("")
        setDiningSettingsMessage("")
        setSavingDiningSettings(true)

        try {
            const response = await restaurantAPI.requestDiningUpdate(nextDiningSettings)

            if (response.data.success) {
                setPendingRequest(response.data.data)
                setDiningSettingsMessage("Update request sent to admin for approval.")
                toast.success("Request sent for approval")
            }
        } catch (error) {
            debugError("Error requesting dining settings update:", error)
            setDiningSettingsError(error?.response?.data?.message || "Failed to submit request.")
            toast.error(error?.response?.data?.message || "Failed to submit request")
        } finally {
            setSavingDiningSettings(false)
        }
    }

    const handleStatusUpdate = async (bookingId, newStatus) => {
        try {
            const response = await diningAPI.updateBookingStatusRestaurant(bookingId, newStatus)
             if (response.data.success) {
                // Update local state
                setBookings(prev => prev.map(b =>
                    b._id === bookingId ? { ...b, status: newStatus } : b
                ))
                toast.success(`Booking ${newStatus === 'accepted' ? 'confirmed' : 'declined'}`)
            }
        } catch (error) {
            debugError("Error updating status:", error)
            toast.error("Failed to update status")
        }
    }

    const getStatusPriority = (status) => {
        const key = String(status || "").toLowerCase()
        if (key === "pending") return 0
        if (key === "confirmed") return 1
        if (key === "accepted") return 2
        if (key === "checked-in") return 3
        if (key === "completed") return 4
        if (key === "cancelled") return 5
        return 6
    }

    const getBookingTimestamp = (booking) => {
        const createdAtTs = new Date(booking?.createdAt || "").getTime()
        if (!Number.isNaN(createdAtTs)) return createdAtTs
        const dateTs = new Date(booking?.date || "").getTime()
        if (!Number.isNaN(dateTs)) return dateTs
        return 0
    }

    const isToday = (value) => {
        const date = new Date(value)
        if (Number.isNaN(date.getTime())) return false
        return date.toDateString() === new Date().toDateString()
    }

    const isNewRequest = (booking) => {
        if (String(booking?.status || "").toLowerCase() !== "pending") return false
        const createdAt = new Date(booking?.createdAt || booking?.date || "").getTime()
        if (Number.isNaN(createdAt)) return true
        return new Date().getTime() - createdAt <= 2 * 60 * 60 * 1000 // eslint-disable-line react-hooks/purity
    }

    const sortedBookings = useMemo(() => {
        return [...bookings].sort((a, b) => {
            const priorityDiff = getStatusPriority(a?.status) - getStatusPriority(b?.status)
            if (priorityDiff !== 0) return priorityDiff
            return getBookingTimestamp(b) - getBookingTimestamp(a)
        })
    }, [bookings])

    const filteredBookings = useMemo(() => {
        const term = searchTerm.trim().toLowerCase()
        return sortedBookings
            .filter((booking) => {
                if (!term) return true
                return (
                    getBookerName(booking).toLowerCase().includes(term) ||
                    String(booking?.bookingId || "").toLowerCase().includes(term) ||
                    getBookerPhone(booking).toLowerCase().includes(term)
                )
            })
            .filter((booking) => {
                if (activeView === "today") return isToday(booking?.date)
                if (activeView === "new") return isNewRequest(booking)
                return true
            })
    }, [sortedBookings, searchTerm, activeView])

    const newRequestsCount = useMemo(
        () => bookings.filter((booking) => isNewRequest(booking)).length,
        [bookings]
    )

    return {
        navigate,
        goBack,
        bookings,
        setBookings,
        loading,
        setLoading,
        restaurant,
        setRestaurant,
        searchTerm,
        setSearchTerm,
        restaurantPhoto,
        setRestaurantPhoto,
        restaurantPhotos,
        setRestaurantPhotos,
        menuPhotos,
        setMenuPhotos,
        uploadingRestaurantPhoto,
        setUploadingRestaurantPhoto,
        uploadingMenuPhotos,
        setUploadingMenuPhotos,
        removingRestaurantPhoto,
        setRemovingRestaurantPhoto,
        removingMenuPhoto,
        setRemovingMenuPhoto,
        uploadMessage,
        setUploadMessage,
        uploadError,
        setUploadError,
        activeSection,
        setActiveSection,
        activeView,
        setActiveView,
        showMediaPanel,
        setShowMediaPanel,
        diningEnabled,
        setDiningEnabled,
        maxGuestsLimit,
        setMaxGuestsLimit,
        savingDiningSettings,
        setSavingDiningSettings,
        diningSettingsMessage,
        setDiningSettingsMessage,
        diningSettingsError,
        setDiningSettingsError,
        diningType,
        setDiningType,
        availableCategories,
        setAvailableCategories,
        pendingRequest,
        setPendingRequest,
        fetchingRequest,
        setFetchingRequest,
        syncRestaurantMediaState,
        handleRestaurantPhotoUpload,
        handleMenuPhotosUpload,
        handleRemoveRestaurantPhoto,
        handleRemoveMenuPhoto,
        handleSaveDiningSettings,
        handleStatusUpdate,
        getStatusPriority,
        getBookingTimestamp,
        isToday,
        isNewRequest,
        sortedBookings,
        filteredBookings,
        newRequestsCount,
        getRestaurantFromResponse,
        normalizeImageEntry,
        getProfilePhotoUrl,
        getCoverImages,
        getMenuImages,
        getBookerName,
        getBookerPhone,
    }
}
