// Generated by tools/extract-hook.js from Frontend/src/modules/Food/pages/restaurant/FssaiUpdate.jsx (FssaiUpdate), then edited by hand
// where the web code touched the DOM. The logic is the web page's own.
/* eslint-disable react-hooks/exhaustive-deps, no-unused-vars, no-empty */
import { useState, useRef } from 'react'
import { useNavigate } from '../../../lib/webRouter'
import useRestaurantBackNavigation from '../useRestaurantBackNavigation'
import { toast } from '../../../lib/notify'



export function useFssaiUpdate() {
  const navigate = useNavigate()
  const goBack = useRestaurantBackNavigation()
  const [uploadedFile, setUploadedFile] = useState(null)
  const [isPhotoPickerOpen, setIsPhotoPickerOpen] = useState(false)
  const fileInputRef = useRef(null)

  const handleFileSelect = (file) => {
    if (file) {
      if (file.size > 5 * 1024 * 1024) {
        toast.error("Image size too large. Max 5MB allowed.")
        return
      }
      setUploadedFile(file)
      toast.success("FSSAI license uploaded")
    }
  }

  const handleFileClick = () => {
    setIsPhotoPickerOpen(true)
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    // For now just go back
    toast.success("FSSAI details updated")
    goBack()
  }

  return {
    navigate,
    goBack,
    uploadedFile,
    setUploadedFile,
    isPhotoPickerOpen,
    setIsPhotoPickerOpen,
    fileInputRef,
    handleFileSelect,
    handleFileClick,
    handleSubmit,
  }
}
