// Generated by tools/extract-hook.js from Frontend/src/modules/Food/pages/restaurant/FssaiDetails.jsx (FssaiDetails), then edited by hand
// where the web code touched the DOM. The logic is the web page's own.
/* eslint-disable react-hooks/exhaustive-deps, no-unused-vars, no-empty */
import { useNavigate } from '../../../lib/webRouter'
import useRestaurantBackNavigation from '../useRestaurantBackNavigation'



export function useFssaiDetails() {
  const navigate = useNavigate()
  const goBack = useRestaurantBackNavigation()

  return {
    navigate,
    goBack,
  }
}
