// Generated by tools/extract-hook.js from Frontend/src/modules/Food/pages/restaurant/FinanceDetailsPage.jsx (FinanceDetailsPage), then edited by hand
// where the web code touched the DOM. The logic is the web page's own.
/* eslint-disable react-hooks/exhaustive-deps, no-unused-vars, no-empty */
// The web page uses useMemo without importing it (the page throws there); imported here so it renders.
import { useMemo, useState, useRef, useEffect } from 'react'
import { useNavigate, useLocation } from '../../../lib/webRouter'
import useRestaurantBackNavigation from '../useRestaurantBackNavigation'



export function useFinanceDetailsPage() {
  const navigate = useNavigate()
  const goBack = useRestaurantBackNavigation()
  const location = useLocation()
  const financeData = location.state?.financeData || null
  const restaurantData = location.state?.restaurantData || null
  
  const [activeTab, setActiveTab] = useState("summary")
  const [isTransitioning, setIsTransitioning] = useState(false)
  const [showDownloadPopup, setShowDownloadPopup] = useState(false)
  const [showEmailPopup, setShowEmailPopup] = useState(false)
  const [expandedSections, setExpandedSections] = useState({
    netOrderValue: true,
    additions: true,
    orderLevelDeductions: true,
    taxDeductions: true,
    investmentsInGrowth: true,
  })
  const topTabBarRef = useRef(null)

  const tabs = [
    { id: "summary", label: "Summary" },
    { id: "orders", label: "Orders" },
    { id: "expenses", label: "Expenses" },
  ]

  const scrollToTopTab = (index) => {
    if (topTabBarRef.current) {
      const buttons = topTabBarRef.current.querySelectorAll("button")
      if (buttons[index]) {
        const button = buttons[index]
        const container = topTabBarRef.current
        const buttonLeft = button.offsetLeft
        const buttonWidth = button.offsetWidth
        const containerWidth = container.offsetWidth
        const scrollLeft = buttonLeft - containerWidth / 2 + buttonWidth / 2

        container.scrollTo({
          left: scrollLeft,
          behavior: "smooth",
        })
      }
    }
  }

  useEffect(() => {
    const index = tabs.findIndex((tab) => tab.id === activeTab)
    if (index >= 0) {
      requestAnimationFrame(() => scrollToTopTab(index))
    }
  }, [activeTab])

  const handleDownload = () => {
    setShowDownloadPopup(true)
    // In a real app, this would trigger PDF download
    setTimeout(() => {
      setShowDownloadPopup(false)
    }, 2000)
  }

  const handleEmail = () => {
    setShowEmailPopup(true)
    // In a real app, this would send email
    setTimeout(() => {
      setShowEmailPopup(false)
    }, 2000)
  }

  // Settlement data with real values from financeData
  const settlementData = useMemo(() => {
    const cycle = financeData?.currentCycle || {};
    const summary = financeData?.invoiceSummary || {};
    
    return {
      totalOrders: cycle.totalOrders || 0,
      netOrderValue: {
        itemSubtotal: summary.subtotal || 0,
        totalGSTCollected: summary.taxes || 0,
        restaurantDiscountPromos: 0,
        restaurantDiscountOthers: 0,
        total: summary.subtotal || 0
      },
      additions: {
        tds194H: 0,
        tds194C: 0,
        total: 0
      },
      orderLevelDeductions: {
        total: 0
      },
      taxDeductions: {
        gstOnServiceFees: 0,
        tds194O: 0,
        gstPaidByZomato: 0,
        total: summary.taxes || 0
      },
      investmentsInGrowth: {
        onlineOrderingAds: 0,
        total: 0
      },
      estimatedPayout: cycle.estimatedPayout || 0,
      start: cycle.start?.day || "15",
      end: cycle.end?.day || "21",
      month: cycle.start?.month || "Dec",
      year: cycle.start?.year || "25"
    }
  }, [financeData])

  const estimatedPayout = settlementData.estimatedPayout;

  const toggleSection = (section) => {
    setExpandedSections(prev => ({
      ...prev,
      [section]: !prev[section]
    }))
  }

  return {
    navigate,
    goBack,
    location,
    financeData,
    restaurantData,
    activeTab,
    setActiveTab,
    isTransitioning,
    setIsTransitioning,
    showDownloadPopup,
    setShowDownloadPopup,
    showEmailPopup,
    setShowEmailPopup,
    expandedSections,
    setExpandedSections,
    topTabBarRef,
    tabs,
    scrollToTopTab,
    handleDownload,
    handleEmail,
    settlementData,
    estimatedPayout,
    toggleSection,
  }
}
