// Generated by tools/extract-hook.js from Frontend/src/modules/Food/pages/restaurant/Onboarding.jsx (RestaurantOnboarding), then edited by hand
// where the web code touched the DOM. The logic is the web page's own.
/* eslint-disable react-hooks/exhaustive-deps, no-unused-vars, no-empty */
import { useCallback, useEffect, useRef, useState } from 'react'
import { useNavigate, useSearchParams } from '../../../lib/webRouter'
import { restaurantAPI, zoneAPI, uploadAPI, api } from '../../../api/restaurant'
import { clearOnboardingFromLocalStorage, clearAllFilesFromDB, hasRestaurantStep1Progress, ONBOARDING_FILE_KEY_PREFIX } from '../../utils/onboardingUtils'
import { toast } from '../../../lib/notify'
import { useCompanyName } from '../useCompanyName'
import { getGoogleMapsApiKey } from '../../utils/googleMapsApiKey'
import { clearModuleAuth, clearAuthData, getModuleToken } from '../../utils/auth'
import { prepareUploadFile } from '../../../lib/images'
import { geocodeAPI } from '../../../api/geocode'
import { BackHandler, Keyboard } from 'react-native'
import { collectFcmTokenForSignup, persistModuleFcmToken, syncPendingPartnerFcmQuick, clearOnboardingFcmLocalState } from '../../../lib/push'
import { setAuthData } from '../../utils/auth'
import { clearOnboardingIntent } from '../../utils/partnerSession'
import { localStore } from '../../../lib/storage'
import { events } from '../../../lib/events'

const debugLog = (...args) => {}

const debugWarn = (...args) => {}

const debugError = (...args) => {}

// shared/utils/emailValidation.js
const EMAIL_REGEX = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/i

/*
 * shared/hooks/useOnboardingExitGuard.js. The web pushes a history entry and
 * catches "popstate"; the app catches the hardware back button the same way:
 * first step -> ask before leaving, later steps -> previous step.
 */
function useOnboardingExitGuard({ isFirstStep, onPreviousStep, onExit, hasUnsavedProgress = () => true }) {
  const [showExitModal, setShowExitModal] = useState(false)

  const handleStay = useCallback(() => {
    setShowExitModal(false)
  }, [])

  const handleExit = useCallback(() => {
    setShowExitModal(false)
    onExit?.()
  }, [onExit])

  const requestExit = useCallback(() => {
    if (hasUnsavedProgress()) {
      setShowExitModal(true)
      return
    }
    onExit?.()
  }, [hasUnsavedProgress, onExit])

  const handleBack = useCallback(() => {
    if (isFirstStep) {
      requestExit()
      return
    }
    onPreviousStep?.()
  }, [isFirstStep, onPreviousStep, requestExit])

  useEffect(() => {
    const sub = BackHandler.addEventListener("hardwareBackPress", () => {
      if (isFirstStep) {
        requestExit()
        return true
      }
      onPreviousStep?.()
      return true
    })
    return () => sub.remove()
  }, [isFirstStep, onPreviousStep, requestExit])

  return { showExitModal, handleBack, handleStay, handleExit, requestExit }
}

const normalizePhoneDigits = (value) => {
  const digits = String(value || "").replace(/\D/g, "")
  return digits.slice(-10)
}

async function finalizeRestaurantPendingSubmission(navigate, phone, fcmOptions = {}) {
  const { fcmToken, platform } = fcmOptions
  const normalizedPhone = normalizePhoneDigits(phone || "")

  try {
    const userStr = localStore.getItem("restaurant_user")
    if (userStr) {
      const user = JSON.parse(userStr)
      user.status = "pending"
      localStore.setItem("restaurant_user", JSON.stringify(user))
    }
  } catch {}

  if (normalizedPhone) {
    localStore.setItem("restaurant_pendingPhone", normalizedPhone)
  }
  localStore.setItem("restaurant_pendingStatus", "pending")
  localStore.removeItem("restaurant_pendingMessage")

  try {
    syncPendingPartnerFcmQuick("restaurant", normalizedPhone, { fcmToken, platform })
  } catch {}

  if (localStore.getItem("restaurant_accessToken")) {
    try {
      persistModuleFcmToken("restaurant", { fcmToken, platform }).catch(() => {})
    } catch {}
  }

  /*
   * A "both" signup never reaches this function while still "both" — the
   * wizard's own step 3 branch (handleNext) intercepts it, runs steps 4-5
   * inline, and clears the intent itself once the hotel half is submitted
   * too. Getting here with the intent still set to "both" would only happen
   * if that flow was interrupted, so treat it the same as restaurant-only
   * rather than dropping the partner onto a stale hotel prompt.
   */
  clearOnboardingIntent()

  navigate("/food/restaurant/pending-verification", {
    replace: true,
    state: { phone: normalizedPhone },
  })
}

const daysOfWeek = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

const ONBOARDING_STORAGE_KEY = "restaurant_onboarding_data"

const PAN_NUMBER_REGEX = /^[A-Z]{5}[0-9]{4}[A-Z]$/

const GST_NUMBER_REGEX = /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/

const FSSAI_NUMBER_REGEX = /^\d{14}$/

const BANK_ACCOUNT_NUMBER_REGEX = /^\d{9,18}$/

const IFSC_CODE_REGEX = /^[A-Z0-9]{11}$/

const OWNER_NAME_REGEX = /^[A-Za-z ]+$/

const ACCOUNT_HOLDER_NAME_REGEX = /^[A-Za-z ]+$/

const GST_LEGAL_NAME_REGEX = /^[A-Za-z ]+$/

const LOCAL_IMAGE_FILE_ACCEPT = ".jpg,.jpeg,.png,.webp,.heic,.heif"

const GALLERY_IMAGE_ACCEPT =
  ".jpg,.jpeg,.png,.webp,.heic,.heif,image/jpeg,image/png,image/webp,image/heic,image/heif"

let onboardingFileCache = {
  step2: {
    menuImages: [],
    profileImage: null,
  },
  step3: {
    panImage: null,
    gstImage: null,
    fssaiImage: null,
  },
}

const saveFileToDB = async (key, file) => {
  if (!file || !isUploadableFile(file)) return
  try {
    const { uri, name, type, size, width, height } = file
    localStore.setItem(ONBOARDING_FILE_KEY_PREFIX + key, JSON.stringify({ uri, name, type, size, width, height }))
  } catch (err) {
    debugError("Saving picked file failed:", err)
  }
}

const getFileFromDB = async (key) => {
  try {
    const raw = localStore.getItem(ONBOARDING_FILE_KEY_PREFIX + key)
    const file = raw ? JSON.parse(raw) : null
    return isUploadableFile(file) ? file : null
  } catch (err) {
    debugError("Loading picked file failed:", err)
    return null
  }
}

const deleteFileFromDB = async (key) => {
  try {
    localStore.removeItem(ONBOARDING_FILE_KEY_PREFIX + key)
  } catch (err) {
    debugError("Deleting picked file failed:", err)
  }
}

const getUploadableMenuFiles = (menuImages = []) =>
  (Array.isArray(menuImages) ? menuImages : [])
    .filter((img) => isUploadableFile(img))
    .slice(0, 10)

const persistMenuImagesToDB = async (menuImages = []) => {
  const uploadableMenuFiles = getUploadableMenuFiles(menuImages)
  for (let i = 0; i < 10; i++) {
    const file = uploadableMenuFiles[i]
    if (file) {
      await saveFileToDB(`menuImage_${i}`, file)
    } else {
      await deleteFileFromDB(`menuImage_${i}`)
    }
  }
}

const isUploadableFile = (value) =>
  Boolean(value) && typeof value === "object" && typeof value.uri === "string" && value.uri.length > 0 && !value.url

const normalizePincode = (value) => String(value || "").replace(/\D/g, "").slice(0, 6)

const getVerifiedPhoneFromStoredRestaurant = () => {
  try {
    const pending = localStore.getItem("restaurant_pendingPhone")
    if (pending && pending.trim()) {
      return pending.trim()
    }

    const storedUser = localStore.getItem("restaurant_user")
    if (!storedUser) return ""
    const user = JSON.parse(storedUser)
    const candidates = [
      user?.ownerPhone,
      user?.primaryContactNumber,
      user?.phone,
      user?.phoneNumber,
      user?.mobile,
      user?.contactNumber,
      user?.contact?.phone,
      user?.owner?.phone,
      user?.restaurant?.phone,
    ]
    const phone = candidates.find((value) => typeof value === "string" && value.trim())
    return phone ? phone.trim() : ""
  } catch {
    return ""
  }
}

const normalizeEmail = (val) => {
  let email = String(val || "").toLowerCase().trim()
  // Auto-correct common Gmail typos
  email = email.replace(/@(gnail|gamil|gimail|gnil)\.com$/i, "@gmail.com")
  return email
}

const normalizeAccountTypeValue = (value) => {
  const normalized = String(value || "").trim().toLowerCase()
  if (normalized === "saving" || normalized === "savings") return "Saving"
  if (normalized === "current") return "Current"
  return ""
}

const formatNameToCapital = (str) => {
  if (!str) return ""
  return str.split(" ").map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()).join(" ")
}

const normalizeIFSC = (val) => String(val || "").toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 11)

const normalizePAN = (val) => String(val || "").toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 10)

const normalizeGST = (val) => String(val || "").toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 15)

const normalizeBankAcc = (val) => String(val || "").replace(/\D/g, "").slice(0, 18)

const getTodayLocalYMD = () => formatDateToLocalYMD(new Date())

const saveOnboardingToLocalStorage = (step1, step2, step3, currentStep) => {
  try {
    // Persist only stable URL-based values. File/Blob objects are not serializable and
    // restoring metadata-only placeholders breaks preview/upload flows.
    const serializableStep2 = {
      ...step2,
      menuImages: (step2.menuImages || []).filter(
        (img) => !isUploadableFile(img) && (img?.url || (typeof img === "string" && img.trim()))
      ),
      profileImage:
        !isUploadableFile(step2.profileImage) &&
        (step2.profileImage?.url || (typeof step2.profileImage === "string" && step2.profileImage.trim()))
          ? step2.profileImage
          : null,
    }

    const serializableStep3 = {
      ...step3,
      panImage:
        !isUploadableFile(step3.panImage) &&
        (step3.panImage?.url || (typeof step3.panImage === "string" && step3.panImage.trim()))
          ? step3.panImage
          : null,
      gstImage:
        !isUploadableFile(step3.gstImage) &&
        (step3.gstImage?.url || (typeof step3.gstImage === "string" && step3.gstImage.trim()))
          ? step3.gstImage
          : null,
      fssaiImage:
        !isUploadableFile(step3.fssaiImage) &&
        (step3.fssaiImage?.url || (typeof step3.fssaiImage === "string" && step3.fssaiImage.trim()))
          ? step3.fssaiImage
          : null,
    }

    const dataToSave = {
      step1,
      step2: serializableStep2,
      step3: serializableStep3,
      currentStep,
      timestamp: Date.now(),
    }

    const userStr = localStore.getItem("restaurant_user")
    let key = ONBOARDING_STORAGE_KEY
    if (userStr) {
      const user = JSON.parse(userStr)
      const userId = user._id || user.id
      if (userId) key = `restaurant_onboarding_data_${userId}`
    }
    localStore.setItem(key, JSON.stringify(dataToSave))
  } catch (error) {
    debugError("Failed to save onboarding data to localStore:", error)
  }
}

const loadOnboardingFromLocalStorage = () => {
  try {
    const userStr = localStore.getItem("restaurant_user")
    let key = ONBOARDING_STORAGE_KEY
    if (userStr) {
      const user = JSON.parse(userStr)
      const userId = user._id || user.id
      if (userId) key = `restaurant_onboarding_data_${userId}`
    }
    const stored = localStore.getItem(key)
    if (stored) {
      return JSON.parse(stored)
    }
  } catch (error) {
    debugError("Failed to load onboarding data from localStore:", error)
  }
  return null
}

const syncOnboardingFileCache = (step2, step3) => {
  onboardingFileCache = {
    step2: {
      menuImages: (step2?.menuImages || []).filter((img) => isUploadableFile(img)),
      profileImage: isUploadableFile(step2?.profileImage) ? step2.profileImage : null,
    },
    step3: {
      panImage: isUploadableFile(step3?.panImage) ? step3.panImage : null,
      gstImage: isUploadableFile(step3?.gstImage) ? step3.gstImage : null,
      fssaiImage: isUploadableFile(step3?.fssaiImage) ? step3.fssaiImage : null,
    },
  }
}

const clearOnboardingFileCache = () => {
  onboardingFileCache = {
    step2: {
      menuImages: [],
      profileImage: null,
    },
    step3: {
      panImage: null,
      gstImage: null,
      fssaiImage: null,
    },
  }
}

const stringToTime = (timeString) => {
  const normalized = normalizeTimeValue(timeString)
  if (!normalized || !normalized.includes(":")) {
    return null
  }
  const [hours, minutes] = normalized.split(":").map(Number)
  return new Date(2000, 0, 1, hours || 0, minutes || 0)
}

const timeToString = (date) => {
  if (!date) return ""
  const hours = date.getHours().toString().padStart(2, "0")
  const minutes = date.getMinutes().toString().padStart(2, "0")
  return `${hours}:${minutes}`
}

const normalizeTimeValue = (value) => {
  if (!value) return ""

  const raw = String(value).trim()
  if (!raw) return ""

  const to24Hour = (h, m, period) => {
    let hours = Number(h)
    const minutes = Number(m)
    if (!Number.isFinite(hours) || !Number.isFinite(minutes)) return ""
    if (minutes < 0 || minutes > 59) return ""
    const p = String(period || "").toUpperCase()
    if (p === "AM") {
      if (hours === 12) hours = 0
    } else if (p === "PM") {
      if (hours !== 12) hours += 12
    }
    if (hours < 0 || hours > 23) return ""
    return `${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}`
  }

  // Already in HH:mm format
  if (/^\d{2}:\d{2}$/.test(raw)) {
    const [h, m] = raw.split(":").map(Number)
    if (!Number.isFinite(h) || !Number.isFinite(m) || h < 0 || h > 23 || m < 0 || m > 59) {
      return ""
    }
    return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}`
  }

  // Handle H:mm by zero-padding hour
  if (/^\d{1}:\d{2}$/.test(raw)) {
    const [h, m] = raw.split(":")
    return to24Hour(h, m, "")
  }

  // Handle 12-hour format (e.g. "10:00 AM", "9:30pm")
  const ampm = raw.match(/^(\d{1,2}):(\d{2})\s*([AaPp][Mm])$/)
  if (ampm) {
    return to24Hour(ampm[1], ampm[2], ampm[3])
  }

  // Fallback for ISO / Date-like strings
  const parsed = new Date(raw)
  if (!Number.isNaN(parsed.getTime())) {
    return timeToString(parsed)
  }

  return ""
}

const timeStringToMinutes = (value) => {
  const normalized = normalizeTimeValue(value)
  if (!normalized || !/^\d{2}:\d{2}$/.test(normalized)) return null
  const [hours, minutes] = normalized.split(":").map(Number)
  if (!Number.isFinite(hours) || !Number.isFinite(minutes)) return null
  if (hours < 0 || hours > 23 || minutes < 0 || minutes > 59) return null
  return hours * 60 + minutes
}

const formatTime12Hour = (timeStr) => {
  if (!timeStr || typeof timeStr !== "string" || !timeStr.includes(":")) return "--:-- --"
  const [h, m] = timeStr.split(":").map(Number)
  if (Number.isNaN(h) || Number.isNaN(m)) return timeStr
  const period = h >= 12 ? "PM" : "AM"
  const hour = h % 12 || 12
  return `${hour}:${String(m).padStart(2, "0")} ${period}`
}

const formatDateToLocalYMD = (date) => {
  if (!date || Number.isNaN(date.getTime?.())) return ""
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, "0")
  const day = String(date.getDate()).padStart(2, "0")
  return `${year}-${month}-${day}`
}

const parseLocalYMDDate = (value) => {
  if (!value || typeof value !== "string") return undefined
  const parts = value.split("-").map(Number)
  if (parts.length !== 3 || parts.some(Number.isNaN)) return undefined
  const [year, month, day] = parts
  return new Date(year, month - 1, day)
}

export function useOnboarding() {
  const companyName = useCompanyName()
  const navigate = useNavigate()
  const [searchParams] = useSearchParams()
  const [step, setStep] = useState(1)
  const scrollRef = useRef(null)
  const scrollToTop = () => scrollRef.current?.scrollTo?.({ y: 0, animated: false })
  const [loading, setLoading] = useState(false)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState("")
  const [isLoggingOut, setIsLoggingOut] = useState(false)


  const handleExitAnyway = useCallback(() => {
    void (async () => {
      try {
        clearOnboardingFcmLocalState()
        clearOnboardingFromLocalStorage()
        clearOnboardingFileCache()
        await clearAllFilesFromDB()

        const hasSession = Boolean(localStore.getItem("restaurant_refreshToken"))
        if (hasSession) {
          await restaurantAPI.logout().catch(() => {})
        }
        clearModuleAuth("restaurant")
        clearAuthData()
        events.emit("restaurantAuthChanged")
      } catch (e) {
        debugError("Error clearing onboarding data on exit:", e)
      }
      navigate("/food/restaurant/login", { replace: true })
    })()
  }, [navigate])

  const goToPreviousOnboardingStep = useCallback(() => {
    setStep((currentStep) => Math.max(1, currentStep - 1))
    scrollToTop()
  }, [])

  const handleLogout = async () => {
    if (isLoggingOut) return
    setIsLoggingOut(true)
    try {
      await restaurantAPI.logout()
      clearModuleAuth("restaurant")
      clearAuthData()
      // Clear onboarding data and files
      clearOnboardingFromLocalStorage()
      await clearAllFilesFromDB()
      
      events.emit("restaurantAuthChanged")
      navigate("/food/restaurant/login", { replace: true })
    } catch (error) {
      debugError("Logout failed:", error)
      clearModuleAuth("restaurant")
      navigate("/food/restaurant/login", { replace: true })
    } finally {
      setIsLoggingOut(false)
    }
  }

  const [verifiedPhoneNumber, setVerifiedPhoneNumber] = useState(() => getVerifiedPhoneFromStoredRestaurant())
  const [keyboardInset, setKeyboardInset] = useState(0)
  const [isEditing, setIsEditing] = useState(true)
  const [hasExistingRestaurantProfile, setHasExistingRestaurantProfile] = useState(false)
  const [isFssaiCalendarOpen, setIsFssaiCalendarOpen] = useState(false)
  const [zones, setZones] = useState([])
  const [zonesLoading, setZonesLoading] = useState(false)
  const [isOnboardingHydrated, setIsOnboardingHydrated] = useState(false)
  const isHydratingRef = useRef(false)

  const [step1, setStep1] = useState({
    restaurantName: "",
    pureVegRestaurant: null,
    ownerName: "",
    ownerEmail: "",
    ownerPhone: "",
    primaryContactNumber: "",
    zoneId: "",
    location: {
      formattedAddress: "",
      addressLine1: "",
      addressLine2: "",
      area: "",
      city: "",
      state: "",
      pincode: "",
      landmark: "",
      latitude: "",
      longitude: "",
    },
  })

  const [step2, setStep2] = useState({
    menuImages: [],
    profileImage: null,
    cuisines: [],
    estimatedDeliveryTime: "",
    openingTime: "",
    closingTime: "",
    openDays: [],
    isTakeawayEnabled: false,
    isTakeawayCodEnabled: false,
  })

  const [step3, setStep3] = useState({
    panNumber: "",
    nameOnPan: "",
    panImage: null,
    gstRegistered: false,
    gstNumber: "",
    gstLegalName: "",
    gstAddress: "",
    gstImage: null,
    fssaiNumber: "",
    fssaiExpiry: "",
    fssaiImage: null,
    accountNumber: "",
    confirmAccountNumber: "",
    ifscCode: "",
    accountHolderName: "",
    accountType: "",
  })

  const totalSteps = 3

  const hasStep1UnsavedProgress = useCallback(
    () => hasRestaurantStep1Progress(step1),
    [step1],
  )

  const {
    showExitModal,
    handleBack,
    handleStay,
    handleExit,
    requestExit,
  } = useOnboardingExitGuard({
    isFirstStep: step === 1,
    onPreviousStep: goToPreviousOnboardingStep,
    onExit: handleExitAnyway,
    hasUnsavedProgress: hasStep1UnsavedProgress,
  })

  const previewUrlCacheRef = useRef(new Map())
  const locationSearchInputRef = useRef(null)
  const locationSearchContainerRef = useRef(null)
  const placesAutocompleteRef = useRef(null)
  const mapsScriptLoadedRef = useRef(false)
  const menuImagesInputRef = useRef(null)
  const profileImageInputRef = useRef(null)
  const panImageInputRef = useRef(null)
  const gstImageInputRef = useRef(null)
  const fssaiImageInputRef = useRef(null)
  const [sourcePicker, setSourcePicker] = useState({
    isOpen: false,
    title: "",
    onSelectFile: null,
    fileNamePrefix: "camera-image",
    fallbackInputRef: null,
  })

  // Manual search states for fallback
  const [locationSearchValue, setLocationSearchValue] = useState("")
  const [locationSuggestions, setLocationSuggestions] = useState([])
  const [isSearchingLocation, setIsSearchingLocation] = useState(false)
  const [isLocationSearchFocused, setIsLocationSearchFocused] = useState(false)

  const getPreviewImageUrl = (value) => {
    if (!value) return null
    if (typeof value === "string") return value
    if (value?.url && typeof value.url === "string") return value.url

    if (isUploadableFile(value)) {
      const cache = previewUrlCacheRef.current
      const cached = cache.get(value)
      if (cached) return cached
      try {
        const objectUrl = (value?.uri || "")
        cache.set(value, objectUrl)
        return objectUrl
      } catch {
        return null
      }
    }

    return null
  }

  const openImageSourcePicker = ({ title, onSelectFile, fileNamePrefix, fallbackInputRef }) => {
    setSourcePicker({
      isOpen: true,
      title: title || "Select image source",
      onSelectFile,
      fileNamePrefix: fileNamePrefix || "camera-image",
      fallbackInputRef: fallbackInputRef || null,
    })
  }

  const closeImageSourcePicker = () => {
    setSourcePicker((prev) => ({ ...prev, isOpen: false }))
  }

  const handleMenuImagesSelected = (files = []) => {
    if (!files.length) return
    const nextMenuImages = [...(step2.menuImages || []), ...files]
    setStep2((prev) => ({
      ...prev,
      menuImages: nextMenuImages,
    }))
    void persistMenuImagesToDB(nextMenuImages)
  }



  const handleProfileImageSelected = (file) => {
    if (!file) return
    setStep2((prev) => ({
      ...prev,
      profileImage: file,
    }))
    void saveFileToDB("profileImage", file)
  }

  const handlePanImageSelected = (file) => {
    if (!file) return
    setStep3((prev) => ({ ...prev, panImage: file }))
  }

  const handleGstImageSelected = (file) => {
    if (!file) return
    setStep3((prev) => ({ ...prev, gstImage: file }))
  }

  const handleFssaiImageSelected = (file) => {
    if (!file) return
    setStep3((prev) => ({ ...prev, fssaiImage: file }))
  }

  const isPersistedImageValue = (value) =>
    !isUploadableFile(value) &&
    ((typeof value === "string" && value.trim()) ||
      (value?.url && typeof value.url === "string"))

  const getPersistedImagePayload = (value) => {
    if (typeof value === "string" && value.trim()) {
      return { url: value.trim(), publicId: null }
    }

    if (value?.url && typeof value.url === "string" && value.url.trim()) {
      return {
        url: value.url.trim(),
        publicId: value.publicId || null,
      }
    }

    return null
  }

  const toPersistedMenuImagesPayload = (menuImages = []) =>
    (Array.isArray(menuImages) ? menuImages : [])
      .filter((img) => isPersistedImageValue(img))
      .map((img) =>
        typeof img === "string"
          ? img
          : {
              url: img.url,
              publicId: img.publicId || null,
            },
      )

  const handleRemoveMenuImage = async (indexToRemove) => {
    const currentMenuImages = step2.menuImages || []
    const imageToRemove = currentMenuImages[indexToRemove]
    const nextMenuImages = currentMenuImages.filter((_, i) => i !== indexToRemove)

    setStep2((prev) => ({
      ...prev,
      menuImages: nextMenuImages,
    }))
    await persistMenuImagesToDB(nextMenuImages)

    if (!isPersistedImageValue(imageToRemove)) {
      return
    }

    try {
      await restaurantAPI.updateProfile({
        menuImages: toPersistedMenuImagesPayload(nextMenuImages),
      })
    } catch (error) {
      setStep2((prev) => ({
        ...prev,
        menuImages: currentMenuImages,
      }))
      await persistMenuImagesToDB(currentMenuImages)
      setError(error?.response?.data?.message || "Failed to remove menu image")
    }
  }

  const handleRemoveProfileImage = async () => {
    const currentProfileImage = step2.profileImage
    setStep2((prev) => ({
      ...prev,
      profileImage: null,
    }))

    if (!isPersistedImageValue(currentProfileImage)) {
      return
    }

    try {
      await restaurantAPI.updateProfile({ profileImage: "" })
    } catch (error) {
      setStep2((prev) => ({
        ...prev,
        profileImage: currentProfileImage,
      }))
      setError(error?.response?.data?.message || "Failed to remove profile image")
    }
  }

  const resolveImageForProfileUpdate = async (value, folder) => {
    if (!value) return null

    if (isUploadableFile(value)) {
      const uploaded = await handleUpload(value, folder)
      return uploaded || null
    }

    return getPersistedImagePayload(value)
  }


  const resolveMenuImagesForProfileUpdate = async (menuImages = []) => {
    const items = Array.isArray(menuImages) ? menuImages : []
    const resolved = await Promise.all(
      items.map(async (image) => {
        if (isUploadableFile(image)) {
          return handleUpload(image, "food/restaurants/menu")
        }

        return getPersistedImagePayload(image)
      }),
    )

    return resolved.filter((image) => image?.url)
  }


  // Load from localStore on mount and check URL parameter
  useEffect(() => {
    if (isOnboardingHydrated || isHydratingRef.current) return;
    isHydratingRef.current = true;
    
    // Check if step is specified in URL (from OTP login redirect)
    const stepParam = searchParams.get("step")

    const loadData = async () => {
      try {
        setLoading(true);
        // Fail-safe: Force loading off after 7 seconds if something hangs on mobile
        const failSafeTimer = setTimeout(() => {
          if (!isOnboardingHydrated) {
            debugWarn("Hydration fail-safe triggered")
            setIsOnboardingHydrated(true)
            setLoading(false)
          }
        }, 7000)

        const currentPhone = getVerifiedPhoneFromStoredRestaurant()
        let localData = loadOnboardingFromLocalStorage()
        
        // 1. First fetch API data to have the latest backend state
        let apiData = null;
        try {
          // Only fetch if we have a token (existing user session)
          if (getModuleToken("restaurant")) {
            const res = await restaurantAPI.getCurrentRestaurant()
            apiData = res?.data?.data?.restaurant || res?.data?.restaurant
          }
        } catch (err) {
          debugError("API fetch skipped/failed:", err)
        }

        // 2. Hydrate from API if exists
        if (apiData) {
          setHasExistingRestaurantProfile(true)
          const onboarding = apiData.onboarding || {}
          const s1 = onboarding.step1 || {}
          const s2 = onboarding.step2 || {}
          const s3 = onboarding.step3 || {}
          const loc = s1.location || apiData.location || {}
          const pay = s3.bank || apiData.bankAccount || {}

          setStep1(prev => ({
            ...prev,
            restaurantName: s1.restaurantName || apiData.name || apiData.restaurantName || "",
            pureVegRestaurant: typeof s1.pureVegRestaurant === 'boolean' ? s1.pureVegRestaurant : (apiData.pureVegRestaurant ?? null),
            ownerName: s1.ownerName || apiData.ownerName || "",
            ownerEmail: s1.ownerEmail || apiData.ownerEmail || apiData.email || "",
            ownerPhone: s1.ownerPhone || apiData.ownerPhone || apiData.phone || "",
            primaryContactNumber: s1.primaryContactNumber || apiData.primaryContactNumber || "",
            zoneId: s1.zoneId || apiData.zoneId || "",
            location: {
              ...prev.location,
              formattedAddress: loc.formattedAddress || loc.address || apiData.address || "",
              addressLine1: loc.addressLine1 || "",
              addressLine2: loc.addressLine2 || "",
              area: loc.area || apiData.area || "",
              city: loc.city || apiData.city || "",
              state: loc.state || apiData.state || "",
              pincode: loc.pincode || apiData.pincode || "",
              landmark: loc.landmark || "",
              latitude: loc.latitude || "",
              longitude: loc.longitude || "",
            }
          }))

          setStep2(prev => ({
            ...prev,
            menuImages: s2.menuImageUrls || apiData.menuImages || [],
            profileImage: s2.profileImageUrl || apiData.profileImage || null,
            cuisines: s2.cuisines || apiData.cuisines || [],
            estimatedDeliveryTime: s2.estimatedDeliveryTime || apiData.estimatedDeliveryTime || "",
            openingTime: normalizeTimeValue(s2.openingTime || apiData.openingTime),
            closingTime: normalizeTimeValue(s2.closingTime || apiData.closingTime),
            openDays: s2.openDays || apiData.openDays || [],
            isTakeawayEnabled: s2.isTakeawayEnabled || apiData.takeawaySettings?.isEnabled || false,
          }))

          setStep3(prev => ({
            ...prev,
            panNumber: s3.pan?.panNumber || apiData.panNumber || "",
            nameOnPan: s3.pan?.nameOnPan || apiData.nameOnPan || "",
            panImage: s3.pan?.image || apiData.panImage || null,
            gstRegistered: s3.gst?.isRegistered ?? apiData.gstRegistered ?? false,
            gstNumber: s3.gst?.gstNumber || apiData.gstNumber || "",
            gstLegalName: s3.gst?.legalName || apiData.gstLegalName || "",
            gstAddress: s3.gst?.address || apiData.gstAddress || "",
            gstImage: s3.gst?.image || apiData.gstImage || null,
            fssaiNumber: s3.fssai?.registrationNumber || apiData.fssaiNumber || "",
            fssaiExpiry: s3.fssai?.expiryDate ? String(s3.fssai.expiryDate).split('T')[0] : (apiData.fssaiExpiry ? String(apiData.fssaiExpiry).split('T')[0] : ""),
            fssaiImage: s3.fssai?.image || apiData.fssaiImage || null,
            accountNumber: pay.accountNumber || apiData.accountNumber || "",
            confirmAccountNumber: pay.accountNumber || apiData.accountNumber || "",
            ifscCode: normalizeIFSC(pay.ifscCode || apiData.ifscCode),
            accountHolderName: pay.accountHolderName || apiData.accountHolderName || "",
            accountType: normalizeAccountTypeValue(pay.accountType || apiData.accountType),
          }))
        }

        // 3. APPLY LOCAL OVERRIDES (The "Persistence" fix)
        // If localStore has unsaved changes for this user, apply them over the API/Initial state.
        if (localData) {
          const savedPhone = normalizePhoneDigits(localData.step1?.ownerPhone || "")
          const normalizedCurrent = normalizePhoneDigits(currentPhone)
          
          // Only use local data if it belongs to the same user
          if (savedPhone && normalizedCurrent && savedPhone === normalizedCurrent) {
            debugLog("? Matching local session found. Resuming with unsaved changes.")
            
            if (localData.step1) {
              setStep1(prev => ({ ...prev, ...localData.step1, location: { ...prev.location, ...localData.step1.location } }));
            }
            if (localData.step2) {
              // Note: Files/Images must be re-hydrated from IndexedDB (handled below)
              setStep2(prev => ({ 
                ...prev, 
                ...localData.step2,
                openingTime: normalizeTimeValue(localData.step2.openingTime),
                closingTime: normalizeTimeValue(localData.step2.closingTime),
              }));
            }
            if (localData.step3) {
              setStep3(prev => ({ ...prev, ...localData.step3 }));
            }

            // Restore Step
            if (localData.currentStep && !stepParam) {
              setStep(Math.min(3, Math.max(1, Number(localData.currentStep))))
            }
          } else if (savedPhone && normalizedCurrent && savedPhone !== normalizedCurrent) {
             debugLog("? Phone mismatch, data belongs to different user. Clearing local cache.")
             localData = null; // Bypass IndexedDB check for mismatched user
             clearOnboardingFromLocalStorage()
             clearAllFilesFromDB().catch(e => debugError("Cleanup failed:", e))
          }
        }

        // 4. Finally re-hydrate heavy files from IndexedDB if they exist 
        // (IndexedDB is reliable for large files which don't fit in localStore)
        // Optimization: Only attempt this if we have existing local or API data to restore.
        if (localData || apiData) {
          debugLog("? Checking IndexedDB for saved files...")
          const [prof, pan, gst, fs] = await Promise.all([
            getFileFromDB("profileImage"),
            getFileFromDB("panImage"),
            getFileFromDB("gstImage"),
            getFileFromDB("fssaiImage"),
          ]);

          if (prof) setStep2(p => ({ ...p, profileImage: prof }));
          if (pan) setStep3(p => ({ ...p, panImage: pan }));
          if (gst) setStep3(p => ({ ...p, gstImage: gst }));
          if (fs) setStep3(p => ({ ...p, fssaiImage: fs }));

          // Parallelize menu images hydration
          const menuPromises = Array.from({ length: 10 }, (_, i) => getFileFromDB(`menuImage_${i}`))
          const restoredMenuImages = (await Promise.all(menuPromises)).filter(Boolean)
          
          if (restoredMenuImages.length) {
            setStep2(p => ({ ...p, menuImages: [...p.menuImages.filter(im => !isUploadableFile(im)), ...restoredMenuImages] }));
          }
        }

        // If step is explicitly in URL, use it
        if (stepParam) {
          const s = parseInt(stepParam, 10);
          if (s >= 1 && s <= 3) setStep(s);
        }

        clearTimeout(failSafeTimer)
      } catch (err) {
        debugError("Onboarding hydration failed:", err)
      } finally {
        setIsOnboardingHydrated(true)
        setLoading(false)
        isHydratingRef.current = false
      }
    }

    loadData()
  }, [])

  useEffect(() => {
    if (!verifiedPhoneNumber) return
    setStep1((prev) => ({
      ...prev,
      ownerPhone: verifiedPhoneNumber,
    }))
  }, [verifiedPhoneNumber])

  // Save to localStore whenever step data changes
  useEffect(() => {
    if (!isOnboardingHydrated) return
    saveOnboardingToLocalStorage(step1, step2, step3, step)
    
    // Save images to IndexedDB
    const saveFiles = async () => {
      if (step2.profileImage && isUploadableFile(step2.profileImage)) {
        await saveFileToDB("profileImage", step2.profileImage)
      } else if (!step2.profileImage) {
        await deleteFileFromDB("profileImage")
      }
      if (step3.panImage && isUploadableFile(step3.panImage)) {
        await saveFileToDB("panImage", step3.panImage)
      }
      if (step3.gstImage && isUploadableFile(step3.gstImage)) {
        await saveFileToDB("gstImage", step3.gstImage)
      }
      if (step3.fssaiImage && isUploadableFile(step3.fssaiImage)) {
        await saveFileToDB("fssaiImage", step3.fssaiImage)
      }
      
      await persistMenuImagesToDB(step2.menuImages || [])
    }
    saveFiles()
  }, [isOnboardingHydrated, step1, step2, step3, step])

  useEffect(() => {
    syncOnboardingFileCache(step2, step3)
  }, [step2, step3])

  useEffect(() => {
    return () => {
      previewUrlCacheRef.current.forEach((url) => {
        try {
          /* (web: URL.revokeObjectURL) */
        } catch {
          // Ignore revoke errors
        }
      })
      previewUrlCacheRef.current.clear()
    }
  }, [])

  // REMOVED redundancy: The hydration is now handled in a single loadData effect above 
  // to avoid race conditions between localStore and API data.

  const handleUpload = async (file, folder) => {
    try {
      if (!isUploadableFile(file)) {
        throw new Error("Invalid image file")
      }

      const response = await uploadAPI.uploadMedia(file, { folder })
      const uploadedImage = response?.data?.data

      if (!uploadedImage?.url) {
        throw new Error("Uploaded image URL was not returned")
      }

      return uploadedImage
    } catch (err) {
      // Provide more informative error message for upload failures
      const errorMsg = err?.response?.data?.message || err?.response?.data?.error || err?.message || "Failed to upload image"
      debugError("Upload error:", errorMsg, err)
      throw new Error(`Image upload failed: ${errorMsg}`)
    }
  }


  // Validation functions for each step
  const validateStep1 = () => {
    const errors = []

    if (!step1.restaurantName?.trim()) {
      errors.push("Restaurant name is required")
    } else if (/[\/-]/.test(step1.restaurantName)) {
      errors.push("Restaurant name cannot contain slashes (/) or hyphens (-)")
    }
    if (typeof step1.pureVegRestaurant !== "boolean") {
      errors.push("Please select whether your restaurant is pure veg")
    }
    if (!step1.ownerName?.trim()) {
      errors.push("Owner name is required")
    } else if (!OWNER_NAME_REGEX.test(step1.ownerName.trim())) {
      errors.push("Owner name must contain only letters")
    }
    if (!step1.ownerEmail?.trim()) {
      errors.push("Owner email is required")
    } else if (!EMAIL_REGEX.test(step1.ownerEmail.trim())) {
      errors.push("Please enter a valid email address")
    } else if (step1.ownerEmail.toLowerCase().includes("@gnail.com") || step1.ownerEmail.toLowerCase().includes("@gnil.com")) {
      errors.push("Invalid email domain. Did you mean '@gmail.com'?")
    }
    if (!step1.ownerPhone?.trim()) {
      errors.push("Owner phone number is required")
    } else if (!/^\d{10}$/.test(normalizePhoneDigits(step1.ownerPhone))) {
      errors.push("Owner phone number must be exactly 10 digits")
    }
    if (!step1.primaryContactNumber?.trim()) {
      errors.push("Primary contact number is required")
    } else if (!/^\d{10}$/.test(normalizePhoneDigits(step1.primaryContactNumber))) {
       errors.push("Primary contact number must be exactly 10 digits")
    }
    if (!step1.zoneId?.trim()) {
      errors.push("Service zone is required")
    }
    if (!step1.location?.area?.trim()) {
      errors.push("Area/Sector/Locality is required")
    }
    if (!step1.location?.city?.trim()) {
      errors.push("City is required")
    }
    if (!step1.location?.pincode?.trim()) {
      errors.push("Pincode is required")
    } else if (!/^\d{6}$/.test(normalizePincode(step1.location.pincode))) {
      errors.push("Pincode must be exactly 6 digits")
    }

    return errors
  }

  const validateStep2 = () => {
    const errors = []

    // Check menu images - must have at least one File or existing URL
    const hasMenuImages = step2.menuImages && step2.menuImages.length > 0
    if (!hasMenuImages) {
      errors.push("At least one menu image is required")
    } else {
      // Verify that menu images are either File objects or have valid URLs
      const validMenuImages = step2.menuImages.filter(img => {
        if (isUploadableFile(img)) return true
        if (img?.url && typeof img.url === 'string') return true
        if (typeof img === 'string' && img.trim()) return true
        return false
      })
      if (validMenuImages.length === 0) {
        errors.push("Please upload at least one valid menu image")
      }
    }

    // Check profile image - must be a File or existing URL
    if (!step2.profileImage) {
      errors.push("Restaurant profile image is required")
    } else {
      // Verify profile image is either a File or has a valid URL
      const isValidProfileImage =
        isUploadableFile(step2.profileImage) ||
        (step2.profileImage?.url && typeof step2.profileImage.url === 'string') ||
        (typeof step2.profileImage === 'string' && step2.profileImage.trim())
      if (!isValidProfileImage) {
        errors.push("Please upload a valid restaurant profile image")
      }
    }

    if (!step2.openingTime?.trim()) {
      errors.push("Opening time is required")
    }
    if (!step2.closingTime?.trim()) {
      errors.push("Closing time is required")
    }
    const openingMinutes = timeStringToMinutes(step2.openingTime)
    const closingMinutes = timeStringToMinutes(step2.closingTime)
    if (openingMinutes !== null && closingMinutes !== null) {
      if (openingMinutes === closingMinutes) {
        errors.push("Opening time and closing time cannot be same")
      } else if (closingMinutes < openingMinutes) {
        errors.push("Closing time cannot be less than opening time")
      }
    }
    if (!step2.openDays || step2.openDays.length === 0) {
      errors.push("Please select at least one open day")
    }
    if (!step2.estimatedDeliveryTime?.trim()) {
      errors.push("Estimated delivery time is required")
    }

    return errors
  }

  const validateStep3 = () => {
    const errors = []

    if (!step3.panNumber?.trim()) {
      errors.push("PAN number is required")
    } else if (!PAN_NUMBER_REGEX.test(step3.panNumber.trim().toUpperCase())) {
      errors.push("PAN number must be valid (e.g., ABCDE1234F)")
    }
    if (!step3.nameOnPan?.trim()) {
      errors.push("Name on PAN is required")
    }
    // Validate PAN image - must be a File or existing URL
    if (!step3.panImage) {
      errors.push("PAN image is required")
    } else {
      const isValidPanImage =
        isUploadableFile(step3.panImage) ||
        (step3.panImage?.url && typeof step3.panImage.url === 'string') ||
        (typeof step3.panImage === 'string' && step3.panImage.trim())
      if (!isValidPanImage) {
        errors.push("Please upload a valid PAN image")
      }
    }

    if (!step3.fssaiNumber?.trim()) {
      errors.push("FSSAI number is required")
    } else if (!FSSAI_NUMBER_REGEX.test(step3.fssaiNumber.trim())) {
      errors.push("FSSAI number must contain exactly 14 digits")
    }
    if (!step3.fssaiExpiry?.trim()) {
      errors.push("FSSAI expiry date is required")
    } else if (step3.fssaiExpiry < getTodayLocalYMD()) {
      errors.push("FSSAI expiry date cannot be in the past")
    }
    // Validate FSSAI image - must be a File or existing URL
    if (!step3.fssaiImage) {
      errors.push("FSSAI image is required")
    } else {
      const isValidFssaiImage =
        isUploadableFile(step3.fssaiImage) ||
        (step3.fssaiImage?.url && typeof step3.fssaiImage.url === 'string') ||
        (typeof step3.fssaiImage === 'string' && step3.fssaiImage.trim())
      if (!isValidFssaiImage) {
        errors.push("Please upload a valid FSSAI image")
      }
    }

    // Validate GST details if GST registered
    if (step3.gstRegistered) {
      if (!step3.gstNumber?.trim()) {
        errors.push("GST number is required when GST registered")
      } else if (!GST_NUMBER_REGEX.test(step3.gstNumber.trim().toUpperCase())) {
        errors.push("GST number must be a valid 15-character GSTIN")
      }
      if (!step3.gstLegalName?.trim()) {
        errors.push("GST legal name is required when GST registered")
      } else if (!GST_LEGAL_NAME_REGEX.test(step3.gstLegalName.trim())) {
        errors.push("GST legal name must contain only letters")
      }
      if (!step3.gstAddress?.trim()) {
        errors.push("GST registered address is required when GST registered")
      }
      // Validate GST image if GST registered
      if (!step3.gstImage) {
        errors.push("GST image is required when GST registered")
      } else {
        const isValidGstImage =
          isUploadableFile(step3.gstImage) ||
          (step3.gstImage?.url && typeof step3.gstImage.url === 'string') ||
          (typeof step3.gstImage === 'string' && step3.gstImage.trim())
        if (!isValidGstImage) {
          errors.push("Please upload a valid GST image")
        }
      }
    }

    if (!step3.accountNumber?.trim()) {
      errors.push("Account number is required")
    } else if (!BANK_ACCOUNT_NUMBER_REGEX.test(step3.accountNumber.trim())) {
      errors.push("Account number must contain 9 to 18 digits only")
    }
    if (!step3.confirmAccountNumber?.trim()) {
      errors.push("Please confirm your account number")
    } else if (!BANK_ACCOUNT_NUMBER_REGEX.test(step3.confirmAccountNumber.trim())) {
      errors.push("Confirm account number must contain 9 to 18 digits only")
    }
    if (step3.accountNumber && step3.confirmAccountNumber && step3.accountNumber !== step3.confirmAccountNumber) {
      errors.push("Account number and confirmation do not match")
    }
    if (!step3.ifscCode?.trim()) {
      errors.push("IFSC code is required")
    } else if (!IFSC_CODE_REGEX.test(step3.ifscCode.trim().toUpperCase())) {
      errors.push("IFSC code must contain exactly 11 alphanumeric characters")
    }
    if (!step3.accountHolderName?.trim()) {
      errors.push("Account holder name is required")
    } else if (!ACCOUNT_HOLDER_NAME_REGEX.test(step3.accountHolderName.trim())) {
      errors.push("Account holder name must contain only letters")
    }
    if (!step3.accountType?.trim()) {
      errors.push("Account type is required")
    } else if (!["Saving", "Current"].includes(step3.accountType.trim())) {
      errors.push("Account type must be either Saving or Current")
    }

    return errors
  }

  const handleNext = async () => {
    setError("")

    // Validate current step before proceeding
    let validationErrors = []
    if (step === 1) {
      validationErrors = validateStep1()
    } else if (step === 2) {
      validationErrors = validateStep2()
    } else if (step === 3) {
      validationErrors = validateStep3()
    }

    if (validationErrors.length > 0) {
      setError(validationErrors[0])
      toast.error(validationErrors[0])
      debugLog('? Validation failed:', validationErrors)
      return
    }

    setSaving(true)
    try {
      if (step === 1) {
        setStep(2)
        scrollToTop()
      } else if (step === 2) {
        setStep(3)
        scrollToTop()
      } else if (step === 3) {
        const { fcmToken, platform } = await collectFcmTokenForSignup("restaurant")

        if (hasExistingRestaurantProfile) {
          const [
            menuImagesPayload,
            profileImagePayload,
            panImagePayload,
            gstImagePayload,
            fssaiImagePayload,
          ] = await Promise.all([
            resolveMenuImagesForProfileUpdate(step2.menuImages || []),
            resolveImageForProfileUpdate(step2.profileImage, "food/restaurants/profile"),
            resolveImageForProfileUpdate(step3.panImage, "food/restaurants/pan"),
            step3.gstRegistered
              ? resolveImageForProfileUpdate(step3.gstImage, "food/restaurants/gst")
              : Promise.resolve(null),
            resolveImageForProfileUpdate(step3.fssaiImage, "food/restaurants/fssai"),
          ])

          const updatePayload = {
            restaurantName: step1.restaurantName || "",
            pureVegRestaurant: step1.pureVegRestaurant === true,
            ownerName: step1.ownerName || "",
            ownerEmail: (step1.ownerEmail || "").trim(),
            ownerPhone: normalizePhoneDigits(step1.ownerPhone),
            primaryContactNumber: normalizePhoneDigits(step1.primaryContactNumber),
            zoneId: step1.zoneId || "",
            location: {
              formattedAddress: step1.location?.formattedAddress || "",
              addressLine1: step1.location?.addressLine1 || "",
              addressLine2: step1.location?.addressLine2 || "",
              area: step1.location?.area || "",
              city: step1.location?.city || "",
              state: step1.location?.state || "",
              pincode: step1.location?.pincode || "",
              landmark: step1.location?.landmark || "",
              latitude: step1.location?.latitude || "",
              longitude: step1.location?.longitude || "",
            },
            cuisines: Array.isArray(step2.cuisines) ? step2.cuisines : [],
            estimatedDeliveryTime: (step2.estimatedDeliveryTime || "").trim(),
            openingTime: normalizeTimeValue(step2.openingTime) || "",
            closingTime: normalizeTimeValue(step2.closingTime) || "",
            openDays: Array.isArray(step2.openDays) ? step2.openDays : [],
            menuImages: menuImagesPayload,
            profileImage: profileImagePayload || "",
            panNumber: step3.panNumber || "",
            nameOnPan: step3.nameOnPan || "",
            panImage: panImagePayload || "",
            gstRegistered: Boolean(step3.gstRegistered),
            gstNumber: step3.gstRegistered ? step3.gstNumber || "" : "",
            gstLegalName: step3.gstRegistered ? step3.gstLegalName || "" : "",
            gstAddress: step3.gstRegistered ? step3.gstAddress || "" : "",
            gstImage: step3.gstRegistered ? (gstImagePayload || "") : "",
            fssaiNumber: step3.fssaiNumber || "",
            fssaiExpiry: step3.fssaiExpiry || "",
            fssaiImage: fssaiImagePayload || "",
            accountNumber: step3.accountNumber || "",
            ifscCode: (step3.ifscCode || "").toUpperCase(),
            accountHolderName: step3.accountHolderName || "",
            accountType: step3.accountType || "",
            isTakeawayEnabled: step2.isTakeawayEnabled === true,
            isTakeawayCodEnabled: step2.isTakeawayCodEnabled === true,
          }

          if (fcmToken) {
            updatePayload.fcmToken = fcmToken
            updatePayload.platform = platform
          }

          await restaurantAPI.updateProfile(updatePayload)

          clearOnboardingFromLocalStorage()
          clearOnboardingFileCache()
          await clearAllFilesFromDB()

          toast.success("Registration submitted. Awaiting admin approval.", { duration: 4000 })
          await finalizeRestaurantPendingSubmission(navigate, step1.ownerPhone, { fcmToken, platform })
          return
        }

        // Final submit: create restaurant in DB using backend multipart endpoint.
        const formData = new FormData()

        // Step 1
        formData.append("restaurantName", step1.restaurantName || "")
        formData.append(
          "pureVegRestaurant",
          step1.pureVegRestaurant === true ? "true" : "false",
        )
        formData.append("ownerName", step1.ownerName || "")
        formData.append("ownerEmail", (step1.ownerEmail || "").trim())
        formData.append("ownerPhone", normalizePhoneDigits(step1.ownerPhone))
        formData.append("primaryContactNumber", normalizePhoneDigits(step1.primaryContactNumber))
        formData.append("zoneId", step1.zoneId || "")
        formData.append("addressLine1", step1.location?.addressLine1 || "")
        formData.append("addressLine2", step1.location?.addressLine2 || "")
        formData.append("area", step1.location?.area || "")
        formData.append("city", step1.location?.city || "")
        formData.append("state", step1.location?.state || "")
        formData.append("pincode", step1.location?.pincode || "")
        formData.append("landmark", step1.location?.landmark || "")
        formData.append("formattedAddress", step1.location?.formattedAddress || "")
        formData.append("latitude", String(step1.location?.latitude || ""))
        formData.append("longitude", String(step1.location?.longitude || ""))

        // Step 2
        formData.append("cuisines", (step2.cuisines || []).join(","))
        formData.append("estimatedDeliveryTime", (step2.estimatedDeliveryTime || "").trim())
        formData.append("openingTime", normalizeTimeValue(step2.openingTime) || "")
        formData.append("closingTime", normalizeTimeValue(step2.closingTime) || "")
        formData.append("openDays", (step2.openDays || []).join(","))
        formData.append("isTakeawayEnabled", step2.isTakeawayEnabled ? "true" : "false")
        formData.append("isTakeawayCodEnabled", step2.isTakeawayCodEnabled ? "true" : "false")

        const menuFiles = (step2.menuImages || []).filter((f) => isUploadableFile(f))
        if (menuFiles.length === 0) {
          throw new Error("At least one menu image must be uploaded")
        }
        const preparedMenuFiles = await Promise.all(menuFiles.map((file) => prepareUploadFile(file)))
        preparedMenuFiles.forEach((file) => formData.append("menuImages", file))

        if (!isUploadableFile(step2.profileImage)) {
          throw new Error("Restaurant profile image is required")
        }
        formData.append(
          "profileImage",
          await prepareUploadFile(step2.profileImage, { preset: "profile" }),
        )

        // Step 3
        formData.append("panNumber", step3.panNumber || "")
        formData.append("nameOnPan", step3.nameOnPan || "")
        if (!isUploadableFile(step3.panImage)) {
          throw new Error("PAN image is required")
        }
        formData.append("panImage", await prepareUploadFile(step3.panImage))

        formData.append("gstRegistered", step3.gstRegistered ? "true" : "false")
        if (step3.gstRegistered) {
          formData.append("gstNumber", step3.gstNumber || "")
          formData.append("gstLegalName", step3.gstLegalName || "")
          formData.append("gstAddress", step3.gstAddress || "")
          if (!isUploadableFile(step3.gstImage)) {
            throw new Error("GST image is required when GST registered")
          }
          formData.append("gstImage", await prepareUploadFile(step3.gstImage))
        }

        formData.append("fssaiNumber", step3.fssaiNumber || "")
        formData.append("fssaiExpiry", step3.fssaiExpiry || "")
        if (!isUploadableFile(step3.fssaiImage)) {
          throw new Error("FSSAI image is required")
        }
        formData.append("fssaiImage", await prepareUploadFile(step3.fssaiImage))

        formData.append("accountNumber", step3.accountNumber || "")
        formData.append("ifscCode", (step3.ifscCode || "").toUpperCase())
        formData.append("accountHolderName", step3.accountHolderName || "")
        formData.append("accountType", step3.accountType || "")

        if (fcmToken) {
          formData.append("fcmToken", fcmToken)
          formData.append("platform", platform)
        }

        const registerResponse = await restaurantAPI.register(formData)
        const registered = registerResponse?.data?.data || registerResponse?.data || {}

        /*
         * Registration hands back a session now. On the "both" path that token
         * is what lets the hotel half be created straight afterwards, without
         * sending the partner back through another OTP.
         */
        if (registered?.session?.accessToken) {
          setAuthData("restaurant", registered.session.accessToken, registered, registered.session.refreshToken)
        }

        // Clear localStore when onboarding is complete
        clearOnboardingFromLocalStorage()
        clearOnboardingFileCache()
        try {
          await clearAllFilesFromDB()
        } catch {}

        toast.success("Registration submitted. Awaiting admin approval.", { duration: 4000 })
        await finalizeRestaurantPendingSubmission(navigate, step1.ownerPhone, {
          fcmToken,
          platform,
          ownerName: step1.ownerName,
          ownerEmail: step1.ownerEmail,
        })
      }
    } catch (err) {
      const msg =
        err?.response?.data?.message ||
        err?.response?.data?.error ||
        err?.message ||
        "Failed to save onboarding data"
      setError(msg)
      toast.error(msg)
    } finally {
      setSaving(false)
    }
  }



  const toggleDay = (day) => {
    setStep2((prev) => {
      const exists = prev.openDays.includes(day)
      if (exists) {
        return { ...prev, openDays: prev.openDays.filter((d) => d !== day) }
      }
      return { ...prev, openDays: [...prev.openDays, day] }
    })
  }
  
  /*
   * Location search. The web attaches the Google Places widget to the input (strictly inside the chosen
   * zone) and falls back to Nominatim suggestions; the app has no widget, so it asks the geocode proxy's
   * text search (biased to the chosen zone) and fills the same fields from the picked place.
   */
  const skipSearchRef = useRef("")

  const zoneCenter = (zone) => {
    const points = (Array.isArray(zone?.coordinates) ? zone.coordinates : [])
      .map((c) => ({ lat: parseFloat(c.latitude ?? c.lat), lng: parseFloat(c.longitude ?? c.lng) }))
      .filter((p) => Number.isFinite(p.lat) && Number.isFinite(p.lng))
    if (!points.length) return null
    return {
      latitude: points.reduce((sum, p) => sum + p.lat, 0) / points.length,
      longitude: points.reduce((sum, p) => sum + p.lng, 0) / points.length,
    }
  }

  useEffect(() => {
    if (step !== 1) return
    const q = String(locationSearchValue || "").trim()

    if (skipSearchRef.current && skipSearchRef.current === q) return
    skipSearchRef.current = ""

    if (q.length < 3) {
      setLocationSuggestions([])
      setIsSearchingLocation(false)
      return
    }

    const selectedZone = zones.find(z => String(z?._id || z?.id) === String(step1.zoneId))
    const zoneName = selectedZone?.name || selectedZone?.zoneName || selectedZone?.serviceLocation || ""
    let cancelled = false

    const t = setTimeout(async () => {
      try {
        setIsSearchingLocation(true)
        const queryWithZone = zoneName ? `${q}, ${zoneName}` : q
        const res = await geocodeAPI.textSearch({ textQuery: queryWithZone, maxResultCount: 8, ...(zoneCenter(selectedZone) || {}) })
        const places = res?.data?.data?.places
        const mapped = (Array.isArray(places) ? places : []).map((p) => ({
          id: p.id,
          display: [p.displayName?.text, p.formattedAddress].filter(Boolean).join(", ") || p.formattedAddress || "",
          formattedAddress: p.formattedAddress || "",
          lat: Number(p.location?.latitude),
          lng: Number(p.location?.longitude),
        }))
        if (!cancelled) setLocationSuggestions(mapped)
      } catch (e) {
        debugError("Location search failed:", e)
      } finally {
        if (!cancelled) setIsSearchingLocation(false)
      }
    }, 400)

    return () => {
      cancelled = true
      clearTimeout(t)
    }
  }, [locationSearchValue, step, step1.zoneId, zones])

  const selectLocationSuggestion = async (s) => {
    skipSearchRef.current = s.display
    setLocationSearchValue(s.display)
    setLocationSuggestions([])
    Keyboard.dismiss()

    // parsePlace() of the web's autocomplete handler, on the geocoded place's address components
    let parsed = { area: "", city: "", state: "", pincode: "" }
    try {
      const res = await geocodeAPI.place(s.id)
      const comps = res?.data?.data?.results?.[0]?.address_components
      if (Array.isArray(comps)) {
        const get = (types) => comps.find((c) => types.some((t) => c.types?.includes(t)))?.long_name || ""
        parsed = {
          area: get(["sublocality_level_1", "sublocality", "neighborhood"]) || get(["locality"]),
          city: get(["locality"]) || get(["administrative_area_level_2"]),
          state: get(["administrative_area_level_1"]) || get(["administrative_area_level_2"]),
          pincode: get(["postal_code"]),
        }
      }
    } catch (e) {
      debugError("Place details failed:", e)
    }

    setStep1((prev) => ({
      ...prev,
      location: {
        ...prev.location,
        formattedAddress: s.formattedAddress || s.display || prev.location.formattedAddress,
        addressLine1: s.formattedAddress || s.display || prev.location.addressLine1 || "",
        area: parsed.area || prev.location.area,
        city: parsed.city || prev.location.city,
        state: parsed.state || prev.location.state,
        pincode: parsed.pincode || prev.location.pincode,
        latitude: Number.isFinite(s.lat) ? Number(s.lat.toFixed(6)) : prev.location.latitude,
        longitude: Number.isFinite(s.lng) ? Number(s.lng.toFixed(6)) : prev.location.longitude,
      },
    }))
  }

  // Load zones for onboarding dropdown (public endpoint).
  useEffect(() => {
    if (step !== 1) return
    let cancelled = false
    setZonesLoading(true)
    zoneAPI.getPublicZones()
      .then((res) => {
        const list = res?.data?.data?.zones || res?.data?.zones || []
        if (!cancelled) setZones(Array.isArray(list) ? list : [])
      })
      .catch(() => {
        if (!cancelled) setZones([])
      })
      .finally(() => {
        if (!cancelled) setZonesLoading(false)
      })
    return () => { cancelled = true }
  }, [step])


  return {
    companyName,
    navigate,
    searchParams,
    step,
    setStep,
    loading,
    setLoading,
    saving,
    setSaving,
    error,
    setError,
    isLoggingOut,
    setIsLoggingOut,
    handleExitAnyway,
    goToPreviousOnboardingStep,
    handleLogout,
    verifiedPhoneNumber,
    setVerifiedPhoneNumber,
    keyboardInset,
    setKeyboardInset,
    isEditing,
    setIsEditing,
    hasExistingRestaurantProfile,
    setHasExistingRestaurantProfile,
    isFssaiCalendarOpen,
    setIsFssaiCalendarOpen,
    zones,
    setZones,
    zonesLoading,
    setZonesLoading,
    isOnboardingHydrated,
    setIsOnboardingHydrated,
    isHydratingRef,
    step1,
    setStep1,
    step2,
    setStep2,
    step3,
    setStep3,
    totalSteps,
    scrollRef,
    selectLocationSuggestion,
    hasStep1UnsavedProgress,
    showExitModal,
    handleBack,
    handleStay,
    handleExit,
    requestExit,
    previewUrlCacheRef,
    locationSearchInputRef,
    locationSearchContainerRef,
    placesAutocompleteRef,
    mapsScriptLoadedRef,
    menuImagesInputRef,
    profileImageInputRef,
    panImageInputRef,
    gstImageInputRef,
    fssaiImageInputRef,
    sourcePicker,
    setSourcePicker,
    locationSearchValue,
    setLocationSearchValue,
    locationSuggestions,
    setLocationSuggestions,
    isSearchingLocation,
    setIsSearchingLocation,
    isLocationSearchFocused,
    setIsLocationSearchFocused,
    getPreviewImageUrl,
    openImageSourcePicker,
    closeImageSourcePicker,
    handleMenuImagesSelected,
    handleProfileImageSelected,
    handlePanImageSelected,
    handleGstImageSelected,
    handleFssaiImageSelected,
    isPersistedImageValue,
    getPersistedImagePayload,
    toPersistedMenuImagesPayload,
    handleRemoveMenuImage,
    handleRemoveProfileImage,
    resolveImageForProfileUpdate,
    resolveMenuImagesForProfileUpdate,
    handleUpload,
    validateStep1,
    validateStep2,
    validateStep3,
    handleNext,
    toggleDay,
    normalizePhoneDigits,
    finalizeRestaurantPendingSubmission,
    daysOfWeek,
    ONBOARDING_STORAGE_KEY,
    PAN_NUMBER_REGEX,
    GST_NUMBER_REGEX,
    FSSAI_NUMBER_REGEX,
    BANK_ACCOUNT_NUMBER_REGEX,
    IFSC_CODE_REGEX,
    OWNER_NAME_REGEX,
    ACCOUNT_HOLDER_NAME_REGEX,
    GST_LEGAL_NAME_REGEX,
    LOCAL_IMAGE_FILE_ACCEPT,
    GALLERY_IMAGE_ACCEPT,
    onboardingFileCache,
    saveFileToDB,
    getFileFromDB,
    deleteFileFromDB,
    getUploadableMenuFiles,
    persistMenuImagesToDB,
    isUploadableFile,
    normalizePincode,
    getVerifiedPhoneFromStoredRestaurant,
    normalizeEmail,
    normalizeAccountTypeValue,
    formatNameToCapital,
    normalizeIFSC,
    normalizePAN,
    normalizeGST,
    normalizeBankAcc,
    getTodayLocalYMD,
    saveOnboardingToLocalStorage,
    loadOnboardingFromLocalStorage,
    syncOnboardingFileCache,
    clearOnboardingFileCache,
    stringToTime,
    timeToString,
    normalizeTimeValue,
    timeStringToMinutes,
    formatTime12Hour,
    formatDateToLocalYMD,
    parseLocalYMDDate,
  }
}
