// Generated by tools/extract-hook.js from Frontend/src/modules/Food/pages/restaurant/ShareFeedback.jsx (ShareFeedback), then edited by hand
// where the web code touched the DOM. The logic is the web page's own.
/* eslint-disable react-hooks/exhaustive-deps, no-unused-vars, no-empty */
import { useState } from 'react'
import { useNavigate } from '../../../lib/webRouter'
import useRestaurantBackNavigation from '../useRestaurantBackNavigation'
import { API_ENDPOINTS } from '../../../api/config'
import api from '../../../api/restaurant'
import { toast } from '../../../lib/notify'
import { useCompanyName } from '../useCompanyName'

const debugLog = (...args) => {}

const debugWarn = (...args) => {}

const debugError = (...args) => {}

export function useShareFeedback() {
  const companyName = useCompanyName()
  const navigate = useNavigate()
  const goBack = useRestaurantBackNavigation()
  const [rating, setRating] = useState(null)
  const [showThanks, setShowThanks] = useState(false)
  const [isSubmitting, setIsSubmitting] = useState(false)

  const numbers = Array.from({ length: 11 }, (_, i) => i)

  const handleClose = () => {
    goBack()
  }

  const handleContinue = async () => {
    if (rating === null) return
    
    try {
      setIsSubmitting(true)
      // Save feedback experience to backend
      const response = await api.post(API_ENDPOINTS.ADMIN.FEEDBACK_EXPERIENCE_CREATE, {
        rating: Math.ceil(rating / 2) || 1, // Convert 0-10 to 1-5 for backend
        module: 'restaurant',
        comment: `User rated ${rating}/10 overall experience`
      })
      
      if (response.data?.success) {
        setShowThanks(true)
      } else {
        throw new Error(response.data?.message || 'Failed to submit')
      }
    } catch (error) {
      debugError('Error submitting feedback:', error)
      toast.error(error.message || 'Failed to save feedback')
    } finally {
      setIsSubmitting(false)
    }
  }

  return {
    companyName,
    navigate,
    goBack,
    rating,
    setRating,
    showThanks,
    setShowThanks,
    isSubmitting,
    setIsSubmitting,
    numbers,
    handleClose,
    handleContinue,
  }
}
