// Generated by tools/extract-hook.js from Frontend/src/modules/Food/pages/restaurant/WithdrawalHistoryPage.jsx (WithdrawalHistoryPage), then edited by hand
// where the web code touched the DOM. The logic is the web page's own.
/* eslint-disable react-hooks/exhaustive-deps, no-unused-vars, no-empty */
import { useState, useEffect } from 'react'
import { useNavigate, useLocation } from '../../../lib/webRouter'
import useRestaurantBackNavigation from '../useRestaurantBackNavigation'
import { restaurantAPI } from '../../../api/restaurant'

const debugLog = (...args) => {}

const debugWarn = (...args) => {}

const debugError = (...args) => {}

export function useWithdrawalHistoryPage() {
  const navigate = useNavigate()
  const location = useLocation()
  const goBack = useRestaurantBackNavigation()
  const [withdrawalHistoryTab, setWithdrawalHistoryTab] = useState('pending')
  const [withdrawalRequests, setWithdrawalRequests] = useState([])
  const [loadingWithdrawalRequests, setLoadingWithdrawalRequests] = useState(false)

  // Fetch withdrawal requests on mount
  useEffect(() => {
    const fetchWithdrawalRequests = async () => {
      try {
        setLoadingWithdrawalRequests(true)
        const response = await restaurantAPI.getWithdrawalHistory()
        // API returns { success: true, data: [...] }
        const history = response?.data?.data || []
        
        // Map backend fields to the local UI names
        const mapped = history.map(h => ({
          id: h._id,
          amount: h.amount,
          status: h.status === 'approved' ? 'Approved' : h.status === 'rejected' ? 'Rejected' : 'Pending',
          requestedAt: h.createdAt,
          processedAt: h.processedAt
        }))
        
        setWithdrawalRequests(mapped)
      } catch (error) {
        if (error.response?.status !== 401) {
          debugError('Error fetching withdrawal requests:', error)
        }
      } finally {
        setLoadingWithdrawalRequests(false)
      }
    }

    fetchWithdrawalRequests()
  }, [])

  return {
    navigate,
    location,
    goBack,
    withdrawalHistoryTab,
    setWithdrawalHistoryTab,
    withdrawalRequests,
    setWithdrawalRequests,
    loadingWithdrawalRequests,
    setLoadingWithdrawalRequests,
  }
}
