// Generated by tools/extract-hook.js from Frontend/src/modules/Food/pages/restaurant/ZoneSetup.jsx (ZoneSetup), then edited by hand
// where the web code touched the DOM. The logic is the web page's own.
/* eslint-disable react-hooks/exhaustive-deps, no-unused-vars, no-empty */
import { useState, useEffect, useRef } from 'react'
import { useNavigate } from '../../../lib/webRouter'
import useRestaurantBackNavigation from '../useRestaurantBackNavigation'
import { restaurantAPI } from '../../../api/restaurant'
import { reverseGeocodeWithGoogle } from '../../utils/googleGeocoding'
import { buildRestaurantLocationUpdatePayload, dispatchRestaurantLocationUpdated, formatRestaurantDisplayAddress, normalizeRestaurantLocationFields } from '../../utils/restaurantLocation'
import { fetchPlaceSuggestions, resolvePlaceSuggestion } from '../../utils/googlePlaces'
import { toast } from '../../../lib/notify'

const debugLog = (...args) => {}

const debugWarn = (...args) => {}

const debugError = (...args) => console.error("[ZoneSetup]", ...args)

const parseCoordinate = (value) => {
  const parsed = Number(value)
  return Number.isFinite(parsed) ? parsed : null
}

const getSavedLocationCoords = (location) => {
  if (!location) return null

  let lat = null
  let lng = null

  if (Array.isArray(location.coordinates) && location.coordinates.length >= 2) {
    lng = parseCoordinate(location.coordinates[0])
    lat = parseCoordinate(location.coordinates[1])
  }

  if (lat === null || lng === null) {
    lat = parseCoordinate(location.latitude)
    lng = parseCoordinate(location.longitude)
  }

  if (lat === null || lng === null) return null

  if (lat < -90 || lat > 90 || lng < -180 || lng > 180) {
    const swappedLat = lng
    const swappedLng = lat

    if (
      swappedLat >= -90 && swappedLat <= 90 &&
      swappedLng >= -180 && swappedLng <= 180
    ) {
      return { lat: swappedLat, lng: swappedLng }
    }

    return null
  }

  return { lat, lng }
}

export function useZoneSetup() {
  const navigate = useNavigate()
  const goBack = useRestaurantBackNavigation()
  const mapRef = useRef(null)
  const mapInstanceRef = useRef(null)
  const markerRef = useRef(null)
  const sessionTokenRef = useRef(null)
  const debounceRef = useRef(null)
  const geocodeDebounceRef = useRef(null)
  const locationRef = useRef(null)

  const [googleMapsApiKey, setGoogleMapsApiKey] = useState("")
  const [mapLoading, setMapLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [geocoding, setGeocoding] = useState(false)
  const [restaurantData, setRestaurantData] = useState(null)
  const [selectedLocation, setSelectedLocation] = useState(null)
  const [locationSearch, setLocationSearch] = useState("")
  const [suggestions, setSuggestions] = useState([])
  const [showSuggestions, setShowSuggestions] = useState(false)
  const [markerCoord, setMarkerCoord] = useState(null)
  const [markerTitle, setMarkerTitle] = useState("Restaurant Location")

  const applyResolvedLocation = (fields) => {
    const next = normalizeRestaurantLocationFields(fields)
    if (!next) return
    locationRef.current = next
    setSelectedLocation(next)
    if (next.latitude != null) updateMarker(next.latitude, next.longitude, formatRestaurantDisplayAddress(next))
  }

  const updateLocationFromCoords = async (nextLat, nextLng) => {
    if (geocodeDebounceRef.current) clearTimeout(geocodeDebounceRef.current)

    geocodeDebounceRef.current = setTimeout(async () => {
      try {
        setGeocoding(true)
        const parsed = await reverseGeocodeWithGoogle(nextLat, nextLng)
        applyResolvedLocation(parsed.locationFields || {
          ...(locationRef.current || {}),
          latitude: nextLat,
          longitude: nextLng,
          formattedAddress: `${nextLat.toFixed(6)}, ${nextLng.toFixed(6)}`,
        })
      } catch (error) {
        debugError("Reverse geocode failed:", error)
        applyResolvedLocation({
          ...(locationRef.current || {}),
          latitude: nextLat,
          longitude: nextLng,
          formattedAddress: `${nextLat.toFixed(6)}, ${nextLng.toFixed(6)}`,
        })
      } finally {
        setGeocoding(false)
      }
    }, 450)
  }

  useEffect(() => {
    fetchRestaurantData()
  }, [])

  // The web's map is drawn by Google's script; here react-native-maps draws it,
  // the marker is state, and the map is ready when its onMapReady fires.
  const handleMapReady = () => setMapLoading(false)

  const moveMapTo = (lat, lng, zoom) => {
    const delta = (360 / Math.pow(2, zoom)) * 1.5
    mapInstanceRef.current?.animateToRegion({ latitude: lat, longitude: lng, latitudeDelta: delta, longitudeDelta: delta }, 350)
  }

  // Place suggestions: the web asks the Maps JS "new" Places API; natively the
  // backend text-search proxy answers instead (same dropdown).
  const fetchSuggestions = async (input) => {
    if (!input || input.trim().length < 2) {
      setSuggestions([])
      setShowSuggestions(false)
      return
    }

    try {
      const mapped = await fetchPlaceSuggestions(input.trim(), { latitude: markerCoord?.latitude, longitude: markerCoord?.longitude })
      setSuggestions(mapped)
      setShowSuggestions(mapped.length > 0)
    } catch (err) {
      setSuggestions([])
      setShowSuggestions(false)
    }
  }

  const handleSearchChange = (value) => {
    setLocationSearch(value)
    if (debounceRef.current) clearTimeout(debounceRef.current)
    debounceRef.current = setTimeout(() => fetchSuggestions(value), 300)
  }

  const handleSelectSuggestion = async (prediction) => {
    try {
      const resolved = await resolvePlaceSuggestion(prediction)
      const lat = Number(resolved.latitude)
      const lng = Number(resolved.longitude)
      if (!Number.isFinite(lat) || !Number.isFinite(lng)) return

      moveMapTo(lat, lng, 17)

      setLocationSearch(resolved.formattedAddress || prediction.display || prediction.mainText || "")
      setSuggestions([])
      setShowSuggestions(false)
      sessionTokenRef.current = null

      await updateLocationFromCoords(lat, lng)
    } catch (err) {
      debugError("Error selecting suggestion:", err)
    }
  }

  // Map tap: the web's map "click" listener.
  const handleMapPress = (event) => {
    const { latitude, longitude } = event.nativeEvent.coordinate
    updateMarker(latitude, longitude, "Resolving address...")
    updateLocationFromCoords(latitude, longitude)
  }

  // Marker drag: the web's marker "dragend" listener.
  const handleMarkerDragEnd = (event) => {
    const { latitude, longitude } = event.nativeEvent.coordinate
    updateLocationFromCoords(latitude, longitude)
  }

  useEffect(() => {
    if (restaurantData?.location && mapInstanceRef.current && !mapLoading) {
      const location = restaurantData.location
      const savedCoords = getSavedLocationCoords(location)

      if (savedCoords) {
        const { lat, lng } = savedCoords
        moveMapTo(lat, lng, 17)

        const normalized = normalizeRestaurantLocationFields(location)
        if (normalized) {
          applyResolvedLocation(normalized)
        } else {
          updateLocationFromCoords(lat, lng)
        }
      }
    }
  }, [restaurantData, mapLoading])

  const fetchRestaurantData = async () => {
    try {
      const response = await restaurantAPI.getCurrentRestaurant()
      const data = response?.data?.data?.restaurant || response?.data?.restaurant
      if (data) {
        setRestaurantData(data)
      }
    } catch (error) {
      debugError("Error fetching restaurant data:", error)
    }
  }

  const updateMarker = (lat, lng, address) => {
    setMarkerCoord({ latitude: lat, longitude: lng })
    setMarkerTitle(address || "Restaurant Location")
  }

  const handleSaveLocation = async () => {
    if (!selectedLocation?.latitude || !selectedLocation?.longitude) {
      toast.error("Please select a location on the map first")
      return
    }

    try {
      setSaving(true)

      const response = await restaurantAPI.updateProfile({
        location: buildRestaurantLocationUpdatePayload(selectedLocation),
      })

      if (response?.data?.data?.restaurant) {
        setRestaurantData(response.data.data.restaurant)
        toast.success("Location saved successfully. Awaiting admin approval.", { duration: 4000 })
        dispatchRestaurantLocationUpdated()
      } else {
        throw new Error("Failed to save location")
      }
    } catch (error) {
      debugError("Error saving location:", error)
      toast.error(error.response?.data?.message || "Failed to save location. Please try again.")
    } finally {
      setSaving(false)
    }
  }

  const selectedAddress = formatRestaurantDisplayAddress(selectedLocation, restaurantData)

  return {
    navigate,
    goBack,
    mapRef,
    mapInstanceRef,
    markerRef,
    sessionTokenRef,
    debounceRef,
    geocodeDebounceRef,
    locationRef,
    googleMapsApiKey,
    setGoogleMapsApiKey,
    mapLoading,
    setMapLoading,
    saving,
    setSaving,
    geocoding,
    setGeocoding,
    restaurantData,
    setRestaurantData,
    selectedLocation,
    setSelectedLocation,
    locationSearch,
    setLocationSearch,
    suggestions,
    setSuggestions,
    showSuggestions,
    setShowSuggestions,
    applyResolvedLocation,
    updateLocationFromCoords,
    fetchSuggestions,
    handleSearchChange,
    handleSelectSuggestion,
    fetchRestaurantData,
    handleMapReady,
    handleMapPress,
    handleMarkerDragEnd,
    markerCoord,
    markerTitle,
    handleSaveLocation,
    selectedAddress,
    parseCoordinate,
    getSavedLocationCoords,
  }
}
