/**
 * Shared support-desk logic.
 *
 * Every module's tickets live in one collection (see supportTicket.model.js),
 * so raising, listing and replying to one is the same work regardless of who is
 * asking — this is that work, once.
 */
import {
  SupportTicket,
  SUPPORT_STATUS_GROUPS,
  generateTicketCode,
} from './supportTicket.model.js';

// The code is generated by the model itself, so a ticket created through a
// module's own controller gets one too.
export { generateTicketCode };

/** Which bucket a status falls in, whatever spelling the module uses. */
export const statusGroupOf = (status) =>
  Object.keys(SUPPORT_STATUS_GROUPS).find((group) => SUPPORT_STATUS_GROUPS[group].includes(status))
  || 'waiting';

/** Turn a group name from a query string into the statuses it covers. */
export const statusesInGroup = (group) => SUPPORT_STATUS_GROUPS[group] || null;

export const createTicket = async ({
  module, requesterRole, requester, category, issueType, subject, description, context, priority,
}) => {
  const ticket = await SupportTicket.create({
    module,
    requesterRole,
    requesterId: requester?._id,
    requesterModel: requester?.constructor?.modelName,
    requesterName: requester?.name || '',
    requesterPhone: requester?.phone || '',
    category: category || 'other',
    issueType: issueType || '',
    subject: subject || '',
    description: description || '',
    context: context || undefined,
    priority: priority || 'medium',
    status: 'open',
    lastMessageAt: new Date(),
    // The opening description is also the first message, so a thread reads in
    // order instead of starting halfway through the conversation.
    messages: description
      ? [{
          senderRole: requesterRole,
          senderId: requester?._id,
          senderName: requester?.name || '',
          message: description,
        }]
      : [],
  });
  return ticket;
};

export const addMessage = async ({ ticket, senderRole, senderId, senderName, message }) => {
  ticket.messages.push({ senderRole, senderId, senderName: senderName || '', message });
  ticket.lastMessageAt = new Date();
  await ticket.save();
  return ticket;
};

export default { generateTicketCode, statusGroupOf, statusesInGroup, createTicket, addMessage };
