// Generated by tools/extract-hook.js from Frontend/src/modules/Taxi/modules/user/pages/intercity/IntercityDetails.jsx (IntercityDetails), then edited by hand
// where the web code touched the DOM. The logic is the web page's own.
/* eslint-disable react-hooks/exhaustive-deps, no-unused-vars, no-empty */
import { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate, useLocation } from '../../lib/webRouter'
import { HAS_VALID_GOOGLE_MAPS_KEY, DISTRICT_CENTER, useAppGoogleMapsLoader } from '../utils/googleMaps'
import api from '../api/client'
import { getTaxiUserRoutePrefix } from '../utils/routePrefix'
import { toHistorySafeState } from '../utils/historyState'
import { window, document, navigator, alert } from '../../lib/webShim'

/*
 * Seeds the map and biases place search when a trip names a city. It held the
 * previous product's Madhya Pradesh routes; these are the towns an outstation
 * trip from Dima Hasao actually starts or ends in.
 */

const CITY_CENTERS = {
  Haflong: { lat: 25.1667, lng: 93.0167 },
  Maibang: { lat: 25.3, lng: 93.1333 },
  Umrangso: { lat: 25.55, lng: 92.7 },
  Silchar: { lat: 24.8333, lng: 92.7789 },
  Lumding: { lat: 25.7486, lng: 93.1697 },
  Guwahati: { lat: 26.1445, lng: 91.7362 },
  Shillong: { lat: 25.5788, lng: 91.8933 },
  Dimapur: { lat: 25.9063, lng: 93.7276 },
  Badarpur: { lat: 24.8686, lng: 92.5951 },
};

const getCityCenter = (city) => CITY_CENTERS[city] || DISTRICT_CENTER;

const getCityCoords = (city) => {
  const center = getCityCenter(city);
  return [center.lng, center.lat];
};

const unwrapApiPayload = (response) => response?.data?.data || response?.data || response || {};

const normalizeSuggestionKey = (result) =>
  `${String(result?.title || '').trim().toLowerCase()}|${String(result?.address || '').trim().toLowerCase()}`;

const MAP_REVERSE_GEOCODE_DEBOUNCE_MS = 450;

const getLatLngCacheKey = (coords, precision = 5) =>
  `${Number(coords?.lat || 0).toFixed(precision)},${Number(coords?.lng || 0).toFixed(precision)}`;

const generateIntercityBookingId = () =>
  'IC-' + Math.random().toString(36).toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 6).padEnd(6, '0');

const generateSearchNonce = () =>
  `intercity-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;

export function useIntercityDetails() {
  const navigate = useNavigate();
  const location = useLocation();
  const routePrefix = getTaxiUserRoutePrefix(location.pathname);
  const state = location.state || {};
  const { fromCity, toCity, vehicle } = state;

  const [pickup, setPickup] = useState(state.pickupAddress || '');
  const [drop, setDrop] = useState('');
  const [pickupCoords, setPickupCoords] = useState(state.pickupCoords || null);
  const [dropCoords, setDropCoords] = useState(null);
  const [showMapPicker, setShowMapPicker] = useState(false);
  const [activeMapField, setActiveMapField] = useState('pickup');
  const [mapCenter, setMapCenter] = useState(DISTRICT_CENTER);
  const [pickedAddress, setPickedAddress] = useState('Move the map to choose a location');
  const [isGeocoding, setIsGeocoding] = useState(false);
  const [isDragging, setIsDragging] = useState(false);
  const [isLocating, setIsLocating] = useState(false);
  const [mapSearchInput, setMapSearchInput] = useState('');
  const [mapSearchResults, setMapSearchResults] = useState([]);
  const [isSearchingMapLocations, setIsSearchingMapLocations] = useState(false);
  const mapInstanceRef = useRef(null);
  const lastCenterRef = useRef(DISTRICT_CENTER);
  const geocoderRef = useRef(null);
  const autocompleteServiceRef = useRef(null);
  const placesServiceRef = useRef(null);
  const autocompleteSessionTokenRef = useRef(null);
  const mapSearchCacheRef = useRef(new Map());
  const latestMapSearchRef = useRef(0);
  const reverseGeocodeTimerRef = useRef(null);
  const reverseGeocodeCacheRef = useRef(new Map());
  const placeSelectionCacheRef = useRef(new Map());
  const { isLoaded, loadError } = useAppGoogleMapsLoader();

  const [autocompletePickup, setAutocompletePickup] = useState(null);
  const [autocompleteDrop, setAutocompleteDrop] = useState(null);
  const [liveDriverCount, setLiveDriverCount] = useState(0);
  const [isFetchingDrivers, setIsFetchingDrivers] = useState(false);
  const [driverFetchError, setDriverFetchError] = useState('');
  const [validationError, setValidationError] = useState('');
  const [isProceeding, setIsProceeding] = useState(false);
  const serviceLocationId = useMemo(
    () => state.serviceLocationId || state.selectedPackages?.[0]?.serviceLocationId || '',
    [state.serviceLocationId, state.selectedPackages]
  );

  const effectivePickupCoords = useMemo(
    () => pickupCoords || state.pickupCoords || getCityCoords(fromCity),
    [fromCity, pickupCoords, state.pickupCoords]
  );

  useEffect(() => {
    if (!fromCity || !vehicle) {
      navigate(`${routePrefix}/intercity`, { replace: true });
    }
  }, [fromCity, navigate, routePrefix, vehicle]);

  useEffect(() => {
    if (!isLoaded || !window.google?.maps?.places?.AutocompleteService) {
      return;
    }

    autocompleteServiceRef.current = autocompleteServiceRef.current || new window.google.maps.places.AutocompleteService();
    placesServiceRef.current = placesServiceRef.current || new window.google.maps.places.PlacesService(document.createElement('div'));
    autocompleteSessionTokenRef.current = autocompleteSessionTokenRef.current
      || new window.google.maps.places.AutocompleteSessionToken();
  }, [isLoaded]);

  useEffect(() => {
    let active = true;

    const loadNearbyDrivers = async () => {
      if (!vehicle?.vehicleTypeId || !Array.isArray(effectivePickupCoords)) {
        if (active) {
          setLiveDriverCount(0);
          setDriverFetchError('');
          setIsFetchingDrivers(false);
        }
        return;
      }

      try {
        if (active) {
          setIsFetchingDrivers(true);
          setDriverFetchError('');
        }

        const response = await api.get('/rides/available-drivers', {
          params: {
            vehicleTypeId: vehicle.vehicleTypeId,
            vehicleIconType: vehicle.iconType || vehicle.name || 'car',
            lng: effectivePickupCoords[0],
            lat: effectivePickupCoords[1],
            service_location_id: serviceLocationId,
            transport_type: 'intercity',
          },
        });

        if (!active) {
          return;
        }

        const availability = unwrapApiPayload(response);
        setLiveDriverCount(Number(availability?.totalDrivers || 0));
      } catch (error) {
        if (!active) {
          return;
        }

        setLiveDriverCount(0);
        setDriverFetchError(error?.message || 'Could not fetch live driver availability.');
      } finally {
        if (active) {
          setIsFetchingDrivers(false);
        }
      }
    };

    loadNearbyDrivers();

    return () => {
      active = false;
    };
  }, [effectivePickupCoords, serviceLocationId, vehicle]);

  // The web returns null here, above two more effects. A hook cannot return early
  // between hooks, so the guard is reported in the result instead.

  const handleContinue = async () => {
    /*
     * This refused with `alert()`, which a Flutter WebView silently swallows —
     * so tapping Proceed did nothing at all, with no message and no request.
     * The screen already renders an error banner directly above this button;
     * say it there, and mark the field that is actually empty.
     */
    if (!pickup.trim() || !drop.trim()) {
      setValidationError(
        !pickup.trim() && !drop.trim()
          ? 'Enter your exact pickup and drop addresses to continue.'
          : !pickup.trim()
            ? 'Enter your exact pickup address to continue.'
            : 'Enter your exact drop address to continue.',
      );
      return;
    }

    setValidationError('');

    const nextPickupCoords = pickupCoords || getCityCoords(fromCity);
    const nextDropCoords = dropCoords || getCityCoords(toCity);
    const bookingId = state.bookingId || generateIntercityBookingId();
    let availabilitySnapshot = {
      totalDrivers: liveDriverCount,
      fetchedAt: new Date().toISOString(),
    };

    if (vehicle?.vehicleTypeId && Array.isArray(nextPickupCoords)) {
      try {
        setIsProceeding(true);
        setDriverFetchError('');
        const response = await api.get('/rides/available-drivers', {
          params: {
            vehicleTypeId: vehicle.vehicleTypeId,
            vehicleIconType: vehicle.iconType || vehicle.name || 'car',
            lng: nextPickupCoords[0],
            lat: nextPickupCoords[1],
            service_location_id: serviceLocationId,
            transport_type: 'intercity',
          },
        });
        /*
         * The taxi axios instance hands back a Proxy (createCompatibleResponseView)
         * so both `res.data.x` and `res.x` resolve, and every nested read is
         * re-wrapped in another Proxy. A Proxy carries internal slots, so
         * structuredClone rejects it outright -- at any depth, however plain its
         * target. Spreading it copies the keys but keeps the proxied values, so
         * this snapshot used to ride into history state and make pushState throw
         * DataCloneError, which killed the navigate below with no visible error.
         * Snapshot it into plain data here, where the Proxy enters.
         */
        const availability = toHistorySafeState(unwrapApiPayload(response)) || {};

        availabilitySnapshot = {
          ...availability,
          totalDrivers: Number(availability?.totalDrivers || 0),
          fetchedAt: new Date().toISOString(),
        };
        setLiveDriverCount(Number(availability?.totalDrivers || 0));
      } catch (error) {
        setDriverFetchError(error?.message || 'Could not fetch live driver availability.');
      } finally {
        setIsProceeding(false);
      }
    }

    const nextState = {
      ...state,
      bookingId,
      pickup,
      drop,
      pickupCoords: nextPickupCoords,
      dropCoords: nextDropCoords,
      searchNonce: generateSearchNonce(),
      vehicleTypeId: vehicle.vehicleTypeId || '',
      vehicleIconType: vehicle.iconType || vehicle.name || 'car',
      vehicleIconUrl: vehicle.vehicleIconUrl || vehicle.icon || '',
      paymentMethod: 'Cash',
      serviceType: 'intercity',
      transport_type: 'intercity',
      bookingMode: vehicle.supportsBidding ? 'bidding' : (state.bookingMode || 'normal'),
      bidStepAmount: Number(state.bidStepAmount || 10),
      userMaxBidFare: vehicle.supportsBidding
        ? Number(state.userMaxBidFare || state.fare || 0)
        : Number(state.fare || 0),
      intercity: {
        bookingId,
        fromCity,
        toCity,
        tripType: state.tripType || 'One Way',
        travelDate: state.date || 'Ride Now',
        passengers: state.passengers || 1,
        distance: Number(state.distance || 0),
        vehicleName: vehicle.name || vehicle.id || 'Intercity Cab',
        packageId: vehicle.packageId || '',
        packageTypeName: vehicle.packageTypeName || 'Intercity',
      },
      driverAvailability: availabilitySnapshot,
    };

    if (state.rideMode === 'schedule' && state.scheduledAt) {
      navigate(`${routePrefix}/intercity/confirm`, {
        state: nextState,
      });
      return;
    }

    navigate(`${routePrefix}/ride/searching`, {
      state: {
        ...nextState,
      }
    });
  };

  const handlePickupPlaceChanged = () => {
    if (autocompletePickup) {
      const place = autocompletePickup.getPlace();
      if (place && place.formatted_address) {
        setPickup(place.formatted_address);
        if (place.geometry) {
          setPickupCoords([place.geometry.location.lng(), place.geometry.location.lat()]);
        }
      }
    }
  };

  const handleDropPlaceChanged = () => {
    if (autocompleteDrop) {
      const place = autocompleteDrop.getPlace();
      if (place && place.formatted_address) {
        setDrop(place.formatted_address);
        if (place.geometry) {
          setDropCoords([place.geometry.location.lng(), place.geometry.location.lat()]);
        }
      }
    }
  };

  const getAutocompleteSessionToken = () => {
    if (!window.google?.maps?.places?.AutocompleteSessionToken) {
      return null;
    }

    if (!autocompleteSessionTokenRef.current) {
      autocompleteSessionTokenRef.current = new window.google.maps.places.AutocompleteSessionToken();
    }

    return autocompleteSessionTokenRef.current;
  };

  const resetAutocompleteSessionToken = () => {
    if (!window.google?.maps?.places?.AutocompleteSessionToken) {
      autocompleteSessionTokenRef.current = null;
      return;
    }

    autocompleteSessionTokenRef.current = new window.google.maps.places.AutocompleteSessionToken();
  };

  const getGeocoder = () => {
    if (!window.google?.maps?.Geocoder) {
      return null;
    }

    if (!geocoderRef.current) {
      geocoderRef.current = new window.google.maps.Geocoder();
    }

    return geocoderRef.current;
  };

  const getPlacesService = () => {
    if (!window.google?.maps?.places?.PlacesService) {
      return null;
    }

    if (!placesServiceRef.current) {
      placesServiceRef.current = new window.google.maps.places.PlacesService(document.createElement('div'));
    }

    return placesServiceRef.current;
  };

  const resolveSuggestionSelection = async (result) => {
    const cacheKey = String(result?.placeId || normalizeSuggestionKey(result));
    if (cacheKey) {
      const cached = placeSelectionCacheRef.current.get(cacheKey);
      if (cached) {
        return cached;
      }
    }

    const geocoder = getGeocoder();
    const placesService = getPlacesService();

    if (result?.placeId && placesService) {
      return new Promise((resolve) => {
        placesService.getDetails(
          {
            placeId: result.placeId,
            sessionToken: getAutocompleteSessionToken(),
            fields: ['formatted_address', 'geometry.location', 'name'],
          },
          (place, status) => {
            const location = place?.geometry?.location;

            if (status === 'OK' && location) {
              const resolvedResult = {
                title: result.title || place.name || place.formatted_address,
                address: place.formatted_address || result.address || result.title || '',
                coords: [location.lng(), location.lat()],
              };
              if (cacheKey) {
                placeSelectionCacheRef.current.set(cacheKey, resolvedResult);
              }
              resolve(resolvedResult);
              return;
            }

            if (!geocoder || !result.placeId) {
              resolve(null);
              return;
            }

            geocoder.geocode({ placeId: result.placeId }, (results, geocodeStatus) => {
              const geocodedPlace = results?.[0];
              const geocodedLocation = geocodedPlace?.geometry?.location;

              if (geocodeStatus === 'OK' && geocodedLocation) {
                const resolvedResult = {
                  title: result.title || geocodedPlace.formatted_address,
                  address: geocodedPlace.formatted_address || result.address || result.title || '',
                  coords: [geocodedLocation.lng(), geocodedLocation.lat()],
                };
                if (cacheKey) {
                  placeSelectionCacheRef.current.set(cacheKey, resolvedResult);
                }
                resolve(resolvedResult);
                return;
              }

              resolve(null);
            });
          },
        );
      });
    }

    if (!geocoder || !result?.address) {
      return null;
    }

    return new Promise((resolve) => {
      geocoder.geocode({ address: result.address }, (results, status) => {
        const place = results?.[0];
        const location = place?.geometry?.location;

        if (status === 'OK' && location) {
          const resolvedResult = {
            title: result.title || place.formatted_address,
            address: place.formatted_address || result.address || result.title || '',
            coords: [location.lng(), location.lat()],
          };
          if (cacheKey) {
            placeSelectionCacheRef.current.set(cacheKey, resolvedResult);
          }
          resolve(resolvedResult);
          return;
        }

        resolve(null);
      });
    });
  };

  const openMapPicker = (field) => {
    const savedCoords = field === 'pickup' ? pickupCoords : dropCoords;
    const savedAddress = field === 'pickup' ? pickup : drop;
    const cityCenter = getCityCenter(field === 'pickup' ? fromCity : toCity);
    const center = Array.isArray(savedCoords)
      ? { lat: savedCoords[1], lng: savedCoords[0] }
      : cityCenter;

    setActiveMapField(field);
    setMapCenter(center);
    lastCenterRef.current = center;
    setPickedAddress(savedAddress || (field === 'pickup' ? `${fromCity} location` : toCity));
    setMapSearchInput(savedAddress || '');
    setMapSearchResults([]);
    setIsSearchingMapLocations(false);
    setShowMapPicker(true);
  };

  const handleMapIdle = () => {
    if (!mapInstanceRef.current || !window.google?.maps?.Geocoder) return;

    const center = mapInstanceRef.current.getCenter();
    const lat = center.lat();
    const lng = center.lng();
    const diff = Math.abs(lat - lastCenterRef.current.lat) + Math.abs(lng - lastCenterRef.current.lng);

    if (diff < 0.00001) {
      setIsDragging(false);
      return;
    }

    lastCenterRef.current = { lat, lng };
    setIsDragging(false);
    const cacheKey = getLatLngCacheKey({ lat, lng });
    const cached = reverseGeocodeCacheRef.current.get(cacheKey);
    if (cached) {
      setPickedAddress(cached);
      return;
    }

    if (reverseGeocodeTimerRef.current) {
      clearTimeout(reverseGeocodeTimerRef.current);
    }

    reverseGeocodeTimerRef.current = setTimeout(() => {
      const geocoder = getGeocoder();
      if (!geocoder) {
        setPickedAddress(`${lat.toFixed(5)}, ${lng.toFixed(5)}`);
        return;
      }

      setIsGeocoding(true);
      geocoder.geocode({ location: { lat, lng } }, (results, status) => {
        setIsGeocoding(false);
        if (status === 'OK' && results?.[0]) {
          reverseGeocodeCacheRef.current.set(cacheKey, results[0].formatted_address);
          setPickedAddress(results[0].formatted_address);
          return;
        }

        setPickedAddress(`${lat.toFixed(5)}, ${lng.toFixed(5)}`);
      });
    }, MAP_REVERSE_GEOCODE_DEBOUNCE_MS);
  };

  useEffect(() => () => {
    if (reverseGeocodeTimerRef.current) {
      clearTimeout(reverseGeocodeTimerRef.current);
    }
  }, []);

  const handleUseCurrentLocation = () => {
    if (!navigator.geolocation) return;

    setIsLocating(true);
    navigator.geolocation.getCurrentPosition(
      (pos) => {
        setIsLocating(false);
        const nextCenter = { lat: pos.coords.latitude, lng: pos.coords.longitude };
        if (mapInstanceRef.current) {
          mapInstanceRef.current.panTo(nextCenter);
          mapInstanceRef.current.setZoom(17);
        } else {
          setMapCenter(nextCenter);
        }
      },
      () => setIsLocating(false),
      { enableHighAccuracy: true }
    );
  };

  const handleMapSearchSuggestionSelect = async (result) => {
    const resolvedResult = await resolveSuggestionSelection(result);
    if (!resolvedResult?.coords) {
      return;
    }

    const [lng, lat] = resolvedResult.coords;
    const nextCenter = { lat, lng };
    lastCenterRef.current = nextCenter;
    setMapCenter(nextCenter);
    setPickedAddress(resolvedResult.address);
    setMapSearchInput(resolvedResult.address);
    setMapSearchResults([]);
    resetAutocompleteSessionToken();

    if (mapInstanceRef.current) {
      mapInstanceRef.current.panTo(nextCenter);
      mapInstanceRef.current.setZoom(17);
    }
  };

  const handleConfirmMapLocation = () => {
    const selectedCoords = [lastCenterRef.current.lng, lastCenterRef.current.lat];

    if (activeMapField === 'pickup') {
      setPickup(pickedAddress);
      setPickupCoords(selectedCoords);
    } else {
      setDrop(pickedAddress);
      setDropCoords(selectedCoords);
    }

    setShowMapPicker(false);
  };

  useEffect(() => {
    if (!showMapPicker || !mapSearchInput.trim() || mapSearchInput.trim().length < 3 || !HAS_VALID_GOOGLE_MAPS_KEY || !autocompleteServiceRef.current) {
      setMapSearchResults([]);
      setIsSearchingMapLocations(false);
      return;
    }

    const normalizedQuery = `${activeMapField}:${mapSearchInput.trim().toLowerCase()}`;
    const cached = mapSearchCacheRef.current.get(normalizedQuery);
    if (cached) {
      setMapSearchResults(cached);
      setIsSearchingMapLocations(false);
      return;
    }

    const requestId = latestMapSearchRef.current + 1;
    latestMapSearchRef.current = requestId;
    setIsSearchingMapLocations(true);

    const timeoutId = setTimeout(() => {
      const city = activeMapField === 'pickup' ? fromCity : toCity;

      autocompleteServiceRef.current.getPlacePredictions(
        {
          input: mapSearchInput.trim(),
          componentRestrictions: { country: 'in' },
          sessionToken: getAutocompleteSessionToken(),
          ...(city ? { locationBias: { center: getCityCenter(city), radius: 30000 } } : {}),
        },
        (predictions = [], status) => {
          if (latestMapSearchRef.current !== requestId) {
            return;
          }

          const nextResults = status === 'OK'
            ? predictions.slice(0, 6).map((prediction) => ({
              title: prediction.structured_formatting?.main_text || prediction.description,
              address: prediction.description,
              placeId: prediction.place_id,
            }))
            : [];

          mapSearchCacheRef.current.set(normalizedQuery, nextResults);
          setMapSearchResults(nextResults);
          setIsSearchingMapLocations(false);
        },
      );
    }, 300);

    return () => {
      clearTimeout(timeoutId);
    };
  }, [activeMapField, fromCity, mapSearchInput, showMapPicker, toCity]);

  return {
    __guard: !fromCity || !vehicle,
    navigate,
    location,
    routePrefix,
    state,
    fromCity,
    toCity,
    vehicle,
    pickup,
    setPickup,
    drop,
    setDrop,
    pickupCoords,
    setPickupCoords,
    dropCoords,
    setDropCoords,
    showMapPicker,
    setShowMapPicker,
    activeMapField,
    setActiveMapField,
    mapCenter,
    setMapCenter,
    pickedAddress,
    setPickedAddress,
    isGeocoding,
    setIsGeocoding,
    isDragging,
    setIsDragging,
    isLocating,
    setIsLocating,
    mapSearchInput,
    setMapSearchInput,
    mapSearchResults,
    setMapSearchResults,
    isSearchingMapLocations,
    setIsSearchingMapLocations,
    mapInstanceRef,
    lastCenterRef,
    geocoderRef,
    autocompleteServiceRef,
    placesServiceRef,
    autocompleteSessionTokenRef,
    mapSearchCacheRef,
    latestMapSearchRef,
    reverseGeocodeTimerRef,
    reverseGeocodeCacheRef,
    placeSelectionCacheRef,
    isLoaded,
    loadError,
    autocompletePickup,
    setAutocompletePickup,
    autocompleteDrop,
    setAutocompleteDrop,
    liveDriverCount,
    setLiveDriverCount,
    isFetchingDrivers,
    setIsFetchingDrivers,
    driverFetchError,
    setDriverFetchError,
    validationError,
    setValidationError,
    isProceeding,
    setIsProceeding,
    serviceLocationId,
    effectivePickupCoords,
    handleContinue,
    handlePickupPlaceChanged,
    handleDropPlaceChanged,
    getAutocompleteSessionToken,
    resetAutocompleteSessionToken,
    getGeocoder,
    getPlacesService,
    resolveSuggestionSelection,
    openMapPicker,
    handleMapIdle,
    handleUseCurrentLocation,
    handleMapSearchSuggestionSelect,
    handleConfirmMapLocation,
    CITY_CENTERS,
    getCityCenter,
    getCityCoords,
    unwrapApiPayload,
    normalizeSuggestionKey,
    MAP_REVERSE_GEOCODE_DEBOUNCE_MS,
    getLatLngCacheKey,
    generateIntercityBookingId,
    generateSearchNonce,
  }
}
