// Generated by tools/extract-hook.js from Frontend/src/modules/Taxi/modules/user/pages/intercity/IntercityVehicle.jsx (IntercityVehicle), then edited by hand
// where the web code touched the DOM. The logic is the web page's own.
/* eslint-disable react-hooks/exhaustive-deps, no-unused-vars, no-empty */
import { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate, useLocation } from '../../lib/webRouter'
import { useSettings } from '../context/SettingsContext'
import { getTaxiUserRoutePrefix } from '../utils/routePrefix'

const pad = (value) => String(value).padStart(2, '0');

const formatDateInputValue = (date) => {
  const year = date.getFullYear();
  const month = pad(date.getMonth() + 1);
  const day = pad(date.getDate());
  return `${year}-${month}-${day}`;
};

const formatDateTimeInputValue = (date) => {
  const year = date.getFullYear();
  const month = pad(date.getMonth() + 1);
  const day = pad(date.getDate());
  const hours = pad(date.getHours());
  const minutes = pad(date.getMinutes());
  return `${year}-${month}-${day}T${hours}:${minutes}`;
};

const getTomorrowLocalDateTime = () => {
  const next = new Date(Date.now() + 60 * 60 * 1000);
  return formatDateTimeInputValue(next);
};

const DEFAULT_BID_STEP_AMOUNT = 10;

const DEFAULT_BID_HEADROOM_PERCENT = 20;

const toConfiguredPositiveInteger = (value, fallback) => {
  const numeric = Number(value);
  return Number.isFinite(numeric) && numeric > 0 ? Math.round(numeric) : fallback;
};

const clampPercentage = (value, fallback = 0) => {
  const numeric = Number(value);
  if (!Number.isFinite(numeric)) {
    return fallback;
  }

  return Math.max(0, Math.min(100, numeric));
};

const alignBidAmountToStep = ({ baseFare, amount, stepAmount }) => {
  const safeBaseFare = Math.max(0, Math.round(Number(baseFare || 0)));
  const safeStepAmount = toConfiguredPositiveInteger(stepAmount, DEFAULT_BID_STEP_AMOUNT);
  const safeAmount = Math.max(safeBaseFare, Math.round(Number(amount || 0)));
  const delta = safeAmount - safeBaseFare;

  if (delta === 0) {
    return safeBaseFare;
  }

  return safeBaseFare + (Math.ceil(delta / safeStepAmount) * safeStepAmount);
};

const getTodayLocalDate = () => formatDateInputValue(new Date());

const getMaxAdvanceDate = () => {
  const nextWeek = new Date();
  nextWeek.setDate(nextWeek.getDate() + 7);
  return formatDateInputValue(nextWeek);
};

const getMaxAdvanceDateTime = () => {
  const nextWeek = new Date();
  nextWeek.setDate(nextWeek.getDate() + 7);
  return formatDateTimeInputValue(nextWeek);
};

const getVehicleIcon = (type = {}) => {
  const customIcon = String(type.icon || '').trim();
  if (customIcon) return customIcon;

  const iconValue = String(type.iconType || type.vehicleName || '').toLowerCase();
  if (iconValue.includes('bike')) return '/1_Bike.png';
  if (iconValue.includes('auto')) return '/2_AutoRickshaw.png';
  return '/4_Taxi.png';
};

const normalizeVehicleEntry = (pkg, vehicle, index) => ({
  id: vehicle.id || `${pkg.id}:${vehicle.vehicleTypeId || index}`,
  packageId: pkg.id,
  packageTypeName: pkg.packageTypeName || 'Intercity',
  destination: pkg.destination || '',
  vehicleTypeId: vehicle.vehicleTypeId || '',
  name: vehicle.vehicleName || 'Vehicle',
  desc: `${pkg.packageTypeName || 'Intercity'} · ${pkg.destination || 'Destination'}`,
  seats: Number(vehicle.capacity || 4) || 4,
  icon: getVehicleIcon(vehicle),
  vehicleIconUrl: getVehicleIcon(vehicle),
  iconType: vehicle.iconType || vehicle.vehicleName || 'car',
  dispatchType: String(vehicle.dispatchType || 'normal').trim().toLowerCase(),
  supportsBidding: ['bidding', 'both'].includes(String(vehicle.dispatchType || 'normal').trim().toLowerCase()),
  baseFare: Number(vehicle.basePrice || 0),
  freeDistance: Number(vehicle.freeDistance || 0),
  pricePerKm: Number(vehicle.distancePrice || 0),
  freeTime: Number(vehicle.freeTime || 0),
  timePrice: Number(vehicle.timePrice || 0),
  serviceTax: Number(vehicle.serviceTax || 0),
  cancellationFee: Number(vehicle.cancellationFee || 0),
});

const calculateFare = (vehicle, tripType) => {
  const baseFare = Number(vehicle.baseFare || 0);
  return tripType === 'Round Trip' ? Math.round(baseFare * 1.8) : Math.round(baseFare);
};

const calculateDefaultBidCeiling = (fare, stepAmount = DEFAULT_BID_STEP_AMOUNT, headroomPercent = DEFAULT_BID_HEADROOM_PERCENT) => {
  const safeFare = Math.max(0, Number(fare || 0));
  const raisedFare = safeFare * (1 + (clampPercentage(headroomPercent, DEFAULT_BID_HEADROOM_PERCENT) / 100));
  return alignBidAmountToStep({ baseFare: safeFare, amount: raisedFare, stepAmount });
};

const getDisplayDate = (rideMode, travelDate) => (rideMode === 'schedule' ? travelDate : 'Ride Now');

export function useIntercityVehicle() {
  const navigate = useNavigate();
  const location = useLocation();
  const { settings } = useSettings();
  const routePrefix = getTaxiUserRoutePrefix(location.pathname);
  const {
    fromCity,
    toCity,
    tripType: initialTripType,
    date: initialDate,
    rideMode: initialRideMode,
    selectedPackages = [],
    pickupAddress = '',
    pickupCoords = null,
  } = location.state || {};

  const [tripType, setTripType] = useState(initialTripType || 'One Way');
  const [rideMode, setRideMode] = useState(initialRideMode || 'now');
  const [travelDate, setTravelDate] = useState(
    initialRideMode === 'schedule' && initialDate && initialDate !== 'Ride Now'
      ? initialDate
      : new Date().toISOString().split('T')[0]
  );
  const [scheduledAt, setScheduledAt] = useState(
    initialRideMode === 'schedule' && location.state?.scheduledAt
      ? String(location.state.scheduledAt).slice(0, 16)
      : getTomorrowLocalDateTime()
  );
  const [passengers, setPassengers] = useState(1);
  const [selectedVehicleId, setSelectedVehicleId] = useState('');
  const [scheduleError, setScheduleError] = useState('');
  const travelDateInputRef = useRef(null);
  const scheduledAtInputRef = useRef(null);
  const minTravelDate = useMemo(() => getTodayLocalDate(), []);
  const maxTravelDate = useMemo(() => getMaxAdvanceDate(), []);
  const minScheduledAt = useMemo(() => getTomorrowLocalDateTime(), []);
  const maxScheduledAt = useMemo(() => getMaxAdvanceDateTime(), []);

  const vehicles = useMemo(
    () =>
      selectedPackages.flatMap((pkg) =>
        (Array.isArray(pkg.vehicles) ? pkg.vehicles : []).map((vehicle, index) =>
          normalizeVehicleEntry(pkg, vehicle, index)
        )
      ),
    [selectedPackages]
  );

  useEffect(() => {
    if (!selectedVehicleId && vehicles.length) {
      setSelectedVehicleId(vehicles[0].id);
    }
  }, [selectedVehicleId, vehicles]);

  const selectedVehicle = useMemo(
    () => vehicles.find((vehicle) => vehicle.id === selectedVehicleId) || vehicles[0] || null,
    [selectedVehicleId, vehicles]
  );

  useEffect(() => {
    if (!fromCity || !toCity) {
      navigate(`${routePrefix}/intercity`, { replace: true });
    }
  }, [fromCity, navigate, routePrefix, toCity]);

  useEffect(() => {
    if (!selectedVehicle) return;
    setPassengers((current) => Math.min(Math.max(current, 1), selectedVehicle.seats));
  }, [selectedVehicle]);

  useEffect(() => {
    if (travelDate < minTravelDate) {
      setTravelDate(minTravelDate);
      return;
    }

    if (travelDate > maxTravelDate) {
      setTravelDate(maxTravelDate);
    }
  }, [maxTravelDate, minTravelDate, travelDate]);

  useEffect(() => {
    if (!scheduledAt) {
      return;
    }

    if (scheduledAt < minScheduledAt) {
      setScheduledAt(minScheduledAt);
      return;
    }

    if (scheduledAt > maxScheduledAt) {
      setScheduledAt(maxScheduledAt);
    }
  }, [maxScheduledAt, minScheduledAt, scheduledAt]);

  if (!fromCity || !toCity) {
    return { __guard: true }
  }

  const finalFare = selectedVehicle ? calculateFare(selectedVehicle, tripType) : 0;
  const configuredBidStepAmount = toConfiguredPositiveInteger(
    settings?.bidRide?.bidding_amount_increase_or_decrease,
    DEFAULT_BID_STEP_AMOUNT,
  );
  const configuredBidHighPercentage = clampPercentage(
    settings?.bidRide?.user_bidding_high_percentage,
    DEFAULT_BID_HEADROOM_PERCENT,
  );

  const openPicker = (inputRef) => {
    if (typeof inputRef.current?.showPicker === 'function') {
      inputRef.current.showPicker();
      return;
    }

    inputRef.current?.focus();
    inputRef.current?.click();
  };

  const handleContinue = () => {
    if (!selectedVehicle) return;

    if (rideMode === 'schedule') {
      const parsedSchedule = new Date(scheduledAt);
      if (!scheduledAt || Number.isNaN(parsedSchedule.getTime())) {
        setScheduleError('Choose a valid schedule date and time.');
        return;
      }

      if (!travelDate || travelDate < minTravelDate) {
        setScheduleError('Travel date cannot be earlier than today.');
        return;
      }

      if (travelDate > maxTravelDate) {
        setScheduleError('Advance booking is available for up to 7 days only.');
        return;
      }

      if (parsedSchedule.getTime() <= Date.now() + 60 * 1000) {
        setScheduleError('Schedule time must be at least 1 minute ahead.');
        return;
      }

      if (scheduledAt < minScheduledAt) {
        setScheduleError('Schedule time cannot be earlier than now.');
        return;
      }

      if (scheduledAt > maxScheduledAt) {
        setScheduleError('Advance booking is available for up to 7 days only.');
        return;
      }
    }

    setScheduleError('');

    navigate(`${routePrefix}/intercity/details`, {
      state: {
        fromCity,
        toCity,
        tripType,
        rideMode,
        date: getDisplayDate(rideMode, travelDate),
        travelDate,
        scheduledAt: rideMode === 'schedule' ? new Date(scheduledAt).toISOString() : null,
        selectedPackages,
        pickupAddress,
        pickupCoords,
        distance: 0,
        vehicle: selectedVehicle,
        passengers,
        fare: finalFare,
        baseFare: finalFare,
        bookingMode: selectedVehicle.supportsBidding ? 'bidding' : 'normal',
        bidStepAmount: configuredBidStepAmount,
        userMaxBidFare: selectedVehicle.supportsBidding
          ? calculateDefaultBidCeiling(finalFare, configuredBidStepAmount, configuredBidHighPercentage)
          : finalFare,
      },
    });
  };

  return {
    navigate,
    location,
    settings,
    routePrefix,
    fromCity,
    toCity,
    initialTripType,
    initialDate,
    initialRideMode,
    selectedPackages,
    pickupAddress,
    pickupCoords,
    tripType,
    setTripType,
    rideMode,
    setRideMode,
    travelDate,
    setTravelDate,
    scheduledAt,
    setScheduledAt,
    passengers,
    setPassengers,
    selectedVehicleId,
    setSelectedVehicleId,
    scheduleError,
    setScheduleError,
    travelDateInputRef,
    scheduledAtInputRef,
    minTravelDate,
    maxTravelDate,
    minScheduledAt,
    maxScheduledAt,
    vehicles,
    selectedVehicle,
    finalFare,
    configuredBidStepAmount,
    configuredBidHighPercentage,
    openPicker,
    handleContinue,
    pad,
    formatDateInputValue,
    formatDateTimeInputValue,
    getTomorrowLocalDateTime,
    DEFAULT_BID_STEP_AMOUNT,
    DEFAULT_BID_HEADROOM_PERCENT,
    toConfiguredPositiveInteger,
    clampPercentage,
    alignBidAmountToStep,
    getTodayLocalDate,
    getMaxAdvanceDate,
    getMaxAdvanceDateTime,
    getVehicleIcon,
    normalizeVehicleEntry,
    calculateFare,
    calculateDefaultBidCeiling,
    getDisplayDate,
  }
}
