// Generated by tools/extract-hook.js from Frontend/src/modules/Taxi/modules/user/pages/ride/SelectVehicle.jsx (SelectVehicle), then edited by hand
// where the web code touched the DOM. The logic is the web page's own.
/* eslint-disable react-hooks/exhaustive-deps, no-unused-vars, no-empty */
import React, { useEffect, useMemo, useRef, useState } from 'react'
import { useNavigate, useLocation } from '../../lib/webRouter'
import { Banknote, CreditCard } from 'lucide-react-native'
import api from '../api/client'
import { HAS_VALID_GOOGLE_MAPS_KEY, useBaseGoogleMapsLoader } from '../utils/googleMaps'
import { computeDrivingRoute, sumComputedRouteLegs } from '../utils/googleRoutes'
import { userService } from '../services/userService'
import { useSettings } from '../context/SettingsContext'
import { DEFAULT_COORDS, DEFAULT_PLACE } from '../constants/districtPlaces'
import { getTaxiUserRoutePrefix } from '../utils/routePrefix'
import { localStore } from '../../lib/storage'
import { window, document } from '../../lib/webShim'

const BikeIcon = require('../../../assets/taxi/icons/bike.png')
const AutoIcon = require('../../../assets/taxi/icons/auto.png')
const CarIcon = require('../../../assets/taxi/icons/car.png')
const PremiumIcon = require('../../../assets/taxi/icons/Premium.png')
const LuxuryIcon = require('../../../assets/taxi/icons/Luxury.png')
const SuvIcon = require('../../../assets/taxi/icons/SUV.png')
const TruckIcon = require('../../../assets/taxi/icons/truck.png')
const LcvIcon = require('../../../assets/taxi/icons/LCV.png')
const McvIcon = require('../../../assets/taxi/icons/mcv.png')
const HcvIcon = require('../../../assets/taxi/icons/hcv.png')
const EhcvIcon = require('../../../assets/taxi/icons/ehcv.png')
const ScootyIcon = require('../../../assets/taxi/icons/bike.png') // scooty.png is damaged in the web repo
const HatchbackIcon = require('../../../assets/taxi/icons/Hatchback.png')
const BusIcon = require('../../../assets/taxi/icons/car.png') // bus.png is damaged in the web repo
const MiniBusIcon = require('../../../assets/taxi/icons/car.png') // mini_bus.png is damaged in the web repo
const MAP_CONTAINER_STYLE = { width: '100%', height: '100%' };

const SELECT_VEHICLE_MAP_OPTIONS = {
  disableDefaultUI: true,
  zoomControl: true,
  clickableIcons: false,
  streetViewControl: false,
  fullscreenControl: false,
  mapTypeControl: false,
  gestureHandling: 'greedy',
};

const toLatLng = (coords, fallback = { lat: 22.7196, lng: 75.8577 }) => {
  const [lng, lat] = coords || [];

  if (Number.isFinite(Number(lat)) && Number.isFinite(Number(lng))) {
    return { lat: Number(lat), lng: Number(lng) };
  }

  return fallback;
};

const getDriverPosition = (driver) => toLatLng(driver?.location?.coordinates, null);

const getOverlayCenterOffset = (width = 56, height = 56) => ({
  x: -(width / 2),
  y: -(height / 2),
});

const getMarkerDimensionsForZoom = (zoom) => {
  const normalizedZoom = Number.isFinite(Number(zoom)) ? Number(zoom) : 13;

  if (normalizedZoom <= 10) {
    return { shell: 76, pulse: 52, icon: 42 };
  }

  if (normalizedZoom <= 11) {
    return { shell: 70, pulse: 48, icon: 38 };
  }

  if (normalizedZoom <= 12) {
    return { shell: 64, pulse: 44, icon: 35 };
  }

  if (normalizedZoom <= 13) {
    return { shell: 58, pulse: 40, icon: 32 };
  }

  return { shell: 54, pulse: 36, icon: 30 };
};

const normalizeHeading = (value) => {
  const numeric = Number(value);

  if (!Number.isFinite(numeric)) {
    return 0;
  }

  return ((numeric % 360) + 360) % 360;
};

const calculateHeadingBetween = (from, to) => {
  if (!from || !to) {
    return 0;
  }

  const angle = Math.atan2(Number(to.lat || 0) - Number(from.lat || 0), Number(to.lng || 0) - Number(from.lng || 0));
  return normalizeHeading((angle * 180) / Math.PI + 90);
};

const buildFallbackRoute = (origin, destination) => {
  if (!origin || !destination) {
    return [];
  }

  const latDelta = destination.lat - origin.lat;
  const lngDelta = destination.lng - origin.lng;
  const bendScale = Math.abs(latDelta) > Math.abs(lngDelta) ? 0.28 : -0.28;
  const latBend = latDelta * bendScale;
  const lngBend = lngDelta * bendScale;

  return [
    origin,
    { lat: origin.lat + latDelta * 0.18, lng: origin.lng + lngDelta * 0.08 },
    { lat: origin.lat + latDelta * 0.36 + latBend, lng: origin.lng + lngDelta * 0.34 - lngBend },
    { lat: origin.lat + latDelta * 0.62 - latBend, lng: origin.lng + lngDelta * 0.58 + lngBend },
    { lat: origin.lat + latDelta * 0.84, lng: origin.lng + lngDelta * 0.9 },
    destination,
  ];
};

const getRouteCacheKey = (origin, destination, waypoints = []) => {
  const serializePoint = (point) =>
    point
      ? `${Number(point.lat || 0).toFixed(5)},${Number(point.lng || 0).toFixed(5)}`
      : '';

  const serializeWaypoint = (waypoint) => String(waypoint?.location || '').trim().toLowerCase();
  return [
    serializePoint(origin),
    serializePoint(destination),
    ...waypoints.map(serializeWaypoint),
  ].join('|');
};

const unwrap = (response) => response?.data?.data || response?.data || response;

const PAYMENT_OPTIONS = [
  { id: 'cash', stateValue: 'Cash', label: 'Cash', sub: 'Pay after ride', Icon: Banknote, bg: 'bg-green-50', color: 'text-green-600' },
  { id: 'online', stateValue: 'Online Payment', label: 'Online Payment', sub: 'UPI, Cards or Wallets', Icon: CreditCard, bg: 'bg-blue-50', color: 'text-blue-600' },
];

const DEFAULT_AVAILABILITY = {
  drivers: [],
  totalDrivers: 0,
  closestDriverDistanceMeters: null,
  closestDriverEtaMinutes: null,
  allowedPaymentMethods: ['cash', 'online'],
};

const normalizeAllowedPaymentMethods = (value) => {
  const items = Array.isArray(value) ? value : [];
  const normalized = items
    .map((item) => String(item || '').trim().toLowerCase())
    .map((item) => (item === 'cash' ? 'cash' : item === 'online' ? 'online' : null))
    .filter(Boolean);

  return [...new Set(normalized)].length ? [...new Set(normalized)] : ['cash', 'online'];
};

const attachDriverMotionMetadata = (drivers = [], previousDrivers = []) => {
  const previousById = new Map(
    (Array.isArray(previousDrivers) ? previousDrivers : []).map((driver) => [String(driver?.id || driver?._id || ''), driver]),
  );

  return (Array.isArray(drivers) ? drivers : []).map((driver, index) => {
    const key = String(driver?.id || driver?._id || index);
    const previousDriver = previousById.get(key);
    const currentPosition = getDriverPosition(driver);
    const previousPosition = getDriverPosition(previousDriver);
    const derivedHeading = calculateHeadingBetween(previousPosition, currentPosition);
    const heading = Number.isFinite(Number(driver?.heading))
      ? normalizeHeading(driver.heading)
      : previousPosition && currentPosition
        ? derivedHeading
        : normalizeHeading(previousDriver?.heading ?? 90 + index * 16);

    return {
      ...driver,
      heading,
    };
  });
};

const toPaymentStateValue = (methodId) => PAYMENT_OPTIONS.find((option) => option.id === methodId)?.stateValue || 'Cash';

const normalizeSelectedPaymentState = (value) => String(value || '').trim().toLowerCase() === 'cash' ? 'cash' : 'online';

const resolveRideTransportType = (...values) => {
  for (const value of values) {
    const normalized = String(value || '').trim().toLowerCase();

    if (!normalized) continue;
    if (normalized === 'both' || normalized === 'all') continue;
    return normalized;
  }

  return 'taxi';
};

const getVehicleTypes = (response) => {
  const data = unwrap(response);
  return data?.vehicle_types || data?.results || (Array.isArray(data) ? data : []);
};

const getTypeLabel = (type) => type?.name || type?.vehicle_type || type?.label || 'Vehicle';

const getIconValue = (type) => String(type?.icon_types || type?.vehicleIconType || type?.name || '').toLowerCase();

const getVehicleMapIcon = (type) => {
  const customIcon = String(type?.map_icon || type?.icon || type?.vehicleIconUrl || '').trim();
  if (customIcon) {
    return customIcon;
  }

  const value = getIconValue(type);

  if (value.includes('scooty')) {
    return '/scooty.png';
  }

  if (value.includes('car_5_seater')) {
    return '/Hatchback.png';
  }

  if (value.includes('car_7_seater')) {
    return '/SUV.png';
  }

  if (value.includes('mini_bus') || value.includes('minibus')) {
    return '/mini_bus.png';
  }

  if (value.includes('bus')) {
    return '/bus.png';
  }

  if (value.includes('bike')) {
    return '/1_Bike.png';
  }

  if (value.includes('auto')) {
    return '/2_AutoRickshaw.png';
  }

  if (value.includes('ehc')) {
    return '/ehcv.png';
  }

  if (value.includes('hcv')) {
    return '/hcv.png';
  }

  if (value.includes('lcv')) {
    return '/LCV.png';
  }

  if (value.includes('mcv')) {
    return '/mcv.png';
  }

  if (value.includes('truck')) {
    return '/truck.png';
  }

  if (value.includes('lux')) {
    return '/Luxury.png';
  }

  if (value.includes('premium')) {
    return '/Premium.png';
  }

  if (value.includes('suv')) {
    return '/SUV.png';
  }

  return '/4_Taxi.png';
};

const getVehiclePreviewImage = (type) => {
  const previewImage = String(type?.image || type?.preview_image || type?.previewImage || '').trim();
  if (previewImage) {
    return previewImage;
  }

  const value = getIconValue(type);

  if (value.includes('scooty')) return ScootyIcon;
  if (value.includes('car_5_seater')) return HatchbackIcon;
  if (value.includes('car_7_seater')) return SuvIcon;
  if (value.includes('mini_bus') || value.includes('minibus')) return MiniBusIcon;
  if (value.includes('bus')) return BusIcon;
  if (value.includes('bike')) return BikeIcon;
  if (value.includes('auto')) return AutoIcon;
  if (value.includes('ehc')) return EhcvIcon;
  if (value.includes('hcv')) return HcvIcon;
  if (value.includes('lcv')) return LcvIcon;
  if (value.includes('mcv')) return McvIcon;
  if (value.includes('truck')) return TruckIcon;
  if (value.includes('lux')) return LuxuryIcon;
  if (value.includes('premium')) return PremiumIcon;
  if (value.includes('suv')) return SuvIcon;

  return CarIcon;
};

const getCapacity = (type) => {
  const value = getIconValue(type);

  if (value.includes('scooty')) {
    return 1;
  }

  if (value.includes('bus') && !value.includes('mini')) {
    return 40;
  }

  if (value.includes('mini_bus') || value.includes('minibus')) {
    return 15;
  }

  if (value.includes('car_7_seater')) {
    return 7;
  }

  if (value.includes('car_5_seater')) {
    return 5;
  }

  if (value.includes('bike')) {
    return 1;
  }

  if (value.includes('auto')) {
    return 3;
  }

  if (value.includes('suv')) {
    return 6;
  }

  return 4;
};

const AVERAGE_CITY_SPEED_KMPH = 24;

const calculateDistanceMeters = (fromCoords = [], toCoords = []) => {
  const [fromLng, fromLat] = fromCoords;
  const [toLng, toLat] = toCoords;

  if (![fromLng, fromLat, toLng, toLat].every((value) => Number.isFinite(Number(value)))) {
    return 0;
  }

  const toRadians = (value) => (Number(value) * Math.PI) / 180;
  const earthRadiusMeters = 6371000;
  const latDelta = toRadians(toLat - fromLat);
  const lngDelta = toRadians(toLng - fromLng);
  const startLat = toRadians(fromLat);
  const endLat = toRadians(toLat);
  const a =
    Math.sin(latDelta / 2) ** 2 +
    Math.cos(startLat) * Math.cos(endLat) * Math.sin(lngDelta / 2) ** 2;
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));

  return Math.round(earthRadiusMeters * c);
};

const estimateDurationMinutes = (distanceMeters = 0) => {
  if (!Number.isFinite(Number(distanceMeters)) || Number(distanceMeters) <= 0) {
    return 0;
  }

  const metersPerMinute = (AVERAGE_CITY_SPEED_KMPH * 1000) / 60;
  return Math.max(1, Math.round(Number(distanceMeters) / metersPerMinute));
};

const getFallbackVehicleEstimate = (type) => {
  const value = getIconValue(type);
  const label = getTypeLabel(type).toLowerCase();

  if (value.includes('bike') || label.includes('bike')) {
    return 22;
  }

  if (value.includes('auto') || label.includes('auto')) {
    return 40;
  }

  if (value.includes('premium') || value.includes('lux') || label.includes('premium') || label.includes('lux')) {
    return 130;
  }

  if (value.includes('suv') || label.includes('suv')) {
    return 150;
  }

  return 106;
};

const getSetPriceRows = (response) => {
  const data = unwrap(response);
  return (data?.paginator?.data || data?.results || []).filter((row) => {
    const scope = String(row?.pricing_scope || 'ride').trim().toLowerCase();
    return scope === 'ride';
  });
};

const getSetPricePaginationMeta = (response) => {
  const data = unwrap(response);
  return {
    currentPage: Number(data?.current_page || data?.paginator?.current_page || 1) || 1,
    lastPage: Number(data?.last_page || data?.paginator?.last_page || 1) || 1,
  };
};

const normalizeId = (value) => String(value?._id || value?.id || value || '').trim();

const getZoneServiceLocationId = (zone) => normalizeId(
  zone?.service_location_id?._id
  || zone?.service_location_id?.id
  || zone?.service_location_id
  || zone?.service_location?._id
  || zone?.service_location?.id
  || zone?.service_location
  || '',
);

const getZoneId = (zone) => normalizeId(zone?._id || zone?.id || '');

const isZoneActive = (zone) => zone?.active !== false && Number(zone?.status ?? 1) !== 0 && String(zone?.status || '').toLowerCase() !== 'inactive';

const toZonePoint = (point) => {
  if (Array.isArray(point) && point.length >= 2) {
    const [lng, lat] = point;
    if (Number.isFinite(Number(lat)) && Number.isFinite(Number(lng))) {
      return { lat: Number(lat), lng: Number(lng) };
    }
  }

  if (point && typeof point === 'object') {
    const lat = Number(point.lat ?? point.latitude);
    const lng = Number(point.lng ?? point.longitude ?? point.lon);
    if (Number.isFinite(lat) && Number.isFinite(lng)) {
      return { lat, lng };
    }
  }

  return null;
};

const normalizeZonePath = (zone) => {
  const source = Array.isArray(zone?.coordinates?.[0]) && Array.isArray(zone?.coordinates?.[0]?.[0])
    ? zone.coordinates[0]
    : zone?.coordinates;

  if (!Array.isArray(source)) {
    return [];
  }

  return source.map(toZonePoint).filter(Boolean);
};

const isPointInPolygon = (point, polygon) => {
  if (!point || polygon.length < 3) {
    return false;
  }

  let inside = false;
  for (let i = 0, j = polygon.length - 1; i < polygon.length; j = i++) {
    const xi = polygon[i].lng;
    const yi = polygon[i].lat;
    const xj = polygon[j].lng;
    const yj = polygon[j].lat;
    const intersects = ((yi > point.lat) !== (yj > point.lat))
      && (point.lng < ((xj - xi) * (point.lat - yi)) / ((yj - yi) || Number.EPSILON) + xi);

    if (intersects) {
      inside = !inside;
    }
  }

  return inside;
};

const toFiniteNumber = (value, fallback = 0) => {
  const numeric = Number(value);
  return Number.isFinite(numeric) ? numeric : fallback;
};

const getRuleServiceLocationId = (rule) => normalizeId(
  rule?.service_location_id?._id
  || rule?.service_location_id?.id
  || rule?.service_location_id
  || rule?.zone?.service_location?._id
  || rule?.zone?.service_location?.id
  || rule?.zone?.service_location_id
  || '',
);

const getRuleZoneId = (rule) => normalizeId(
  rule?.zone_id?._id
  || rule?.zone_id?.id
  || rule?.zone_id
  || rule?.zone?._id
  || rule?.zone?.id
  || rule?.zone
  || '',
);

const sortPricingRules = (rules = []) => (
  [...rules].sort((first, second) => {
    const firstUpdatedAt = new Date(first?.updatedAt || first?.createdAt || 0).getTime();
    const secondUpdatedAt = new Date(second?.updatedAt || second?.createdAt || 0).getTime();
    return secondUpdatedAt - firstUpdatedAt;
  })
);

const isActiveRidePricingRule = (rule) => {
  const isActive = Number(rule?.active ?? 1) === 1 && String(rule?.status || 'active').toLowerCase() !== 'inactive';
  const scope = String(rule?.pricing_scope || 'ride').trim().toLowerCase();
  return isActive && scope === 'ride';
};

const matchesTransportType = (rule, transportType) => {
  const normalizedRuleTransport = String(rule?.transport_type || 'taxi').trim().toLowerCase();
  const normalizedTransportType = String(transportType || 'taxi').trim().toLowerCase() || 'taxi';

  return normalizedRuleTransport === normalizedTransportType
    || normalizedRuleTransport === 'both';
};

const findBestPricingRule = ({ rules, vehicleTypeId, zoneId, serviceLocationId, transportType }) => {
  const normalizedVehicleTypeId = normalizeId(vehicleTypeId);
  const normalizedZoneId = normalizeId(zoneId);
  const normalizedServiceLocationId = normalizeId(serviceLocationId);
  const normalizedTransportType = String(transportType || 'taxi').trim().toLowerCase() || 'taxi';

  const candidates = sortPricingRules(rules.filter((rule) => {
    const matchesVehicle = normalizeId(rule?.vehicle_type?._id || rule?.vehicle_type || rule?.type_id) === normalizedVehicleTypeId;
    return matchesVehicle && isActiveRidePricingRule(rule) && matchesTransportType(rule, normalizedTransportType);
  }));

  if (!candidates.length) {
    return null;
  }

  const exactTransportMatch = (rule) => String(rule?.transport_type || 'taxi').trim().toLowerCase() === normalizedTransportType;
  const exactZone = candidates.find((rule) => (
    normalizedZoneId
    && getRuleZoneId(rule) === normalizedZoneId
    && exactTransportMatch(rule)
  ));

  if (exactZone) {
    return exactZone;
  }

  const exactZoneAnyTransport = candidates.find((rule) => (
    normalizedZoneId && getRuleZoneId(rule) === normalizedZoneId
  ));

  if (exactZoneAnyTransport) {
    return exactZoneAnyTransport;
  }

  const exactServiceLocation = candidates.find((rule) => (
    normalizedServiceLocationId
    && getRuleServiceLocationId(rule) === normalizedServiceLocationId
    && exactTransportMatch(rule)
  ));

  if (exactServiceLocation) {
    return exactServiceLocation;
  }

  const exactServiceLocationAnyTransport = candidates.find((rule) => (
    normalizedServiceLocationId && getRuleServiceLocationId(rule) === normalizedServiceLocationId
  ));

  if (exactServiceLocationAnyTransport) {
    return exactServiceLocationAnyTransport;
  }

  const genericTransportMatch = candidates.find((rule) => (
    !getRuleServiceLocationId(rule) && !getRuleZoneId(rule) && exactTransportMatch(rule)
  ));

  if (genericTransportMatch) {
    return genericTransportMatch;
  }

  const genericBoth = candidates.find((rule) => !getRuleServiceLocationId(rule) && !getRuleZoneId(rule));
  if (genericBoth) {
    return genericBoth;
  }

  /*
   * No unscoped row exists for this vehicle type, and none of its scoped rows
   * matched this ride's zone or service location exactly. The server's own
   * resolver (resolveSetPriceForRide) has no such veto — its last filter is
   * `{ vehicle_type, transport_type }` alone, so it will price this ride
   * against a scoped row from a different zone/location rather than leave it
   * unpriced. Refusing here just means the rider is quoted the flat fallback
   * while the server bills the real tariff, and the mismatch gets the ride
   * rejected at booking. Matching the server's own fallback keeps the two in
   * agreement.
   */
  const anyExactTransportMatch = candidates.find((rule) => exactTransportMatch(rule));
  if (anyExactTransportMatch) {
    return anyExactTransportMatch;
  }

  return candidates[0] || null;
};

const calculateEstimatedFare = ({ vehicle, pricingRule, distanceMeters, durationMinutes }) => {
  const fallbackFare = getFallbackVehicleEstimate(vehicle?.raw || vehicle);

  if (!pricingRule) {
    return fallbackFare;
  }

  const distanceKm = Math.max(0, Number(distanceMeters || 0) / 1000);
  const basePrice = toFiniteNumber(pricingRule.base_price, 0);
  const baseDistance = Math.max(0, toFiniteNumber(pricingRule.base_distance, 0));
  const pricePerDistance = toFiniteNumber(pricingRule.price_per_distance, 0);
  const timePrice = toFiniteNumber(pricingRule.time_price, 0);
  const serviceTax = toFiniteNumber(pricingRule.service_tax, 0);
  const isWithinBaseDistance = baseDistance > 0 && distanceKm <= baseDistance;
  const extraDistanceKm = Math.max(0, distanceKm - baseDistance);
  const subtotal = isWithinBaseDistance
    ? basePrice
    : basePrice + (extraDistanceKm * pricePerDistance) + (Math.max(0, Number(durationMinutes || 0)) * timePrice);

  if (subtotal <= 0) {
    return fallbackFare;
  }

  const total = subtotal + (subtotal * serviceTax) / 100;
  return Math.max(0, Math.round(total));
};

const getDropTime = (minutesAway = 0) => {
  const safeMinutes = Math.max(6, Number(minutesAway) || 0);
  const date = new Date(Date.now() + safeMinutes * 60 * 1000);
  return date.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', hour12: false });
};

const formatDistanceLabel = (distanceMeters) => {
  if (!Number.isFinite(Number(distanceMeters))) {
    return 'No distance yet';
  }

  const meters = Number(distanceMeters);

  if (meters < 1000) {
    return `${Math.max(50, Math.round(meters / 10) * 10)} m`;
  }

  return `${(meters / 1000).toFixed(meters >= 10000 ? 0 : 1)} km`;
};

const formatCurrency = (amount) => `₹${Math.round(Number(amount) || 0)}`;

const formatPromoSummary = (promo) => {
  const percent = Math.max(0, Number(promo?.discount_percentage || 0));
  const maxDiscount = Math.max(0, Number(promo?.maximum_discount_amount || 0));
  const minimumTripAmount = Math.max(0, Number(promo?.minimum_trip_amount || 0));

  const parts = [];
  if (percent > 0) {
    parts.push(`${percent}% off`);
  }
  if (maxDiscount > 0) {
    parts.push(`up to ${formatCurrency(maxDiscount)}`);
  }
  if (minimumTripAmount > 0) {
    parts.push(`min ${formatCurrency(minimumTripAmount)}`);
  }

  return parts.join(' • ') || 'Promo available';
};

const toConfiguredPositiveInteger = (value, fallback) => {
  const numeric = Number(value);
  return Number.isFinite(numeric) && numeric > 0 ? Math.round(numeric) : fallback;
};

const clampPercentage = (value, fallback = 0) => {
  const numeric = Number(value);
  if (!Number.isFinite(numeric)) {
    return fallback;
  }

  return Math.max(0, Math.min(100, numeric));
};

const alignBidAmountToStep = ({ baseFare, amount, stepAmount, direction = 'up' }) => {
  const safeBaseFare = Math.max(0, Math.round(Number(baseFare || 0)));
  const safeStepAmount = toConfiguredPositiveInteger(stepAmount, 10);
  const safeAmount = Math.max(0, Math.round(Number(amount || 0)));
  const delta = safeAmount - safeBaseFare;

  if (delta === 0) {
    return safeBaseFare;
  }

  const absoluteDelta = Math.abs(delta);
  const rawSteps = absoluteDelta / safeStepAmount;
  const normalizedSteps = direction === 'down' ? Math.floor(rawSteps) : Math.ceil(rawSteps);
  return Math.max(0, safeBaseFare + (Math.sign(delta) * normalizedSteps * safeStepAmount));
};

const getBidFareBounds = (vehicle, stepCount) => {
  const baseFare = Math.max(0, Math.round(Number(vehicle?.price) || 0));
  const maxSteps = Math.max(0, Number(vehicle?.maxBidSteps) || 0);
  const safeStepCount = Math.min(
    maxSteps,
    Math.max(0, Number.isFinite(Number(stepCount)) ? Number(stepCount) : maxSteps),
  );
  const stepAmount = Math.max(0, Math.round(Number(vehicle?.bidStepAmount) || 0));

  return {
    min: baseFare,
    max: baseFare + (safeStepCount * stepAmount),
  };
};

const formatVehicleFare = (vehicle, stepCount) => {
  if (!vehicle?.supportsBidding) {
    return formatCurrency(vehicle?.price);
  }

  const { min, max } = getBidFareBounds(vehicle, stepCount);
  return `${formatCurrency(min)}-${formatCurrency(max)}`;
};

const pad = (value) => String(value).padStart(2, '0');

const formatDateTimeInputValue = (date) => {
  const year = date.getFullYear();
  const month = pad(date.getMonth() + 1);
  const day = pad(date.getDate());
  const hours = pad(date.getHours());
  const minutes = pad(date.getMinutes());
  return `${year}-${month}-${day}T${hours}:${minutes}`;
};

const getMinScheduledDateTime = () => {
  const next = new Date(Date.now() + 60 * 60 * 1000);
  return formatDateTimeInputValue(next);
};

const getMaxScheduledDateTime = () => {
  const nextWeek = new Date();
  nextWeek.setDate(nextWeek.getDate() + 7);
  return formatDateTimeInputValue(nextWeek);
};

const formatScheduledDisplay = (value) => {
  if (!value) {
    return 'Pick date & time';
  }

  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return 'Pick date & time';
  }

  return parsed.toLocaleString('en-IN', {
    day: '2-digit',
    month: 'short',
    hour: '2-digit',
    minute: '2-digit',
  });
};

const formatAvailabilityLine = (availability) => {
  if (!availability?.totalDrivers) {
    return 'Not available right now';
  }

  const etaMinutes = availability.closestDriverEtaMinutes || 1;
  const dropTime = getDropTime(etaMinutes + 10);
  return `Closest driver ${formatDistanceLabel(availability.closestDriverDistanceMeters)} away - ${etaMinutes} mins away - Drop ${dropTime}`;
};

const formatDispatchLabel = (vehicle) => {
  if (vehicle?.supportsBidding) {
    return 'Bid or instant booking';
  }

  const dispatchType = String(vehicle?.dispatchType || '').toLowerCase();
  if (dispatchType === 'bidding') {
    return 'Bid booking';
  }

  return 'Instant booking';
};

const getAvailabilityBadge = (availability) => {
  if (!availability?.totalDrivers) {
    return 'NOT AVAILABLE';
  }

  if ((availability.closestDriverEtaMinutes || Number.POSITIVE_INFINITY) <= 2) {
    return 'FASTEST';
  }

  if (availability.totalDrivers >= 5) {
    return 'POPULAR';
  }

  return null;
};

const getNormalizedCategory = (type) => {
  const cat = String(type?.category || '').trim().toLowerCase();
  if (cat) {
    if (cat.includes('car')) return 'car';
    if (cat.includes('bike') || cat.includes('scooty')) return 'bike';
    if (cat.includes('auto')) return 'auto';
    return cat;
  }

  const icon = String(type?.icon_types || '').trim().toLowerCase();
  if (icon.includes('bike') || icon.includes('scooty')) return 'bike';
  if (icon.includes('auto')) return 'auto';
  return 'car';
};

const normalizeVehicleType = (type, index) => {
  const id = String(type?._id || type?.id || type?.name || index);
  const dispatchType = String(type?.dispatch_type || 'normal').trim().toLowerCase();

  return {
    id,
    vehicleTypeId: type?._id || type?.id || '',
    transportType: String(type?.transport_type || 'taxi').trim().toLowerCase() || 'taxi',
    iconType: type?.icon_types || 'car',
    category: getNormalizedCategory(type),
    icon: getVehiclePreviewImage(type),
    vehicleIconUrl: getVehicleMapIcon(type),
    name: getTypeLabel(type),
    capacity: getCapacity(type),
    badge: null,
    badgeColor: 'bg-orange-50 text-orange-500 border-orange-100',
    sublabel: type?.short_description || type?.description || 'Available ride',
    price: getFallbackVehicleEstimate(type),
    dispatchType,
    supportsBidding: dispatchType === 'bidding' || dispatchType === 'both',
    bidStepAmount: 10,
    maxBidSteps: 5,
    raw: type,
  };
};

const createHistorySafeVehicle = (vehicle) => {
  if (!vehicle) {
    return null;
  }

  return {
    id: vehicle.id,
    vehicleTypeId: vehicle.vehicleTypeId,
    transportType: vehicle.transportType,
    iconType: vehicle.iconType,
    icon: vehicle.icon,
    vehicleIconUrl: vehicle.vehicleIconUrl,
    name: vehicle.name,
    capacity: vehicle.capacity,
    badge: vehicle.badge,
    badgeColor: vehicle.badgeColor,
    sublabel: vehicle.sublabel,
    price: vehicle.price,
    dispatchType: vehicle.dispatchType,
    supportsBidding: vehicle.supportsBidding,
    bidStepAmount: vehicle.bidStepAmount,
    maxBidSteps: vehicle.maxBidSteps,
  };
};

export function useSelectVehicle() {
  const location = useLocation();
  const searchParams = new URLSearchParams(location.search);
  const queryVehicleType = searchParams.get('vehicleType') || '';
  const localVehicleType = true ? (localStore.getItem('selectedVehicleType') || '') : '';
  const routeState = location.state || {};
  const [vehicles, setVehicles] = useState([]);
  const [availabilityByVehicleId, setAvailabilityByVehicleId] = useState({});
  const [selected, setSelected] = useState('');
  const [paymentMethod, setPaymentMethod] = useState('Cash');
  const [showPaymentModal, setShowPaymentModal] = useState(false);
  const [showCouponModal, setShowCouponModal] = useState(false);
  const [showBidModal, setShowBidModal] = useState(false);
  const [previewVehicleId, setPreviewVehicleId] = useState('');
  const [availablePromos, setAvailablePromos] = useState([]);
  const [isLoadingPromos, setIsLoadingPromos] = useState(false);
  const [promoCodeInput, setPromoCodeInput] = useState('');
  const [promoFeedback, setPromoFeedback] = useState('');
  const [promoError, setPromoError] = useState('');
  const [applyingPromoCode, setApplyingPromoCode] = useState('');
  const [appliedPromo, setAppliedPromo] = useState(null);
  const [rideMode, setRideMode] = useState(() => (location.state?.rideMode === 'schedule' ? 'schedule' : 'now'));
  const [scheduledAt, setScheduledAt] = useState(() => (
    location.state?.scheduledAt ? String(location.state.scheduledAt).slice(0, 16) : getMinScheduledDateTime()
  ));
  const [scheduleError, setScheduleError] = useState('');
  const [bidStepCount, setBidStepCount] = useState(2);
  const [isLoadingVehicles, setIsLoadingVehicles] = useState(true);
  const [isLoadingDrivers, setIsLoadingDrivers] = useState(false);
  const [vehicleLoadError, setVehicleLoadError] = useState('');
  const [driverLoadError, setDriverLoadError] = useState('');
  const [pricingRules, setPricingRules] = useState([]);
  const [isLoadingPricingRules, setIsLoadingPricingRules] = useState(true);
  const [tripMetrics, setTripMetrics] = useState(() => {
    if (
      Number.isFinite(Number(routeState?.estimatedDistanceMeters))
      && Number.isFinite(Number(routeState?.estimatedDurationMinutes))
    ) {
      return {
        distanceMeters: Number(routeState.estimatedDistanceMeters),
        durationMinutes: Number(routeState.estimatedDurationMinutes),
      };
    }

    const fallbackDistanceMeters = calculateDistanceMeters(
      routeState?.pickupCoords || DEFAULT_COORDS,
      routeState?.dropCoords || DEFAULT_COORDS,
    );

    return {
      distanceMeters: fallbackDistanceMeters,
      durationMinutes: estimateDurationMinutes(fallbackDistanceMeters),
    };
  });
  const routeMetricsCacheRef = useRef(new Map());
  const [isResolvingTripMetrics, setIsResolvingTripMetrics] = useState(true);
  const [showScrollArrow, setShowScrollArrow] = useState(false);
  const scrollRef = React.useRef({ scrollTop: 0, scrollHeight: 0, clientHeight: 0 });
  const availabilityHistoryRef = useRef({});
  const selectedVehicleIdRef = useRef('');
  const scheduledAtInputRef = useRef(null);
  const navigate = useNavigate();
  const { settings } = useSettings();
  const pickup = routeState.pickup || DEFAULT_PLACE.address;
  const drop = routeState.drop || '';
  const pickupCoords = useMemo(() => routeState.pickupCoords || DEFAULT_COORDS, [routeState.pickupCoords]);
  const dropCoords = useMemo(() => routeState.dropCoords || DEFAULT_COORDS, [routeState.dropCoords]);
  const stops = useMemo(
    () => (Array.isArray(routeState.stops) ? routeState.stops : []),
    [routeState.stops],
  );
  const routeServiceLocationId = routeState.service_location_id || routeState.serviceLocationId || '';
  const routeZoneId = routeState.zone_id || routeState.zoneId || '';
  const hasCompleteRouteZoneContext = Boolean(routeServiceLocationId && routeZoneId);
  const [resolvedServiceLocationId, setResolvedServiceLocationId] = useState(routeServiceLocationId);
  const [resolvedZoneId, setResolvedZoneId] = useState(routeZoneId);
  const [isResolvingServiceLocation, setIsResolvingServiceLocation] = useState(!hasCompleteRouteZoneContext);
  const [hasLoadedAvailability, setHasLoadedAvailability] = useState(false);
  const serviceLocationId = hasCompleteRouteZoneContext
    ? (resolvedServiceLocationId || routeServiceLocationId || '')
    : resolvedServiceLocationId;
  const zoneId = hasCompleteRouteZoneContext
    ? (resolvedZoneId || routeZoneId || '')
    : resolvedZoneId;
  const routePrefix = getTaxiUserRoutePrefix(location.pathname);
  const pickupPosition = useMemo(() => toLatLng(pickupCoords), [pickupCoords]);
  const dropPosition = useMemo(() => toLatLng(dropCoords, null), [dropCoords]);
  const { isLoaded: isMapLoaded, loadError: mapLoadError } = useBaseGoogleMapsLoader();
  const minScheduledAt = useMemo(() => getMinScheduledDateTime(), []);
  const maxScheduledAt = useMemo(() => getMaxScheduledDateTime(), []);

  useEffect(() => {
    if (hasCompleteRouteZoneContext) {
      setResolvedServiceLocationId(routeServiceLocationId);
      setResolvedZoneId(routeZoneId);
      setIsResolvingServiceLocation(false);
      return;
    }

    setResolvedServiceLocationId('');
    setResolvedZoneId('');
    setIsResolvingServiceLocation(true);
  }, [hasCompleteRouteZoneContext, routeServiceLocationId, routeZoneId]);

  useEffect(() => {
    let active = true;

    const resolveServiceLocationFromPickup = async () => {
      if (hasCompleteRouteZoneContext) {
        if (active) {
          setIsResolvingServiceLocation(false);
        }
        return;
      }

      if (!Array.isArray(pickupCoords) || pickupCoords.length !== 2) {
        if (active) {
          setIsResolvingServiceLocation(false);
        }
        return;
      }

      if (active) {
        setIsResolvingServiceLocation(true);
      }

      try {
        const response = await api.get('/users/zones');
        if (!active) {
          return;
        }

        const payload = unwrap(response);
        const zones = payload?.results || payload?.zones || payload?.paginator?.data || (Array.isArray(payload) ? payload : []);
        const pickupPoint = { lat: Number(pickupCoords[1]), lng: Number(pickupCoords[0]) };
        const matchedZone = [...(Array.isArray(zones) ? zones : [])]
          .filter((zone) => isZoneActive(zone))
          .map((zone) => ({ zone, path: normalizeZonePath(zone) }))
          .filter(({ path }) => isPointInPolygon(pickupPoint, path))
          .sort((left, right) => {
            const leftUpdatedAt = new Date(left.zone?.updatedAt || left.zone?.createdAt || 0).getTime();
            const rightUpdatedAt = new Date(right.zone?.updatedAt || right.zone?.createdAt || 0).getTime();
            return rightUpdatedAt - leftUpdatedAt;
          })[0]?.zone;

        const nextZoneId = getZoneId(matchedZone);
        const nextServiceLocationId = getZoneServiceLocationId(matchedZone);
        setResolvedZoneId(nextZoneId || '');
        setResolvedServiceLocationId(nextServiceLocationId || '');
      } catch {
        if (active) {
          setResolvedServiceLocationId('');
          setResolvedZoneId('');
        }
      } finally {
        if (active) {
          setIsResolvingServiceLocation(false);
        }
      }
    };

    resolveServiceLocationFromPickup();

    return () => {
      active = false;
    };
  }, [hasCompleteRouteZoneContext, pickupCoords]);

  // Native: scroll metrics come from the ScrollView's events (scrollRef.current holds them).
  const handleScroll = (event) => {
    const metrics = scrollRef.current || (scrollRef.current = { scrollTop: 0, scrollHeight: 0, clientHeight: 0 });
    const n = event?.nativeEvent;
    if (n?.contentOffset) metrics.scrollTop = n.contentOffset.y;
    if (n?.contentSize) metrics.scrollHeight = n.contentSize.height;
    if (n?.layoutMeasurement) metrics.clientHeight = n.layoutMeasurement.height;
    const { scrollTop, scrollHeight, clientHeight } = metrics;
    const hasMore = scrollTop + clientHeight < scrollHeight - 8;
    setShowScrollArrow(hasMore);
  };

  useEffect(() => {
    if (!scheduledAt) {
      return;
    }

    if (scheduledAt < minScheduledAt) {
      setScheduledAt(minScheduledAt);
      return;
    }

    if (scheduledAt > maxScheduledAt) {
      setScheduledAt(maxScheduledAt);
    }
  }, [maxScheduledAt, minScheduledAt, scheduledAt]);

  useEffect(() => {
    let active = true;

    const loadVehicleTypes = async () => {
      setIsLoadingVehicles(true);
      setVehicleLoadError('');

      try {
        const response = await api.get('/users/vehicle-types');

        if (!active) {
          return;
        }

        const categoryFilter = String(queryVehicleType || routeState?.selectedCategory || localVehicleType || '').trim().toLowerCase();
        let nextVehicles = getVehicleTypes(response)
          .filter((type) => {
            const isActive = type.active !== false && Number(type.status ?? 1) !== 0;
            const transportType = String(type.transport_type || 'taxi').toLowerCase();
            return isActive && (transportType === 'taxi' || transportType === 'both');
          })
          .map(normalizeVehicleType);

        if (categoryFilter) {
          nextVehicles = nextVehicles.filter((v) => {
            const vCat = v.category;
            if (categoryFilter === 'cab' && vCat === 'car') return true;
            if (categoryFilter === 'car' && vCat === 'cab') return true;
            return vCat === categoryFilter;
          });
        }


        const preselectedVehicle = nextVehicles[0] || null;

        setVehicles(nextVehicles);
        setSelected((current) => current || preselectedVehicle?.id || nextVehicles[0]?.id || '');
      } catch (err) {
        console.error('[SelectVehicle] Failed to load vehicles:', err);
        if (active) {
          setVehicleLoadError('Failed to load available vehicles for this area.');
        }
      } finally {
        if (active) {
          setIsLoadingVehicles(false);
        }
      }
    };

    loadVehicleTypes();

    return () => {
      active = false;
    };
  }, [isResolvingServiceLocation, queryVehicleType, routeState?.selectedCategory, localVehicleType, resolvedZoneId, resolvedServiceLocationId, routeState.transportType, routeState.transport_type, routeState.serviceType, hasCompleteRouteZoneContext]);

  useEffect(() => {
    let active = true;

    const loadPricingRules = async () => {
      if (isResolvingServiceLocation) {
        return;
      }

      setIsLoadingPricingRules(true);

      try {
        const aggregatedRules = [];
        let page = 1;
        let lastPage = 1;
        const pricingTransportType = resolveRideTransportType(
          routeState.transport_type,
          routeState.transportType,
          'taxi',
        );

        do {
          // No zone_id filter here: the backend's zone_id filter excludes any
          // service-location-scoped price row (zone_id: null), which is how
          // every real tariff in this DB is set up. findBestPricingRule()
          // below already does zone > service-location > generic matching
          // client-side, so filtering server-side by zone just drops the
          // correct row and pushes every fare onto the ₹22/₹40/... fallback.
          const response = await api.get('/users/set-prices', {
            params: {
              scope: 'ride',
              page,
              limit: 100,
              ...(pricingTransportType ? { transport_type: pricingTransportType } : {}),
            },
          });

          if (!active) {
            return;
          }

          aggregatedRules.push(...getSetPriceRows(response));
          const pagination = getSetPricePaginationMeta(response);
          lastPage = pagination.lastPage;
          page += 1;
        } while (page <= lastPage);

        if (!active) {
          return;
        }

        setPricingRules(aggregatedRules);
      } catch {
        if (active) {
          setPricingRules([]);
        }
      } finally {
        if (active) {
          setIsLoadingPricingRules(false);
        }
      }
    };

    loadPricingRules();

    return () => {
      active = false;
    };
  }, [isResolvingServiceLocation, routeState.transportType, routeState.transport_type, zoneId]);

  useEffect(() => {
    const fallbackDistanceMeters = calculateDistanceMeters(pickupCoords, dropCoords);
    const fallbackDurationMinutes = estimateDurationMinutes(fallbackDistanceMeters);

    if (!dropPosition) {
      setIsResolvingTripMetrics(false);
      setTripMetrics({
        distanceMeters: fallbackDistanceMeters,
        durationMinutes: fallbackDurationMinutes,
      });
      return;
    }

    if (mapLoadError || !HAS_VALID_GOOGLE_MAPS_KEY) {
      setIsResolvingTripMetrics(false);
      setTripMetrics({
        distanceMeters: fallbackDistanceMeters,
        durationMinutes: fallbackDurationMinutes,
      });
      return;
    }

    if (!isMapLoaded) {
      setIsResolvingTripMetrics(true);
      return;
    }

    const waypointRequests = stops
      .map((stop) => String(stop || '').trim())
      .filter(Boolean)
      .map((stop) => ({ location: stop, stopover: true }));
    const routeCacheKey = getRouteCacheKey(pickupPosition, dropPosition, waypointRequests);
    const cachedMetrics = routeMetricsCacheRef.current.get(routeCacheKey);
    if (cachedMetrics) {
      setIsResolvingTripMetrics(false);
      setTripMetrics(cachedMetrics);
      return;
    }

    let active = true;
    setIsResolvingTripMetrics(true);
    void (async () => {
      const result = await computeDrivingRoute({
        origin: pickupPosition,
        destination: dropPosition,
        intermediates: waypointRequests,
      });

      if (!active) {
        return;
      }

      const totals = sumComputedRouteLegs(result.legs);
      const distanceMeters = toFiniteNumber(totals.distanceMeters, fallbackDistanceMeters);
      const durationMinutes = Math.max(
        1,
        Math.round(toFiniteNumber(totals.durationSeconds, fallbackDurationMinutes * 60) / 60),
      );

      if (result.status === 'OK' && result.legs.length) {
        routeMetricsCacheRef.current.set(routeCacheKey, { distanceMeters, durationMinutes });
        setIsResolvingTripMetrics(false);
        setTripMetrics({ distanceMeters, durationMinutes });
        return;
      }

      routeMetricsCacheRef.current.set(routeCacheKey, {
        distanceMeters: fallbackDistanceMeters,
        durationMinutes: fallbackDurationMinutes,
      });
      setIsResolvingTripMetrics(false);
      setTripMetrics({
        distanceMeters: fallbackDistanceMeters,
        durationMinutes: fallbackDurationMinutes,
      });
    })();

    return () => {
      active = false;
    };
  }, [dropCoords, dropPosition, isMapLoaded, mapLoadError, pickupCoords, pickupPosition, stops]);

  const pricedVehicles = useMemo(
    () =>
      vehicles.map((vehicle) => {
        const pricingRule = findBestPricingRule({
          rules: pricingRules,
          vehicleTypeId: vehicle.vehicleTypeId,
          zoneId,
          serviceLocationId,
          transportType: resolveRideTransportType(
            routeState.transport_type,
            routeState.transportType,
            vehicle.transportType,
          ),
        });

        const calculatedPrice = calculateEstimatedFare({
          vehicle,
          pricingRule,
          distanceMeters: tripMetrics.distanceMeters,
          durationMinutes: tripMetrics.durationMinutes,
        });

        // Dynamically scale max bidding steps to a realistic 15% of the actual calculated price
        const stepAmount = Number(vehicle.bidStepAmount || 10);
        const dynamicMaxBidSteps = Math.max(2, Math.round((calculatedPrice * 0.15) / stepAmount));

        return {
          ...vehicle,
          pricingRule,
          price: calculatedPrice,
          maxBidSteps: dynamicMaxBidSteps,
        };
      }),
    [pricingRules, serviceLocationId, tripMetrics.distanceMeters, tripMetrics.durationMinutes, vehicles, zoneId],
  );

  const isFarePending = isResolvingTripMetrics || isLoadingPricingRules;

  const hasAvailabilityResults = Object.keys(availabilityByVehicleId).length > 0;

  const displayedVehicles = useMemo(() => {
    if (!hasLoadedAvailability) {
      return [];
    }

    if (!hasAvailabilityResults) {
      return pricedVehicles;
    }

    const rankedVehicles = pricedVehicles
      .map((vehicle, index) => ({
        ...vehicle,
        originalIndex: index,
        availability: availabilityByVehicleId[vehicle.id] || DEFAULT_AVAILABILITY,
      }))
      .sort((a, b) => {
        const aAvailable = (a.availability.totalDrivers || 0) > 0;
        const bAvailable = (b.availability.totalDrivers || 0) > 0;

        if (aAvailable !== bAvailable) {
          return aAvailable ? -1 : 1;
        }

        if (aAvailable && bAvailable) {
          const driverDelta = (b.availability.totalDrivers || 0) - (a.availability.totalDrivers || 0);
          if (driverDelta !== 0) return driverDelta;

          const etaDelta = (a.availability.closestDriverEtaMinutes || Number.POSITIVE_INFINITY)
            - (b.availability.closestDriverEtaMinutes || Number.POSITIVE_INFINITY);
          if (etaDelta !== 0) return etaDelta;
        }

        return a.originalIndex - b.originalIndex;
      })
      .map(({ originalIndex, availability, ...vehicle }) => vehicle);


    return rankedVehicles;
  }, [availabilityByVehicleId, hasAvailabilityResults, hasLoadedAvailability, pricedVehicles]);

  const selectedVehicle = useMemo(() => pricedVehicles.find((v) => v.id === selected), [pricedVehicles, selected]);
  const previewVehicle = useMemo(
    () => pricedVehicles.find((vehicle) => vehicle.id === previewVehicleId) || null,
    [previewVehicleId, pricedVehicles],
  );
  const resolvedTransportType = useMemo(
    () => resolveRideTransportType(
      routeState.transport_type,
      routeState.transportType,
      selectedVehicle?.transportType,
    ),
    [routeState.transportType, routeState.transport_type, selectedVehicle?.transportType],
  );
  const appliedPromoDiscount = Math.max(0, Number(appliedPromo?.breakdown?.discount_amount || 0));
  const discountedSelectedFare = Math.max(
    0,
    Number(appliedPromo?.breakdown?.fare_after_discount ?? selectedVehicle?.price ?? 0),
  );
  const selectedAvailability = selectedVehicle ? (availabilityByVehicleId[selectedVehicle.id] || DEFAULT_AVAILABILITY) : DEFAULT_AVAILABILITY;
  const previewAvailability = previewVehicle ? (availabilityByVehicleId[previewVehicle.id] || DEFAULT_AVAILABILITY) : DEFAULT_AVAILABILITY;
  const canProceed = Boolean(selectedVehicle) && !isFarePending;
  const hasBookableVehicles = useMemo(
    () => displayedVehicles.length > 0,
    [displayedVehicles],
  );
  const shouldUseDriverBidding = Boolean(
    routeState.intercity ||
    routeState.serviceType === 'intercity' ||
    routeState.transport_type === 'intercity' ||
    routeState.transportType === 'intercity',
  );
  const bidRideSettings = settings?.bidRide || {};
  const selectedBidStepAmount = shouldUseDriverBidding
    ? toConfiguredPositiveInteger(
        bidRideSettings.bidding_amount_increase_or_decrease,
        Number(selectedVehicle?.bidStepAmount || 10),
      )
    : Number(selectedVehicle?.bidStepAmount || 10);
  const bidLowPercentage = clampPercentage(bidRideSettings.user_bidding_low_percentage, 10);
  const bidHighPercentage = clampPercentage(bidRideSettings.user_bidding_high_percentage, 20);
  const normalizedBidLowPercentage = Math.min(bidLowPercentage, bidHighPercentage);
  const normalizedBidHighPercentage = Math.max(bidLowPercentage, bidHighPercentage);
  const selectedBidFloorFare = shouldUseDriverBidding
    ? alignBidAmountToStep({
        baseFare: Number(selectedVehicle?.price || 0),
        amount: Number(selectedVehicle?.price || 0) * (1 + (normalizedBidLowPercentage / 100)),
        stepAmount: selectedBidStepAmount,
        direction: 'up',
      })
    : Number(selectedVehicle?.price || 0);
  const selectedBidCeilingMaxFare = shouldUseDriverBidding
    ? alignBidAmountToStep({
        baseFare: Number(selectedVehicle?.price || 0),
        amount: Number(selectedVehicle?.price || 0) * (1 + (normalizedBidHighPercentage / 100)),
        stepAmount: selectedBidStepAmount,
        direction: 'up',
      })
    : Number(selectedVehicle?.price || 0);
  const selectedBidSteps = shouldUseDriverBidding
    ? Math.max(0, Math.round((selectedBidCeilingMaxFare - selectedBidFloorFare) / selectedBidStepAmount))
    : Number(selectedVehicle?.maxBidSteps || 5);
  const selectedBidIncrement = (selectedVehicle?.supportsBidding ? bidStepCount : 0) * selectedBidStepAmount;
  const selectedBidCeiling = shouldUseDriverBidding
    ? selectedBidFloorFare + selectedBidIncrement
    : Number(selectedVehicle?.price || 0) + selectedBidIncrement;
  const allowedPaymentMethods = useMemo(
    () => normalizeAllowedPaymentMethods(selectedAvailability?.allowedPaymentMethods),
    [selectedAvailability?.allowedPaymentMethods],
  );
  const paymentOptions = useMemo(
    () => PAYMENT_OPTIONS.filter((option) => allowedPaymentMethods.includes(option.id)),
    [allowedPaymentMethods],
  );
  const onlineDrivers = selectedAvailability.drivers || [];

  useEffect(() => {
    if (!paymentOptions.length) {
      return;
    }

    const normalizedCurrent = normalizeSelectedPaymentState(paymentMethod);
    if (!paymentOptions.some((option) => option.id === normalizedCurrent)) {
      setPaymentMethod(paymentOptions[0].stateValue);
    }
  }, [paymentMethod, paymentOptions]);

  const clearAppliedPromo = (nextFeedback = '') => {
    setAppliedPromo(null);
    setApplyingPromoCode('');
    setPromoError('');
    setPromoFeedback(nextFeedback);
  };

  const applyPromoCode = async (rawCode) => {
    const code = String(rawCode || '').trim().toUpperCase();

    if (!serviceLocationId) {
      setPromoError('Pickup zone is missing for this ride.');
      setPromoFeedback('');
      return false;
    }

    if (!selectedVehicle) {
      setPromoError('Select a vehicle before applying a coupon.');
      setPromoFeedback('');
      return false;
    }

    if (!code) {
      setPromoError('Enter a coupon code.');
      setPromoFeedback('');
      return false;
    }

    setApplyingPromoCode(code);
    setPromoError('');
    setPromoFeedback('');

    try {
      const response = await userService.validatePromo({
        code,
        fare: Number(selectedVehicle.price || 0),
        service_location_id: serviceLocationId,
        transport_type: resolvedTransportType,
      });
      const payload = unwrap(response);

      if (!payload?.eligible) {
        setAppliedPromo(null);
        setPromoError(payload?.message || 'This coupon is not valid for this ride.');
        return false;
      }

      setAppliedPromo(payload);
      setPromoCodeInput(code);
      setPromoFeedback(`${code} applied. You save ${formatCurrency(payload?.breakdown?.discount_amount || 0)}.`);
      return true;
    } catch (error) {
      setAppliedPromo(null);
      setPromoError(error?.response?.data?.message || error?.message || 'Could not apply this coupon right now.');
      return false;
    } finally {
      setApplyingPromoCode('');
    }
  };

  useEffect(() => {
    let active = true;

    const loadPromos = async () => {
      if (!serviceLocationId) {
        if (active) {
          setAvailablePromos([]);
          clearAppliedPromo('');
        }
        return;
      }

      setIsLoadingPromos(true);

      try {
        const response = await userService.getAvailablePromos({
          service_location_id: serviceLocationId,
          transport_type: resolvedTransportType,
          limit: 20,
        });

        if (!active) {
          return;
        }

        const promos = Array.isArray(unwrap(response)) ? unwrap(response) : [];
        setAvailablePromos(promos);

        if (appliedPromo?.promo?.code) {
          const stillAvailable = promos.some((promo) => String(promo?.code || '').toUpperCase() === String(appliedPromo.promo.code || '').toUpperCase());
          if (!stillAvailable) {
            clearAppliedPromo('Coupon removed because it does not apply in this zone.');
          }
        }
      } catch (_error) {
        if (active) {
          setAvailablePromos([]);
        }
      } finally {
        if (active) {
          setIsLoadingPromos(false);
        }
      }
    };

    loadPromos();

    return () => {
      active = false;
    };
  }, [resolvedTransportType, serviceLocationId]);

  useEffect(() => {
    if (!appliedPromo?.promo?.code || !selectedVehicle) {
      return;
    }

    let active = true;

    const refreshAppliedPromo = async () => {
      try {
        const response = await userService.validatePromo({
          code: appliedPromo.promo.code,
          fare: Number(selectedVehicle.price || 0),
          service_location_id: serviceLocationId,
          transport_type: resolvedTransportType,
        });
        const payload = unwrap(response);

        if (!active) {
          return;
        }

        if (!payload?.eligible) {
          clearAppliedPromo(payload?.message || 'Coupon removed because it is no longer valid for this fare.');
          return;
        }

        setAppliedPromo(payload);
      } catch (error) {
        if (active) {
          clearAppliedPromo(error?.response?.data?.message || 'Coupon removed because validation failed.');
        }
      }
    };

    refreshAppliedPromo();

    return () => {
      active = false;
    };
  }, [appliedPromo?.promo?.code, resolvedTransportType, selectedVehicle?.price, serviceLocationId]);

  useEffect(() => {
    const timer = setTimeout(handleScroll, 200);
    return () => clearTimeout(timer);
  }, [displayedVehicles, tripMetrics]);

  useEffect(() => {
    setBidStepCount(0);
  }, [selected]);

  useEffect(() => {
    selectedVehicleIdRef.current = selected;
  }, [selected]);

  useEffect(() => {
    if (!hasAvailabilityResults || !displayedVehicles.length) {
      return;
    }

    const firstAvailable = displayedVehicles.find((vehicle) => (availabilityByVehicleId[vehicle.id]?.totalDrivers || 0) > 0) || displayedVehicles[0];

    if (!selected && firstAvailable) {
      setSelected(firstAvailable.id);
    }
  }, [availabilityByVehicleId, displayedVehicles, hasAvailabilityResults, rideMode, selected]);

  useEffect(() => {
    let active = true;
    let intervalId;

    if (isResolvingServiceLocation) {
      setHasLoadedAvailability(false);
      return undefined;
    }

    const fetchVehicleAvailabilities = async (vehicleSubset, { replace = false, silent = false } = {}) => {
      const fetchableVehicles = (Array.isArray(vehicleSubset) ? vehicleSubset : []).filter((vehicle) => vehicle?.vehicleTypeId);

      if (!fetchableVehicles.length) {
        if (replace) {
          availabilityHistoryRef.current = {};
          setAvailabilityByVehicleId({});
        }
        if (active) {
          setHasLoadedAvailability(true);
        }
        return;
      }

      if (!silent) {
        setIsLoadingDrivers(true);
      }
      setDriverLoadError('');

      try {
        const responses = await Promise.all(
          fetchableVehicles.map(async (vehicle) => {
            const response = await api.get('/rides/available-drivers', {
              params: {
                vehicleTypeId: vehicle.vehicleTypeId,
                vehicleIconType: vehicle.iconType,
                lng: pickupCoords[0],
                lat: pickupCoords[1],
                service_location_id: serviceLocationId,
                transport_type: vehicle.transportType || routeState.transport_type || routeState.transportType || 'taxi',
              },
            });

            return [vehicle.id, { ...DEFAULT_AVAILABILITY, ...unwrap(response) }];
          }),
        );

        if (!active) {
          return;
        }

        setAvailabilityByVehicleId((current) => {
          const base = replace ? {} : current;
          const nextEntries = { ...base };

          responses.forEach(([vehicleId, payload]) => {
            const previousDrivers = availabilityHistoryRef.current?.[vehicleId]?.drivers || current?.[vehicleId]?.drivers || [];
            nextEntries[vehicleId] = {
              ...payload,
              drivers: attachDriverMotionMetadata(payload?.drivers, previousDrivers),
            };
          });

          availabilityHistoryRef.current = nextEntries;
          return nextEntries;
        });
      } catch (error) {
        if (active) {
          if (replace) {
            availabilityHistoryRef.current = {};
            setAvailabilityByVehicleId({});
          }
          setDriverLoadError(error.message || 'Could not load online drivers.');
        }
      } finally {
        if (active) {
          if (!silent) {
            setIsLoadingDrivers(false);
          }
          setHasLoadedAvailability(true);
        }
      }
    };

    if (!vehicles.length) {
      availabilityHistoryRef.current = {};
      setAvailabilityByVehicleId({});
      setHasLoadedAvailability(false);
      return undefined;
    }

    setHasLoadedAvailability(false);
    fetchVehicleAvailabilities(vehicles, { replace: true });

    const pollSelectedVehicle = () => {
      if (document.visibilityState !== 'visible') {
        return;
      }

      const activeVehicle =
        vehicles.find((vehicle) => vehicle.id === selectedVehicleIdRef.current)
        || vehicles.find((vehicle) => vehicle.vehicleTypeId);

      if (!activeVehicle) {
        return;
      }

      fetchVehicleAvailabilities([activeVehicle], { silent: true });
    };

    intervalId = setInterval(pollSelectedVehicle, 8000);

    const handleVisibilityChange = () => {
      if (document.visibilityState === 'visible') {
        pollSelectedVehicle();
      }
    };

    document.addEventListener('visibilitychange', handleVisibilityChange);

    return () => {
      active = false;
      clearInterval(intervalId);
      document.removeEventListener('visibilitychange', handleVisibilityChange);
    };
  }, [isResolvingServiceLocation, pickupCoords, routeState.transportType, routeState.transport_type, serviceLocationId, vehicles]);

  const isInitialVehicleResultsLoading =
    isLoadingVehicles ||
    isResolvingServiceLocation ||
    (vehicles.length > 0 && !hasLoadedAvailability && !driverLoadError);

  const openPicker = (inputRef) => {
    if (typeof inputRef.current?.showPicker === 'function') {
      inputRef.current.showPicker();
      return;
    }

    inputRef.current?.focus();
    inputRef.current?.click();
  };

  const openLocationEditor = () => {
    navigate(`${routePrefix}/ride/select-location`, {
      state: {
        pickup,
        drop,
        pickupCoords,
        dropCoords,
        stops,
        service_location_id: serviceLocationId,
        zone_id: zoneId,
        selectedCategory: routeState.selectedCategory, // Forward category filter
      },
    });
  };

  const proceedToBooking = () => {
    if (!selectedVehicle) {
      return;
    }

    setShowBidModal(false);
    const baseFare = Number(selectedVehicle.price || 0);
    const finalFare = appliedPromo?.breakdown?.fare_after_discount ?? baseFare;
    const historySafeVehicle = createHistorySafeVehicle(selectedVehicle);

    navigate(`${routePrefix}/ride/searching`, {
      state: {
        pickup,
        drop,
        pickupCoords,
        dropCoords,
        stops,
        zone_id: zoneId,
        service_location_id: serviceLocationId,
        transport_type: resolvedTransportType,
        vehicle: historySafeVehicle,
        vehicleTypeId: historySafeVehicle?.vehicleTypeId || '',
        vehicleIconType: historySafeVehicle?.iconType || '',
        vehicleIconUrl: historySafeVehicle?.vehicleIconUrl || historySafeVehicle?.icon || '',
        paymentMethod,
        fare: finalFare,
        baseFare,
        promo_code: appliedPromo?.promo?.code || '',
        promo: appliedPromo?.promo || null,
        promoBreakdown: appliedPromo?.breakdown || null,
        bookingMode: selectedVehicle.supportsBidding ? 'bidding' : 'normal',
        pricingNegotiationMode: selectedVehicle.supportsBidding
          ? shouldUseDriverBidding
            ? 'driver_bid'
            : 'user_increment_only'
          : 'none',
        bidStepAmount: selectedBidStepAmount,
        bidFloorFare: selectedBidFloorFare,
        bidCeilingMaxFare: selectedBidCeilingMaxFare,
        userMaxBidFare: selectedVehicle.supportsBidding && shouldUseDriverBidding ? selectedBidCeiling : finalFare,
        bidIncrement: selectedVehicle.supportsBidding && shouldUseDriverBidding ? selectedBidIncrement : 0,
        estimatedDistanceMeters: tripMetrics.distanceMeters,
        estimatedDurationMinutes: tripMetrics.durationMinutes,
        rideMode,
        scheduledAt: rideMode === 'schedule' ? new Date(scheduledAt).toISOString() : null,
        allowedPaymentMethods,
        searchNonce: `${Date.now()}-${Math.random().toString(36).slice(2)}`,
      },
    });
  };

  const handleBook = () => {
    if (!selectedVehicle) {
      return;
    }

    if (rideMode === 'schedule') {
      const parsedSchedule = new Date(scheduledAt);

      if (!scheduledAt || Number.isNaN(parsedSchedule.getTime())) {
        setScheduleError('Choose a valid schedule date and time.');
        return;
      }

      if (parsedSchedule.getTime() <= Date.now() + 60 * 1000) {
        setScheduleError('Schedule time must be at least 1 minute ahead.');
        return;
      }

      if (scheduledAt < minScheduledAt) {
        setScheduleError('Schedule time cannot be earlier than now.');
        return;
      }

      if (scheduledAt > maxScheduledAt) {
        setScheduleError('Advance booking is available for up to 7 days only.');
        return;
      }
    }

    setScheduleError('');

    if (selectedVehicle.supportsBidding && shouldUseDriverBidding) {
      setShowBidModal(true);
      return;
    }

    proceedToBooking();
  };

  return {
    location,
    searchParams,
    queryVehicleType,
    localVehicleType,
    routeState,
    vehicles,
    setVehicles,
    availabilityByVehicleId,
    setAvailabilityByVehicleId,
    selected,
    setSelected,
    paymentMethod,
    setPaymentMethod,
    showPaymentModal,
    setShowPaymentModal,
    showCouponModal,
    setShowCouponModal,
    showBidModal,
    setShowBidModal,
    previewVehicleId,
    setPreviewVehicleId,
    availablePromos,
    setAvailablePromos,
    isLoadingPromos,
    setIsLoadingPromos,
    promoCodeInput,
    setPromoCodeInput,
    promoFeedback,
    setPromoFeedback,
    promoError,
    setPromoError,
    applyingPromoCode,
    setApplyingPromoCode,
    appliedPromo,
    setAppliedPromo,
    rideMode,
    setRideMode,
    scheduledAt,
    setScheduledAt,
    scheduleError,
    setScheduleError,
    bidStepCount,
    setBidStepCount,
    isLoadingVehicles,
    setIsLoadingVehicles,
    isLoadingDrivers,
    setIsLoadingDrivers,
    vehicleLoadError,
    setVehicleLoadError,
    driverLoadError,
    setDriverLoadError,
    pricingRules,
    setPricingRules,
    isLoadingPricingRules,
    setIsLoadingPricingRules,
    tripMetrics,
    setTripMetrics,
    routeMetricsCacheRef,
    isResolvingTripMetrics,
    setIsResolvingTripMetrics,
    showScrollArrow,
    setShowScrollArrow,
    scrollRef,
    availabilityHistoryRef,
    selectedVehicleIdRef,
    scheduledAtInputRef,
    navigate,
    settings,
    pickup,
    drop,
    pickupCoords,
    dropCoords,
    stops,
    routeServiceLocationId,
    routeZoneId,
    hasCompleteRouteZoneContext,
    resolvedServiceLocationId,
    setResolvedServiceLocationId,
    resolvedZoneId,
    setResolvedZoneId,
    isResolvingServiceLocation,
    setIsResolvingServiceLocation,
    hasLoadedAvailability,
    setHasLoadedAvailability,
    serviceLocationId,
    zoneId,
    routePrefix,
    pickupPosition,
    dropPosition,
    isMapLoaded,
    mapLoadError,
    minScheduledAt,
    maxScheduledAt,
    handleScroll,
    pricedVehicles,
    isFarePending,
    hasAvailabilityResults,
    displayedVehicles,
    selectedVehicle,
    previewVehicle,
    resolvedTransportType,
    appliedPromoDiscount,
    discountedSelectedFare,
    selectedAvailability,
    previewAvailability,
    canProceed,
    hasBookableVehicles,
    shouldUseDriverBidding,
    bidRideSettings,
    selectedBidStepAmount,
    bidLowPercentage,
    bidHighPercentage,
    normalizedBidLowPercentage,
    normalizedBidHighPercentage,
    selectedBidFloorFare,
    selectedBidCeilingMaxFare,
    selectedBidSteps,
    selectedBidIncrement,
    selectedBidCeiling,
    allowedPaymentMethods,
    paymentOptions,
    onlineDrivers,
    clearAppliedPromo,
    applyPromoCode,
    isInitialVehicleResultsLoading,
    openPicker,
    openLocationEditor,
    proceedToBooking,
    handleBook,
    MAP_CONTAINER_STYLE,
    SELECT_VEHICLE_MAP_OPTIONS,
    toLatLng,
    getDriverPosition,
    getOverlayCenterOffset,
    getMarkerDimensionsForZoom,
    normalizeHeading,
    calculateHeadingBetween,
    buildFallbackRoute,
    getRouteCacheKey,
    unwrap,
    PAYMENT_OPTIONS,
    DEFAULT_AVAILABILITY,
    normalizeAllowedPaymentMethods,
    attachDriverMotionMetadata,
    toPaymentStateValue,
    normalizeSelectedPaymentState,
    resolveRideTransportType,
    getVehicleTypes,
    getTypeLabel,
    getIconValue,
    getVehicleMapIcon,
    getVehiclePreviewImage,
    getCapacity,
    AVERAGE_CITY_SPEED_KMPH,
    calculateDistanceMeters,
    estimateDurationMinutes,
    getFallbackVehicleEstimate,
    getSetPriceRows,
    getSetPricePaginationMeta,
    normalizeId,
    getZoneServiceLocationId,
    getZoneId,
    isZoneActive,
    toZonePoint,
    normalizeZonePath,
    isPointInPolygon,
    toFiniteNumber,
    getRuleServiceLocationId,
    getRuleZoneId,
    sortPricingRules,
    isActiveRidePricingRule,
    matchesTransportType,
    findBestPricingRule,
    calculateEstimatedFare,
    getDropTime,
    formatDistanceLabel,
    formatCurrency,
    formatPromoSummary,
    toConfiguredPositiveInteger,
    clampPercentage,
    alignBidAmountToStep,
    getBidFareBounds,
    formatVehicleFare,
    pad,
    formatDateTimeInputValue,
    getMinScheduledDateTime,
    getMaxScheduledDateTime,
    formatScheduledDisplay,
    formatAvailabilityLine,
    formatDispatchLabel,
    getAvailabilityBadge,
    getNormalizedCategory,
    normalizeVehicleType,
    createHistorySafeVehicle,
  }
}
