// Generated by tools/extract-hook.js from Frontend/src/../../mobile-user/.parts/tmp/SearchingDriver.jsx (SearchingDriver), then edited by hand
// where the web code touched the DOM. The logic is the web page's own.
/* eslint-disable react-hooks/exhaustive-deps, no-unused-vars, no-empty */
import { useCallback, useEffect, useMemo, useState, useRef } from 'react'
import { useNavigate, useLocation } from '../../lib/webRouter'
import { Navigation } from 'lucide-react-native'
import { socketService } from '../api/socket'
import api from '../api/client'
import { getLocalUserToken } from '../services/authService'
import { getCurrentRide, isActiveCurrentRide, saveCurrentRide } from '../services/currentRideService'
import { useBaseGoogleMapsLoader } from '../utils/googleMaps'
import { scheduleScheduledRideReminders } from '../store/upcomingRideReminderService'
import { toHistorySafeState } from '../utils/historyState'
import { getTaxiUserRoutePrefix } from '../utils/routePrefix'
import { sessionStore } from '../../lib/storage'
import { BackHandler } from 'react-native'

const LuxuryIcon = require('../../../assets/taxi/icons/Luxury.png')
const PremiumIcon = require('../../../assets/taxi/icons/Premium.png')
const SuvIcon = require('../../../assets/taxi/icons/SUV.png')
const BikeIcon = require('../../../assets/taxi/icons/bike.png')
const CarIcon = require('../../../assets/taxi/icons/car.png')
const AutoIcon = require('../../../assets/taxi/icons/auto.png')
const MAP_OPTIONS = {
  disableDefaultUI: true,
  styles: [
    { "elementType": "geometry", "stylers": [{ "color": "#f5f5f5" }] },
    { "elementType": "labels.icon", "stylers": [{ "visibility": "off" }] },
    { "elementType": "labels.text.fill", "stylers": [{ "color": "#616161" }] },
    { "elementType": "labels.text.stroke", "stylers": [{ "color": "#f5f5f5" }] },
    { "featureType": "administrative.land_parcel", "elementType": "labels.text.fill", "stylers": [{ "color": "#bdbdbd" }] },
    { "featureType": "poi", "elementType": "geometry", "stylers": [{ "color": "#eeeeee" }] },
    { "featureType": "poi", "elementType": "labels.text.fill", "stylers": [{ "color": "#757575" }] },
    { "featureType": "poi.park", "elementType": "geometry", "stylers": [{ "color": "#e5e5e5" }] },
    { "featureType": "poi.park", "elementType": "labels.text.fill", "stylers": [{ "color": "#9e9e9e" }] },
    { "featureType": "road", "elementType": "geometry", "stylers": [{ "color": "#ffffff" }] },
    { "featureType": "road.arterial", "elementType": "labels.text.fill", "stylers": [{ "color": "#757575" }] },
    { "featureType": "road.highway", "elementType": "geometry", "stylers": [{ "color": "#dadada" }] },
    { "featureType": "road.highway", "elementType": "labels.text.fill", "stylers": [{ "color": "#616161" }] },
    { "featureType": "road.local", "elementType": "labels.text.fill", "stylers": [{ "color": "#9e9e9e" }] },
    { "featureType": "transit.line", "elementType": "geometry", "stylers": [{ "color": "#e5e5e5" }] },
    { "featureType": "transit.station", "elementType": "geometry", "stylers": [{ "color": "#eeeeee" }] },
    { "featureType": "water", "elementType": "geometry", "stylers": [{ "color": "#c9c9c9" }] },
    { "featureType": "water", "elementType": "labels.text.fill", "stylers": [{ "color": "#9e9e9e" }] }
  ]
}

const unwrap = (response) => response?.data?.data || response?.data || response;

const getVehicleIcon = (type = 'car') => {
  const val = String(type).toLowerCase();
  if (val.includes('bike')) return BikeIcon;
  if (val.includes('auto')) return AutoIcon;
  if (val.includes('lux')) return LuxuryIcon;
  if (val.includes('premium')) return PremiumIcon;
  if (val.includes('suv')) return SuvIcon;
  return CarIcon;
}

const getOverlayCenterOffset = (width, height) => ({
  x: -(width / 2),
  y: -(height / 2),
});

const SEARCH_FALLBACK_POLL_DELAY_MS = 10000;

const SEARCH_FALLBACK_POLL_INTERVAL_MS = 10000;

const clampVehicleCount = (value) => {
  const numeric = Number(value);

  if (!Number.isFinite(numeric) || numeric <= 0) {
    return 4;
  }

  return Math.max(3, Math.min(8, Math.round(numeric)));
}

const buildAvailableVehicleMarkers = (center, count) => {
  const safeCount = clampVehicleCount(count);
  const lat = Number(center?.lat || 0);
  const lng = Number(center?.lng || 0);

  return Array.from({ length: safeCount }, (_, index) => {
    const angle = ((Math.PI * 2) / safeCount) * index + (index % 2 ? 0.28 : -0.12);
    const radius = 0.0022 + (index % 3) * 0.00045;

    return {
      id: `available-driver-${index}`,
      position: {
        lat: lat + Math.sin(angle) * radius,
        lng: lng + Math.cos(angle) * radius,
      },
      heading: (angle * 180) / Math.PI + 90,
      delay: index * 0.18,
    };
  });
}

const DRIVER_PLACEHOLDER = { name: 'Captain', rating: '4.9', vehicle: 'Taxi', plate: 'Assigned', phone: '', eta: 2 };

const STAGES = { SEARCHING: 'searching', ACCEPTED: 'accepted', COMPLETING: 'completing' };

const CONSUMED_SEARCH_NONCE_PREFIX = 'Dima Hasao 24_consumed_search_nonce:';

const ACTIVE_SEARCH_NONCES = new Set();

const ACTIVE_SEARCH_NONCE_CLEANUPS = new Map();

const normalizeDriver = (driver = {}) => ({
  name: driver.name || 'Captain',
  rating: driver.rating || '4.9',
  vehicle: driver.vehicle || driver.vehicleType || driver.vehicle_type || 'Taxi',
  vehicleType: driver.vehicleType || driver.vehicle_type || driver.vehicle || 'Taxi',
  plate: driver.plate || driver.vehicleNumber || driver.vehicle_number || 'Assigned',
  vehicleNumber: driver.vehicleNumber || driver.vehicle_number || driver.plate || 'Assigned',
  phone: driver.phone || driver.mobile || driver.phoneNumber || '',
  profileImage: driver.profileImage || driver.profile_image || driver.image || driver.avatar || driver.selfie || '',
  vehicleImage: driver.vehicleImage || driver.vehicle_image || driver.vehiclePhoto || driver.vehicle_photo || driver.vehicle?.image || '',
  vehicleColor: driver.vehicleColor || driver.vehicle_color || driver.vehicle?.vehicleColor || driver.vehicle?.vehicle_color || '',
  vehicleMake: driver.vehicleMake || driver.vehicle_make || driver.vehicle?.vehicleMake || driver.vehicle?.vehicle_make || '',
  vehicleModel: driver.vehicleModel || driver.vehicle_model || driver.vehicle?.vehicleModel || driver.vehicle?.vehicle_model || '',
  vehicleIconUrl: driver.vehicleIconUrl || driver.map_icon || driver.icon || '',
  eta: driver.eta || 2,
});

const formatCurrency = (amount) => `Rs ${Math.round(Number(amount) || 0)}`;

const formatScheduledDateTime = (value) => {
  if (!value) {
    return 'Scheduled';
  }

  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return 'Scheduled';
  }

  return parsed.toLocaleString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

const buildHistoryState = (value) => toHistorySafeState(value) || {};

export function useSearchingDriver() {
  const navigate = useNavigate();
  const location = useLocation();
  const routeState = useMemo(() => location.state || {}, [location.state]);
  const [stage, setStage] = useState(STAGES.SEARCHING);
  const [showCancelConfirm, setShowCancelConfirm] = useState(false);
  const [driver, setDriver] = useState(DRIVER_PLACEHOLDER);
  const [rideOtp, setRideOtp] = useState('');
  const [searchStatus, setSearchStatus] = useState('Connecting with drivers nearby');
  const [nearbyVehicleCount, setNearbyVehicleCount] = useState(4);
  const [scheduledStatus, setScheduledStatus] = useState(() => (routeState.scheduledAt ? 'saving' : 'idle'));
  const [scheduledError, setScheduledError] = useState('');
  const [now, setNow] = useState(() => Date.now());
  const [fareHistory, setFareHistory] = useState(() => {
    const initialFare = Number(routeState.fare || routeState.vehicle?.price || 0);
    return initialFare > 0 ? [initialFare] : [];
  });
  const timerRef = useRef(null);
  const activeRidePollRef = useRef(null);
  const activeRidePollStartTimeoutRef = useRef(null);
  const requestStartedRef = useRef(false);
  const cleanupSearchRef = useRef(null);
  const cleanupDelayRef = useRef(null);
  const trackingStartedRef = useRef(false);
  const driverRef = useRef(driver);
  const cancellingRef = useRef(false);
  const routePrefix = useMemo(
    () => (getTaxiUserRoutePrefix(location.pathname)),
    [location.pathname],
  );
  const userHomeRoute = routePrefix || '/taxi/user';
  const selectedVehicleTypeId = useMemo(
    () => routeState.vehicleTypeId || routeState.vehicle?.vehicleTypeId,
    [routeState],
  );
  const activeRideIdRef = useRef('');
  const searchNonce = String(routeState.searchNonce || '');
  const isScheduledRide = Boolean(routeState.scheduledAt);
  const isSearching = stage === STAGES.SEARCHING;
  const isAccepted = stage === STAGES.ACCEPTED || stage === STAGES.COMPLETING;
  const appendFareHistory = (fare) => {
    const normalizedFare = Math.round(Number(fare || 0));
    if (!Number.isFinite(normalizedFare) || normalizedFare <= 0) {
      return;
    }
    setFareHistory((current) => (
      current[current.length - 1] === normalizedFare ? current : [...current, normalizedFare]
    ));
  };

  const { isLoaded } = useBaseGoogleMapsLoader();

  const pickupPos = useMemo(
    () => (
      routeState.pickupCoords
        ? { lng: routeState.pickupCoords[0], lat: routeState.pickupCoords[1] }
        : { lat: 22.7196, lng: 75.8577 }
    ),
    [routeState.pickupCoords],
  );

  const dropPos = useMemo(
    () => (
      routeState.dropCoords
        ? { lng: routeState.dropCoords[0], lat: routeState.dropCoords[1] }
        : null
    ),
    [routeState.dropCoords],
  );
  const availableVehicleIcon = useMemo(
    () => (
      routeState.vehicleIconUrl ||
      routeState.vehicle?.vehicleIconUrl ||
      routeState.vehicle?.icon ||
      getVehicleIcon(routeState.vehicleIconType || routeState.vehicle?.iconType || routeState.vehicle?.name)
    ),
    [routeState.vehicle?.icon, routeState.vehicle?.iconType, routeState.vehicle?.name, routeState.vehicle?.vehicleIconUrl, routeState.vehicleIconType, routeState.vehicleIconUrl],
  );
  const availableVehicleMarkers = useMemo(
    () => buildAvailableVehicleMarkers(pickupPos, nearbyVehicleCount),
    [nearbyVehicleCount, pickupPos],
  );
  const formattedScheduledTime = useMemo(
    () => formatScheduledDateTime(routeState.scheduledAt),
    [routeState.scheduledAt],
  );

  useEffect(() => {
    driverRef.current = driver;
  }, [driver]);

  useEffect(() => {
    if (!searchNonce) {
      navigate(userHomeRoute, { replace: true });
      return;
    }

    const nonceKey = `${CONSUMED_SEARCH_NONCE_PREFIX}${searchNonce}`;
    const pendingCleanup = ACTIVE_SEARCH_NONCE_CLEANUPS.get(searchNonce);
    if (pendingCleanup) {
      clearTimeout(pendingCleanup);
      ACTIVE_SEARCH_NONCE_CLEANUPS.delete(searchNonce);
    }

    if (ACTIVE_SEARCH_NONCES.has(searchNonce)) {
      return () => {
        const cleanupId = setTimeout(() => {
          ACTIVE_SEARCH_NONCES.delete(searchNonce);
          ACTIVE_SEARCH_NONCE_CLEANUPS.delete(searchNonce);
        }, 0);
        ACTIVE_SEARCH_NONCE_CLEANUPS.set(searchNonce, cleanupId);
      };
    }

    if (sessionStore.getItem(nonceKey)) {
      const activeRide = getCurrentRide();

      if (isActiveCurrentRide(activeRide)) {
        navigate(`${routePrefix}/ride/tracking`, {
          replace: true,
          state: activeRide,
        });
        setRideOtp(activeRide?.otp || '');
        return;
      }

      navigate(userHomeRoute, { replace: true });
      return;
    }

    sessionStore.setItem(nonceKey, '1');
    ACTIVE_SEARCH_NONCES.add(searchNonce);

    return () => {
      const cleanupId = setTimeout(() => {
        ACTIVE_SEARCH_NONCES.delete(searchNonce);
        ACTIVE_SEARCH_NONCE_CLEANUPS.delete(searchNonce);
      }, 0);
      ACTIVE_SEARCH_NONCE_CLEANUPS.set(searchNonce, cleanupId);
    };
  }, [navigate, routePrefix, searchNonce]);

  useEffect(() => {
    if (cleanupDelayRef.current) {
      clearTimeout(cleanupDelayRef.current);
      cleanupDelayRef.current = null;
    }

    if (requestStartedRef.current) {
      return () => {
        cleanupDelayRef.current = setTimeout(() => {
          cleanupSearchRef.current?.();
        }, 0);
      };
    }

    if (!searchNonce || !selectedVehicleTypeId) {
      setSearchStatus('Vehicle type missing. Please select a vehicle again.');
      navigate(userHomeRoute, { replace: true });
      return undefined;
    }

    requestStartedRef.current = true;
    let disposed = false;

    const onRideSearchUpdate = ({ matchedDrivers, radius }) => {
      setNearbyVehicleCount(clampVehicleCount(matchedDrivers));
      const radiusKm = radius ? (Number(radius) / 1000).toFixed(1) : '';
      setSearchStatus(
        matchedDrivers > 0
          ? `${matchedDrivers} captain${matchedDrivers > 1 ? 's' : ''} notified within ${radiusKm} km - waiting for acceptance`
          : `Searching within ${radiusKm} km`,
      );
    };

    const moveToTracking = ({ acceptedDriver, rideId, rideSnapshot }) => {
      if (disposed) {
        return;
      }

      if (trackingStartedRef.current) {
        return;
      }

      const nextDriver = normalizeDriver(acceptedDriver);
      const nextOtp = String(rideSnapshot?.otp || routeState?.otp || '');
      driverRef.current = nextDriver;
      setDriver(nextDriver);
      setStage(STAGES.ACCEPTED);
      setSearchStatus('Captain accepted your ride.');
      activeRideIdRef.current = String(rideId || activeRideIdRef.current || '');
      trackingStartedRef.current = true;
      saveCurrentRide({
        ...routeState,
        pickup: rideSnapshot?.pickupAddress || routeState.pickup,
        drop: rideSnapshot?.dropAddress || routeState.drop,
        pickupCoords: rideSnapshot?.pickupLocation?.coordinates || routeState.pickupCoords,
        dropCoords: rideSnapshot?.dropLocation?.coordinates || routeState.dropCoords,
        rideId: activeRideIdRef.current,
        otp: nextOtp,
        driver: nextDriver,
        fare: rideSnapshot?.fare || routeState.fare || routeState.baseFare || routeState.vehicle?.price || 22,
        vehicleIconUrl: rideSnapshot?.vehicleIconUrl || routeState.vehicleIconUrl || routeState.vehicle?.vehicleIconUrl || routeState.vehicle?.icon || '',
        paymentMethod: routeState.paymentMethod || 'Cash',
        status: 'accepted',
      });
      setRideOtp(nextOtp);

      clearTimeout(timerRef.current);
      clearInterval(activeRidePollRef.current);
      timerRef.current = setTimeout(() => {
        navigate(`${routePrefix}/ride/tracking`, {
          replace: true,
          state: buildHistoryState({
            ...routeState,
            pickup: rideSnapshot?.pickupAddress || routeState.pickup,
            drop: rideSnapshot?.dropAddress || routeState.drop,
            pickupCoords: rideSnapshot?.pickupLocation?.coordinates || routeState.pickupCoords,
            dropCoords: rideSnapshot?.dropLocation?.coordinates || routeState.dropCoords,
            rideId: activeRideIdRef.current,
            otp: nextOtp,
            driver: nextDriver,
            fare: rideSnapshot?.fare || routeState.fare || routeState.baseFare || routeState.vehicle?.price || 22,
            vehicleIconUrl: rideSnapshot?.vehicleIconUrl || routeState.vehicleIconUrl || routeState.vehicle?.vehicleIconUrl || routeState.vehicle?.icon || '',
            paymentMethod: routeState.paymentMethod || 'Cash',
          }),
        });
      }, 2200);
    };

    const onRideAccepted = ({ driver: acceptedDriver, rideId }) => {
      moveToTracking({ acceptedDriver, rideId });
    };

    const onRideState = (payload) => {
      if (!payload || String(payload.rideId || '') !== String(activeRideIdRef.current || '')) {
        return;
      }

      if (payload.status === 'accepted' || payload.liveStatus === 'accepted') {
        moveToTracking({ acceptedDriver: payload.driver, rideId: payload.rideId, rideSnapshot: payload });
      }
    };

    const hydrateAcceptedRide = async () => {
      if (disposed) {
        return null;
      }

      const activeResponse = await api.get('/rides/active/me');
      const activeRide = activeResponse?.data?.data || activeResponse?.data || activeResponse;

      if (!activeRide?.rideId) {
        return null;
      }

      return activeRide;
    };

    const onRideStatusUpdated = async (payload) => {
      if (!payload || String(payload.rideId || '') !== String(activeRideIdRef.current || '')) {
        return;
      }

      if (payload.status === 'accepted' || payload.liveStatus === 'accepted') {
        const activeRide = await hydrateAcceptedRide().catch(() => null);
        moveToTracking({
          acceptedDriver: activeRide?.driver || driverRef.current,
          rideId: payload.rideId,
          rideSnapshot: activeRide || payload,
        });
      }
    };

    const onRideCancelled = ({ reason }) => {
      const displayReason = reason === 'No drivers accepted the ride request' 
        ? 'No drivers available nearby'
        : (reason || 'No drivers accepted the ride request.');
      setSearchStatus(displayReason);
      setStage(STAGES.SEARCHING);
    };

    const onError = ({ message }) => {
      setSearchStatus(message || 'Could not request ride.');
    };

    socketService.on('rideSearchUpdate', onRideSearchUpdate);
    socketService.on('rideAccepted', onRideAccepted);
    socketService.on('ride:state', onRideState);
    socketService.on('ride:status:updated', onRideStatusUpdated);
    socketService.on('rideCancelled', onRideCancelled);
    socketService.on('errorMessage', onError);

    cleanupSearchRef.current = () => {
      if (disposed) {
        return;
      }

      disposed = true;
      requestStartedRef.current = false;
      clearTimeout(timerRef.current);
      clearTimeout(activeRidePollStartTimeoutRef.current);
      clearInterval(activeRidePollRef.current);
      activeRidePollStartTimeoutRef.current = null;
      activeRidePollRef.current = null;
      socketService.off('rideSearchUpdate', onRideSearchUpdate);
      socketService.off('rideAccepted', onRideAccepted);
      socketService.off('ride:state', onRideState);
      socketService.off('ride:status:updated', onRideStatusUpdated);
      socketService.off('rideCancelled', onRideCancelled);
      socketService.off('errorMessage', onError);
    };

    (async () => {
      try {
        let userToken = getLocalUserToken();

        if (!userToken) {
          navigate('/taxi/user/login', { replace: true });
          return;
        }

        if (disposed) {
          return;
        }

        const rideRequestConfig = userToken
          ? {
            headers: {
              Authorization: `Bearer ${userToken}`,
            },
            timeout: 15000,
          }
          : { timeout: 15000 };

        const requestPayload = {
          pickup: routeState.pickupCoords || [75.9048, 22.7039],
          drop: routeState.dropCoords || [75.8937, 22.7533],
          pickupAddress: routeState.pickup || '',
          dropAddress: routeState.drop || '',
          fare: routeState.baseFare || routeState.fare || routeState.vehicle?.price || 22,
          estimatedDistanceMeters: routeState.estimatedDistanceMeters || 0,
          estimatedDurationMinutes: routeState.estimatedDurationMinutes || 0,
          vehicleTypeId: selectedVehicleTypeId,
          vehicleTypeIds: selectedVehicleTypeId ? [selectedVehicleTypeId] : [],
          vehicleIconType: routeState.vehicleIconType || routeState.vehicle?.iconType,
          vehicleIconUrl: routeState.vehicleIconUrl || routeState.vehicle?.vehicleIconUrl || routeState.vehicle?.icon || '',
          paymentMethod: routeState.paymentMethod || 'Cash',
          serviceType: routeState.serviceType || 'ride',
          intercity: routeState.intercity || undefined,
          promo_code: routeState.promo_code || '',
          zone_id: routeState.zone_id || routeState.zoneId || '',
          service_location_id: routeState.service_location_id || routeState.serviceLocationId || '',
          transport_type: routeState.transport_type || routeState.transportType || routeState.vehicle?.transportType || 'taxi',
          scheduledAt: routeState.scheduledAt || null,
        };


        const response = await api.post('/rides', requestPayload, rideRequestConfig);

        if (disposed) {
          return;
        }

        const payload = response?.data || response;
        const ride = payload?.data?.ride || payload?.ride || payload;
        const rideId = ride?._id || ride?.id || payload?.realtime?.rideId;
        const normalizedRideId = String(rideId || '');
        activeRideIdRef.current = normalizedRideId;
        if (isScheduledRide) {
          scheduleScheduledRideReminders({
            ...ride,
            rideId: normalizedRideId,
            scheduledAt: ride?.scheduledAt || routeState.scheduledAt || null,
            pickupAddress: ride?.pickupAddress || routeState.pickup || '',
            dropAddress: ride?.dropAddress || routeState.drop || '',
            status: ride?.status || 'scheduled',
            liveStatus: ride?.liveStatus || 'scheduled',
          });
          setScheduledStatus('scheduled');
          setSearchStatus('Your ride has been scheduled successfully.');
          return;
        }
        const socket = socketService.connect({ role: 'user', token: userToken });

        if (socket && rideId) {
          socketService.emit('joinRide', { rideId });
          socketService.emit('ride:join', { rideId });
        }

        const pollActiveRide = async () => {
          if (disposed) {
            return;
          }

          try {
            const activeRide = await hydrateAcceptedRide();

            if (disposed || !activeRide?.rideId) {
              return;
            }

            const isThisRide = String(activeRide.rideId || '') === normalizedRideId;
            const isAcceptedRide = ['accepted', 'arriving', 'started', 'ongoing'].includes(String(activeRide.status || activeRide.liveStatus || '').toLowerCase());

            if (isThisRide && isAcceptedRide) {
              moveToTracking({
                acceptedDriver: activeRide.driver || driverRef.current,
                rideId: activeRide.rideId,
                rideSnapshot: activeRide,
              });
            }
          } catch (_error) {
            // Socket remains the primary path; polling is only a race-condition fallback.
          }
        };

        clearInterval(activeRidePollRef.current);
        activeRidePollRef.current = null;
        const startFallbackPolling = () => {
          if (disposed || trackingStartedRef.current) {
            return;
          }

          pollActiveRide();
          activeRidePollRef.current = setInterval(pollActiveRide, SEARCH_FALLBACK_POLL_INTERVAL_MS);
        };
        clearTimeout(activeRidePollStartTimeoutRef.current);
        activeRidePollStartTimeoutRef.current = setTimeout(
          startFallbackPolling,
          SEARCH_FALLBACK_POLL_DELAY_MS,
        );

        if (!disposed) {
          setSearchStatus('Booking created. Notifying nearby drivers...');
        }
      } catch (error) {
        console.error('[searching-driver] Ride creation error:', error);
        if (!disposed) {
          const errorMessage =
            error?.error ||
            error?.message ||
            error?.response?.data?.error ||
            error?.response?.data?.message ||
            'Network error or server down';
          const isNoDrivers = errorMessage.toLowerCase().includes('no driver') || errorMessage.toLowerCase().includes('not available');

          if (isScheduledRide) {
            setScheduledStatus('error');
            setScheduledError(errorMessage);
            setSearchStatus(errorMessage);
            return;
          }
          setSearchStatus(isNoDrivers ? 'No drivers available nearby' : errorMessage);
          
          if (!isNoDrivers) {
            setTimeout(() => {
              if (!disposed) navigate(userHomeRoute, { replace: true });
            }, 3000);
          }
        }
      }
    })();

    return () => {
      cleanupDelayRef.current = setTimeout(() => {
        cleanupSearchRef.current?.();
      }, 0);
    };
  }, [isScheduledRide, navigate, routePrefix, routeState, searchNonce, selectedVehicleTypeId, userHomeRoute]);

  const handleCancel = useCallback(async () => {
    if (cancellingRef.current) {
      return;
    }

    cancellingRef.current = true;
    clearTimeout(timerRef.current);

    const rideId = activeRideIdRef.current;

    try {
      if (rideId) {
        await api.patch(`/rides/${rideId}/cancel`);
      }
    } catch (_error) {
      // Navigation still proceeds even if the cancel request races with another state update.
    }

    navigate(userHomeRoute, { replace: true });
  }, [navigate, userHomeRoute]);

  useEffect(() => {
    if (!isSearching || trackingStartedRef.current) {
      return undefined;
    }

    // Web: a popstate guard turns the browser's back into "cancel". Native: the hardware back button does the same.
    const sub = BackHandler.addEventListener('hardwareBackPress', () => {
      if (trackingStartedRef.current || cancellingRef.current) {
        return true;
      }
      handleCancel();
      return true;
    });

    return () => {
      sub.remove();
    };
  }, [handleCancel, isSearching, searchNonce]);

  const navigateAfterCancel = async (nextState = {}) => {
    const rideId = activeRideIdRef.current;

    try {
      if (rideId) {
        await api.patch(`/rides/${rideId}/cancel`);
      }
    } catch {
      // Navigation should still proceed even if cancellation races with another update.
    }

    navigate(`${routePrefix}/ride/select-vehicle`, {
      replace: true,
      state: buildHistoryState({
        ...routeState,
        ...nextState,
      }),
    });
  };

  return {
    navigate,
    location,
    routeState,
    stage,
    setStage,
    showCancelConfirm,
    setShowCancelConfirm,
    driver,
    setDriver,
    rideOtp,
    setRideOtp,
    searchStatus,
    setSearchStatus,
    nearbyVehicleCount,
    setNearbyVehicleCount,
    scheduledStatus,
    setScheduledStatus,
    scheduledError,
    setScheduledError,
    now,
    setNow,
    fareHistory,
    setFareHistory,
    timerRef,
    activeRidePollRef,
    activeRidePollStartTimeoutRef,
    requestStartedRef,
    cleanupSearchRef,
    cleanupDelayRef,
    trackingStartedRef,
    driverRef,
    cancellingRef,
    routePrefix,
    userHomeRoute,
    selectedVehicleTypeId,
    activeRideIdRef,
    searchNonce,
    isScheduledRide,
    isSearching,
    isAccepted,
    appendFareHistory,
    isLoaded,
    pickupPos,
    dropPos,
    availableVehicleIcon,
    availableVehicleMarkers,
    formattedScheduledTime,
    handleCancel,
    navigateAfterCancel,
    MAP_OPTIONS,
    unwrap,
    getVehicleIcon,
    getOverlayCenterOffset,
    SEARCH_FALLBACK_POLL_DELAY_MS,
    SEARCH_FALLBACK_POLL_INTERVAL_MS,
    clampVehicleCount,
    buildAvailableVehicleMarkers,
    DRIVER_PLACEHOLDER,
    STAGES,
    CONSUMED_SEARCH_NONCE_PREFIX,
    ACTIVE_SEARCH_NONCES,
    ACTIVE_SEARCH_NONCE_CLEANUPS,
    normalizeDriver,
    formatCurrency,
    formatScheduledDateTime,
    buildHistoryState,
  }
}
